import { ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { NotificationType, SubscriptionPlan, SubscriptionStatus } from '@prisma/client';
import type { AuthenticatedUser } from '../../infrastructure/auth/auth.types'; import { PrismaService } from '../../infrastructure/database/prisma.service'; import { AuditService } from '../audit/audit.service'; import { NotificationsService } from '../notifications/notifications.service';
export const plans: Record<SubscriptionPlan,{staffLimit:number;features:string[]}>={TRIAL:{staffLimit:20,features:['自動生成','CSV・印刷','バックアップ']},STANDARD:{staffLimit:50,features:['自動生成','CSV・印刷','バックアップ','監査ログ']},PROFESSIONAL:{staffLimit:200,features:['すべての既存機能']}};
@Injectable() export class SubscriptionsService { constructor(private prisma:PrismaService,private audit:AuditService,private notifications:NotificationsService){}
 async get(user:AuthenticatedUser){const subscription=await this.find(user.tenantId);const activeStaffCount=await this.prisma.staff.count({where:{tenantId:user.tenantId,isActive:true}}); await this.trialNotifications(user,subscription); return {...subscription,activeStaffCount,remainingStaffSlots:Math.max(0,subscription.staffLimit-activeStaffCount),features:plans[subscription.plan].features,readOnly:this.readOnly(subscription)};}
 async find(tenantId:string){const sub=await this.prisma.tenantSubscription.findUnique({where:{tenantId}}); if(!sub)return {tenantId,plan:SubscriptionPlan.STANDARD,status:SubscriptionStatus.ACTIVE,staffLimit:50,trialStartedAt:null,trialEndsAt:null,currentPeriodStartedAt:null,currentPeriodEndsAt:null,suspendedAt:null,cancelledAt:null,cancellationReason:null,suspensionReason:null}; if(sub.status===SubscriptionStatus.TRIAL&&sub.trialEndsAt&&sub.trialEndsAt<new Date()) return {...sub,status:SubscriptionStatus.EXPIRED}; return sub;}
 readOnly(sub:any){return [SubscriptionStatus.SUSPENDED,SubscriptionStatus.EXPIRED,SubscriptionStatus.CANCELLED].includes(sub.status);}
 async assertWritable(tenantId:string){const sub=await this.find(tenantId);if(sub.status===SubscriptionStatus.SUSPENDED)throw new ForbiddenException({code:'SUBSCRIPTION_SUSPENDED',message:'この園の利用は停止されています。'});if(this.readOnly(sub))throw new ForbiddenException({code:'SUBSCRIPTION_EXPIRED',message:'この園の契約は利用期限を過ぎています。'});}
 async assertStaffCapacity(tenantId:string){const sub=await this.find(tenantId);const count=await this.prisma.staff.count({where:{tenantId,isActive:true}});if(count>=sub.staffLimit)throw new ConflictException({code:'STAFF_LIMIT_REACHED',message:'職員登録上限に達しています。'});}
 async platformList(user:AuthenticatedUser,query:any){await this.platform(user);return this.prisma.tenant.findMany({where:{...(query.q?{name:{contains:query.q,mode:'insensitive'}}:{}),...(query.plan||query.status?{subscription:{is:{...(query.plan?{plan:query.plan}:{}),...(query.status?{status:query.status}:{})}}}:{})},include:{subscription:true,_count:{select:{staff:{where:{isActive:true}}}}},orderBy:{updatedAt:'desc'}});}
 async platformUpdate(user:AuthenticatedUser,tenantId:string,input:any){await this.platform(user);const before=await this.prisma.tenantSubscription.findUnique({where:{tenantId}});if(!before)throw new NotFoundException('SUBSCRIPTION_NOT_FOUND');const data:any={};if(input.plan){const plan=input.plan as SubscriptionPlan;data.plan=plan;data.staffLimit=input.staffLimit??plans[plan].staffLimit;}if(input.status){data.status=input.status;data.suspensionReason=input.suspensionReason??null;data.suspendedAt=input.status===SubscriptionStatus.SUSPENDED?new Date():null;}if(input.staffLimit)data.staffLimit=input.staffLimit;if(input.extendTrialDays){data.status=SubscriptionStatus.TRIAL;data.trialEndsAt=new Date(Date.now()+input.extendTrialDays*86400000);}const updated=await this.prisma.tenantSubscription.update({where:{tenantId},data});const action=input.extendTrialDays?'TRIAL_EXTENDED':input.status===SubscriptionStatus.SUSPENDED?'TENANT_SUSPENDED':input.status===SubscriptionStatus.ACTIVE&&before.status===SubscriptionStatus.SUSPENDED?'TENANT_REACTIVATED':input.plan?'PLAN_CHANGED':'SUBSCRIPTION_UPDATED';await this.audit.create(tenantId,user.sub,action,'TenantSubscription',updated.id,{before:{plan:before.plan,status:before.status,staffLimit:before.staffLimit},after:{plan:updated.plan,status:updated.status,staffLimit:updated.staffLimit}});return updated;}
 private async platform(user:AuthenticatedUser){const u=await this.prisma.user.findUnique({where:{id:user.sub},select:{isPlatformAdmin:true}});if(!u?.isPlatformAdmin)throw new ForbiddenException('プラットフォーム管理者専用です。');}
 private async trialNotifications(user:AuthenticatedUser,sub:any){if(sub.status!==SubscriptionStatus.TRIAL||!sub.trialEndsAt)return;const days=Math.ceil((sub.trialEndsAt.getTime()-Date.now())/86400000);if(![0,3,7].includes(days))return;const existing=await this.prisma.notification.findFirst({where:{tenantId:user.tenantId,type:NotificationType.SYSTEM,title:`試用終了${days}日前`}});if(!existing)await this.notifications.notifyRoles(user.tenantId,['ADMIN','DIRECTOR'],NotificationType.SYSTEM,`試用終了${days}日前`,'契約状況をご確認ください。');}
}
