module.exports = {
  schemaVersion: 1, packageType: 'TENANT_PERMANENT_MASTER', tenantCode: 'musubi-nursery',
  staffCodes: Array.from({ length: 23 }, (_, index) => `S${String(index + 1).padStart(3, '0')}`),
  staffProfiles: [
    {"staffCode": "S001", "assignedClass": "AGE_5", "employmentType": "FULL_TIME", "canWorkEarly": true, "canWorkRegular": true, "canWorkLate": true, "earlyShiftOnly": false, "lateShiftOnly": false, "canWorkSaturdays": true, "departmentCode": "CHILDCARE"},
    {"staffCode": "S002", "assignedClass": "AGE_5", "employmentType": "FULL_TIME", "canWorkEarly": true, "canWorkRegular": true, "canWorkLate": true, "earlyShiftOnly": false, "lateShiftOnly": false, "canWorkSaturdays": true, "departmentCode": "CHILDCARE"},
    {"staffCode": "S003", "assignedClass": "AGE_4", "employmentType": "FULL_TIME", "canWorkEarly": true, "canWorkRegular": true, "canWorkLate": true, "earlyShiftOnly": false, "lateShiftOnly": false, "canWorkSaturdays": true, "departmentCode": "CHILDCARE"},
    {"staffCode": "S004", "assignedClass": "AGE_3", "employmentType": "FULL_TIME", "canWorkEarly": true, "canWorkRegular": true, "canWorkLate": true, "earlyShiftOnly": false, "lateShiftOnly": false, "canWorkSaturdays": true, "departmentCode": "CHILDCARE"},
    {"staffCode": "S005", "assignedClass": "AGE_3", "employmentType": "FULL_TIME", "canWorkEarly": true, "canWorkRegular": true, "canWorkLate": true, "earlyShiftOnly": false, "lateShiftOnly": false, "canWorkSaturdays": true, "departmentCode": "CHILDCARE"},
    {"staffCode": "S006", "assignedClass": "AGE_2", "employmentType": "FULL_TIME", "canWorkEarly": true, "canWorkRegular": true, "canWorkLate": true, "earlyShiftOnly": false, "lateShiftOnly": false, "canWorkSaturdays": true, "departmentCode": "CHILDCARE"},
    {"staffCode": "S007", "assignedClass": "AGE_2", "employmentType": "FULL_TIME", "canWorkEarly": true, "canWorkRegular": true, "canWorkLate": true, "earlyShiftOnly": false, "lateShiftOnly": false, "canWorkSaturdays": true, "departmentCode": "CHILDCARE"},
    {"staffCode": "S008", "assignedClass": "AGE_2", "employmentType": "FULL_TIME", "canWorkEarly": true, "canWorkRegular": true, "canWorkLate": true, "earlyShiftOnly": false, "lateShiftOnly": false, "canWorkSaturdays": true, "departmentCode": "CHILDCARE"},
    {"staffCode": "S009", "assignedClass": "AGE_1", "employmentType": "FULL_TIME", "canWorkEarly": true, "canWorkRegular": true, "canWorkLate": true, "earlyShiftOnly": false, "lateShiftOnly": false, "canWorkSaturdays": true, "departmentCode": "CHILDCARE"},
    {"staffCode": "S010", "assignedClass": "AGE_1", "employmentType": "FULL_TIME", "canWorkEarly": true, "canWorkRegular": true, "canWorkLate": true, "earlyShiftOnly": false, "lateShiftOnly": false, "canWorkSaturdays": true, "departmentCode": "CHILDCARE"},
    {"staffCode": "S011", "assignedClass": "AGE_0", "employmentType": "FULL_TIME", "canWorkEarly": true, "canWorkRegular": true, "canWorkLate": true, "earlyShiftOnly": false, "lateShiftOnly": false, "canWorkSaturdays": true, "departmentCode": "CHILDCARE"},
    {"staffCode": "S012", "assignedClass": "AGE_0", "employmentType": "FULL_TIME", "canWorkEarly": true, "canWorkRegular": true, "canWorkLate": true, "earlyShiftOnly": false, "lateShiftOnly": false, "canWorkSaturdays": true, "departmentCode": "CHILDCARE"},
    {"staffCode": "S013", "assignedClass": "FREE", "employmentType": "FULL_TIME", "canWorkEarly": true, "canWorkRegular": true, "canWorkLate": true, "earlyShiftOnly": false, "lateShiftOnly": false, "canWorkSaturdays": true, "departmentCode": "CHILDCARE"},
    {"staffCode": "S014", "assignedClass": "AGE_1", "employmentType": "FULL_TIME", "canWorkEarly": false, "canWorkRegular": true, "canWorkLate": false, "earlyShiftOnly": false, "lateShiftOnly": false, "canWorkSaturdays": true, "departmentCode": "CHILDCARE"},
    {"staffCode": "S015", "assignedClass": "AGE_5", "employmentType": "PART_TIME", "canWorkEarly": false, "canWorkRegular": true, "canWorkLate": false, "earlyShiftOnly": false, "lateShiftOnly": false, "canWorkSaturdays": true, "departmentCode": "CHILDCARE"},
    {"staffCode": "S016", "assignedClass": "AGE_4", "employmentType": "PART_TIME", "canWorkEarly": false, "canWorkRegular": true, "canWorkLate": false, "earlyShiftOnly": false, "lateShiftOnly": false, "canWorkSaturdays": false, "departmentCode": "CHILDCARE"},
    {"staffCode": "S017", "assignedClass": "AGE_1", "employmentType": "PART_TIME", "canWorkEarly": false, "canWorkRegular": true, "canWorkLate": false, "earlyShiftOnly": false, "lateShiftOnly": false, "canWorkSaturdays": true, "departmentCode": "CHILDCARE"},
    {"staffCode": "S018", "assignedClass": "AGE_0", "employmentType": "PART_TIME", "canWorkEarly": false, "canWorkRegular": true, "canWorkLate": false, "earlyShiftOnly": false, "lateShiftOnly": false, "canWorkSaturdays": true, "departmentCode": "CHILDCARE"},
    {"staffCode": "S019", "assignedClass": "SUPPORT", "employmentType": "PART_TIME", "canWorkEarly": true, "canWorkRegular": false, "canWorkLate": false, "earlyShiftOnly": true, "lateShiftOnly": false, "canWorkSaturdays": true, "departmentCode": "CHILDCARE_SUPPORT"},
    {"staffCode": "S020", "assignedClass": "SUPPORT", "employmentType": "PART_TIME", "canWorkEarly": false, "canWorkRegular": true, "canWorkLate": false, "earlyShiftOnly": false, "lateShiftOnly": false, "canWorkSaturdays": true, "departmentCode": "CHILDCARE_SUPPORT"},
    {"staffCode": "S021", "assignedClass": "FREE", "employmentType": "PART_TIME", "canWorkEarly": false, "canWorkRegular": false, "canWorkLate": false, "earlyShiftOnly": false, "lateShiftOnly": false, "canWorkSaturdays": false, "departmentCode": "FOOD_SERVICE"},
    {"staffCode": "S022", "assignedClass": "FREE", "employmentType": "PART_TIME", "canWorkEarly": false, "canWorkRegular": false, "canWorkLate": false, "earlyShiftOnly": false, "lateShiftOnly": false, "canWorkSaturdays": false, "departmentCode": "FOOD_SERVICE"},
    {"staffCode": "S023", "assignedClass": "FREE", "employmentType": "PART_TIME", "canWorkEarly": false, "canWorkRegular": false, "canWorkLate": false, "earlyShiftOnly": false, "lateShiftOnly": false, "canWorkSaturdays": false, "departmentCode": "FOOD_SERVICE"}
  ],
  departments: [['CHILDCARE', '保育'], ['CHILDCARE_SUPPORT', '支援'], ['FOOD_SERVICE', '給食']],
  patterns: [
    ['EARLY', '①', '07:30', '16:00', true, true], ['NORMAL', '普通出', '08:30', '17:00', true, true], ['SAT_NORMAL', '普通出（土曜）', '08:30', '16:00', true, true], ['LATE', '⑥', '11:00', '19:30', true, true], ['OFF', '休', null, null, false, false],
    ['P02', '②', '08:00', '16:30', true, true], ['P03', '③', '09:00', '17:30', true, true], ['P04', '④', '09:30', '18:00', true, true], ['P05', '⑤', '10:00', '18:30', true, true], ['P07', '⑦', '07:30', '15:00', true, true], ['P08', '⑧', '09:30', '17:00', true, true], ['P09', '⑨', '10:30', '18:00', true, true], ['NO_ROTATION', 'シフト無し', '08:30', '17:00', true, false],
    ['FIXED_S014', '固定', '09:00', '16:30', true, true], ['FIXED_S015', '固定', '09:30', '15:30', true, true], ['FIXED_S017', '固定', '09:30', '15:30', true, true], ['FIXED_S018', '固定', '09:30', '15:30', true, true], ['FIXED_S020_1715', '固定', '08:45', '17:15', true, true],
  ],
  attributes: [['GENERATOR_EXCLUDED', '自動生成対象外', 'ROLE'], ['FIXED_ASSIGNMENT', '固定勤務materialization対象', 'ASSIGNMENT'], ['WEEKLY_PATTERN_GROUP_LIMIT_EXEMPT', '週勤務グループ上限の園固有例外', 'QUALIFICATION'], ['MUSUBI_ROTATION', '保育ローテーション対象', 'ROLE'], ['MUSUBI_SATURDAY_ROTATION', '土曜ローテーション対象', 'ROLE'], ['MUSUBI_VETERAN_05', '⑤ベテラン候補', 'QUALIFICATION'], ['MUSUBI_TRIGGER_LATE_PAIR', '条件付き⑥対象', 'ROLE']],
  attributeAssignments: { GENERATOR_EXCLUDED: ['S021', 'S022', 'S023'], FIXED_ASSIGNMENT: ['S021', 'S022', 'S023'], WEEKLY_PATTERN_GROUP_LIMIT_EXEMPT: ['S008', 'S016', 'S019'], MUSUBI_ROTATION: Array.from({ length: 20 }, (_, index) => `S${String(index + 1).padStart(3, '0')}`), MUSUBI_SATURDAY_ROTATION: Array.from({ length: 20 }, (_, index) => `S${String(index + 1).padStart(3, '0')}`), MUSUBI_VETERAN_05: ['S002', 'S003', 'S004'], MUSUBI_TRIGGER_LATE_PAIR: ['S005', 'S010'] },
  settings: { saturdayOperationEnabled: true, sundayOperationEnabled: false, weekdayEarlyRequired: 2, weekdayLateRequired: 2, saturdayMinimumStaff: 5, saturdayEarlyRequired: 0, saturdayLateRequired: 0, defaultStartEarly: '07:30', defaultEndEarly: '16:00', defaultStartNormal: '08:30', defaultEndNormal: '17:00', defaultStartLate: '11:00', defaultEndLate: '19:30', defaultBreakMinutes: 60, maxConsecutiveWorkDays: 6, maxConsecutiveEarlyDays: 1, maxConsecutiveLateDays: 1 },
  classRequirements: [['AGE_0', 2], ['AGE_1', 2], ['AGE_2', 2], ['AGE_3', 2], ['AGE_4', 1], ['AGE_5', 1]],
  features: ['BASIC_SHIFT_GENERATION', 'TENANT_CUSTOM_RULES', 'STAFF_WORK_RULES', 'ADVANCED_WORK_PATTERNS', 'ADVANCED_STAFFING_REQUIREMENTS'],
  customRules: { weeklyPatternGroupLimit: { groupCode: 'MUSUBI_01_06', patternCodes: ['EARLY', 'P02', 'P03', 'P04', 'P05', 'LATE'], maxPerWeek: 1, exemptAttributeCode: 'WEEKLY_PATTERN_GROUP_LIMIT_EXEMPT', relaxation: { enabled: true, maxPerWeek: 2, explanationLevel: 'INFO', activationMode: 'FORMAL', historyYears: 3, recentWindowDays: 90 } }, fixedWorkPatternOverridesWeeklyLimit: true, nextDayBlockedPatternTransitions: [{ fromPatternCodes: ['P05'], toPatternCodes: ['EARLY'] }], replaceLegacyShiftTargetsWhenPatternRequirementsActive: true, fillOpenUnassignedWithNormal: true, meetingDayRules: [{ dayOfWeek: 5, occurrence: 3, minimumEndTime: '18:30' }] },
  permanentRules: [{ staffCode: 'S013', ruleType: 'UNAVAILABLE_WORK_PATTERN', patternCode: 'LATE', dayOfWeek: 4, reason: '園正式回答・毎週木曜日は⑥不可' }, { staffCode: 'S016', ruleType: 'REQUIRED_DAY_OFF', dayOfWeek: 6, reason: '園正式回答・毎週土曜日は休み' }, ...[1, 2, 3, 4, 5].map((dayOfWeek) => ({ staffCode: 'S016', ruleType: 'FIXED_WORK_PATTERN', patternCode: 'P02', dayOfWeek, startTime: '08:00', endTime: '16:40', reason: '平日は②固定・個人時刻16:40（共通②16:30と分離）' })), ...[1, 2, 3, 4, 5].map((dayOfWeek) => ({ staffCode: 'S019', ruleType: 'FIXED_WORK_PATTERN', patternCode: 'EARLY', dayOfWeek, reason: '平日は①固定' })), ...Object.entries({ S014: 'FIXED_S014', S015: 'FIXED_S015', S017: 'FIXED_S017', S018: 'FIXED_S018', S020: 'FIXED_S020_1715' }).flatMap(([staffCode, patternCode]) => (staffCode === 'S020' ? [1, 2, 3, 4, 5] : [1, 2, 3, 4, 5, 6]).map((dayOfWeek) => ({ staffCode, ruleType: 'FIXED_WORK_PATTERN', patternCode, dayOfWeek, reason: '契約固定時間を維持' })))],
  fixedMaterialization: { staff: { S014: ['09:00', '16:30', 390], S015: ['09:30', '15:30', 300], S017: ['09:30', '15:30', 300], S018: ['09:30', '15:30', 300], S020: ['08:45', '17:15', 450], S021: ['07:30', '16:00', 450], S022: ['08:30', '17:00', 450], S023: ['08:00', '16:30', 450] } },
  staffingRequirements: { weekday: [['EARLY', 2], ['P02', 1], ['P03', 1], ['P04', 1], ['P05', 1], ['LATE', 2]], saturday: [['P07', 2], ['P08', 1], ['P09', 2]] },
  conditionalRequirement: { code: 'MUSUBI_VETERAN_05_WHEN_NAMED_06', triggerAttribute: 'MUSUBI_TRIGGER_LATE_PAIR', triggerPattern: 'LATE', triggerCount: 1, targetAttribute: 'MUSUBI_VETERAN_05', targetPattern: 'P05', requiredCount: 1 },
};

// Source Matrix MUSUBI-2026-039. No personal names or inferred annual targets.
const master = module.exports;
master.sourceRegistry = { matrixSourceId: 'MUSUBI-2026-039', matrixSha256: '6db2e20d95802e185f2d21801dc513a1fd3b9f752c3544a393391229643869cb', sourceIds: ['MUSUBI-2026-031','MUSUBI-2026-032','MUSUBI-2026-035','MUSUBI-2026-036','MUSUBI-2026-037','MUSUBI-2026-038'] };
master.permanentRules.push(
  ...['S019', 'S020'].map(staffCode => ({ staffCode, ruleType: 'FIXED_WORK_PATTERN', patternCode: 'P07', dayOfWeek: 6, reason: 'Source Matrix 039: 土曜出勤時⑦、休暇優先' })),
  { staffCode: 'S003', ruleType: 'FIXED_WORK_PATTERN', patternCode: 'NO_ROTATION', dayOfWeek: 3, reason: 'MUSUBI-2026-031: 水曜シフト無し・出勤/配置不算入' },
  { staffCode: 'S012', ruleType: 'MAX_WORK_PATTERN_PER_MONTH', patternCode: 'EARLY', numericValue: 1, reason: 'MUSUBI-2026-031: ①月1回上限' },
  ...['EARLY','NORMAL'].map(patternCode => ({ staffCode: 'S013', ruleType: 'AVAILABLE_WORK_PATTERN', patternCode, dayOfWeek: 2, reason: 'MUSUBI-2026-031: 火曜①または普通' }))
);
master.individualTimes = { ...master.fixedMaterialization.staff, S016: ['08:00','16:40'], S019: ['07:30','16:00'] };
master.customRules.release1SourceProvenance = { matrixSourceId: 'MUSUBI-2026-039', provisionalValues: { P09: { value: ['10:30','18:00'], approvalStatus: 'PROVISIONAL_PENDING_ADMIN_CONFIRMATION', sourceId: 'MUSUBI-2026-036', decisionActorType: 'USER_PRODUCT_OWNER_DECISION', applicablePeriod: { from: null, to: null } } }, operationalDefaults: { sourceId: 'MUSUBI-2026-037', approvalStatus: 'RELEASE1_OPERATIONAL_DEFAULT', decisionActorType: 'USER_PRODUCT_OWNER_DECISION', explicitRulesTakePrecedence: true, foodRotation: false } };
master.customRules.release1ProvisionalSoftRules = [
  ...['S006','S007'].map(staffCode => ({ staffCode, kind: 'NEXT_DAY_PATTERN', fromPatternCode: 'LATE', targetPatternCode: 'P03', status: 'RELEASE1_PROVISIONAL_SOFT_RULE', sourceId: 'MUSUBI-2026-038', decisionActorType: 'USER_PRODUCT_OWNER_DECISION' })),
  { staffCode: 'S006', kind: 'MONTHLY_PATTERN_PREFERENCE', targetPatternCode: 'EARLY', avoidDayOfWeek: 3, targetMonthlyCount: 1, status: 'RELEASE1_PROVISIONAL_SOFT_RULE', sourceId: 'MUSUBI-2026-038', decisionActorType: 'USER_PRODUCT_OWNER_DECISION' }
];
