import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import { api, type ClassRequirement, type ClosedDate, type Session, type ShiftSetting } from '../../api/client';
import { LoadingState } from '../../components/UiStates';

const labels: Record<string, string> = { AGE_0: '0歳児', AGE_1: '1歳児', AGE_2: '2歳児', AGE_3: '3歳児', AGE_4: '4歳児', AGE_5: '5歳児' };
const monthNow = new Date().toISOString().slice(0, 7);
export function ShiftSettings({ session }: { session: Session }) {
  const [setting, setSetting] = useState<ShiftSetting | null>(null); const [requirements, setRequirements] = useState<ClassRequirement[]>([]); const [month, setMonth] = useState(monthNow); const [closedDates, setClosedDates] = useState<ClosedDate[]>([]); const [message, setMessage] = useState(''); const [closed, setClosed] = useState({ closedDate: `${monthNow}-01`, name: '', note: '' });
  const load = async () => { try { const [nextSetting, nextRequirements, nextClosed] = await Promise.all([api.shiftSettings(session.accessToken), api.classRequirements(session.accessToken), api.closedDates(session.accessToken, month)]); setSetting(nextSetting); setRequirements(nextRequirements); setClosedDates(nextClosed); } catch (error) { setMessage(error instanceof Error ? error.message : '園設定を取得できませんでした。'); } };
  useEffect(() => { void load(); }, [month]);
  const updateNumber = (key: keyof ShiftSetting, value: string) => setSetting((current) => current ? { ...current, [key]: Number(value) } : current);
  const saveSetting = async () => { if (!setting) return; try { setSetting(await api.updateShiftSettings(session.accessToken, setting)); setMessage('園設定を保存しました。'); } catch (error) { setMessage(error instanceof Error ? error.message : '園設定を保存できませんでした。入力内容を確認して、もう一度お試しください。'); } };
  const saveRequirements = async () => { try { setRequirements(await api.updateClassRequirements(session.accessToken, requirements)); setMessage('クラス別必要人数を保存しました。'); } catch (error) { setMessage(error instanceof Error ? error.message : '必要人数を保存できませんでした。入力内容を確認して、もう一度お試しください。'); } };
  const addClosed = async () => { try { await api.createClosedDate(session.accessToken, closed); setClosed({ closedDate: `${month}-01`, name: '', note: '' }); setMessage('休園日を登録しました。'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : '休園日を登録できませんでした。入力内容をご確認ください。'); } };
  const removeClosed = async (id: string) => { if (!window.confirm('この休園日を削除しますか？ 削除後は元に戻せません。')) return; try { await api.deleteClosedDate(session.accessToken, id); setMessage('休園日を削除しました。'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : '休園日を削除できませんでした。時間をおいてもう一度お試しください。'); } };
  if (!setting) return <section className="mt-6"><LoadingState label="園設定を読み込んでいます…" /></section>;
  return <section className="mt-6 space-y-5">{message && <p role="status" className="rounded-lg bg-slate-100 p-3 text-sm">{message}</p>}<Card title="必要人数"><div className="grid gap-3 sm:grid-cols-2">{([['weekdayEarlyRequired','平日早出'],['weekdayLateRequired','平日遅出'],['saturdayMinimumStaff','土曜最低勤務人数'],['saturdayEarlyRequired','土曜早出'],['saturdayLateRequired','土曜遅出']] as Array<[keyof ShiftSetting,string]>).map(([key,label]) => <NumberInput key={key} label={label} value={setting[key] as number} onChange={(value) => updateNumber(key,value)} />)}<p className="rounded border bg-slate-50 p-3 text-sm text-slate-600">土曜は早出・遅出を優先し、最低勤務人数まで通常勤務を配置します。</p><label className="flex items-center gap-2 rounded border p-3"><input aria-label="土曜保育" type="checkbox" checked={setting.saturdayOperationEnabled} onChange={(e) => setSetting({ ...setting, saturdayOperationEnabled: e.target.checked })} />土曜保育を行う</label><label className="flex items-center gap-2 rounded border p-3"><input aria-label="日曜開園" type="checkbox" checked={setting.sundayOperationEnabled} onChange={(e) => setSetting({ ...setting, sundayOperationEnabled: e.target.checked })} />日曜も開園する（土曜人数設定を使用）</label></div><Save onClick={saveSetting} /></Card>
    <Card title="園長の勤務・クラス配置"><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm">園長を必要保育人数に含める<select aria-label="園長を必要保育人数に含める" value={setting.directorCountsTowardStaffing ? 'include' : 'exclude'} onChange={(e) => setSetting({ ...setting, directorCountsTowardStaffing: e.target.value === 'include' })} className="rounded border p-2"><option value="exclude">含めない（初期値）</option><option value="include">含める</option></select></label><label className="grid gap-1 text-sm">園長のクラス配置<select aria-label="園長のクラス配置" value={setting.directorClassPlacementMode} onChange={(e) => setSetting({ ...setting, directorClassPlacementMode: e.target.value as ShiftSetting['directorClassPlacementMode'] })} className="rounded border p-2"><option value="NONE">原則なし（初期値）</option><option value="SHORTAGE_ONLY">不足時のみ</option><option value="NORMAL">通常配置可能</option></select></label></div><p className="mt-3 rounded border bg-slate-50 p-3 text-sm text-slate-600">「原則なし」では担当を運営と表示します。不足時の配置は応援先クラス名を表示します。</p><Save onClick={saveSetting} /></Card>
    <Card title="連続勤務ルール"><div className="grid gap-3 sm:grid-cols-3">{([['maxConsecutiveWorkDays','最大連続勤務日数'],['maxConsecutiveEarlyDays','最大連続早出日数'],['maxConsecutiveLateDays','最大連続遅出日数']] as Array<[keyof ShiftSetting,string]>).map(([key,label]) => <NumberInput key={key} label={label} value={setting[key] as number} onChange={(value) => updateNumber(key,value)} />)}</div><Save onClick={saveSetting} /></Card>
    <Card title="標準勤務時間・休憩"><div className="grid gap-3 sm:grid-cols-3">{([['defaultStartEarly','早出開始'],['defaultEndEarly','早出終了'],['defaultStartNormal','通常開始'],['defaultEndNormal','通常終了'],['defaultStartLate','遅出開始'],['defaultEndLate','遅出終了']] as Array<[keyof ShiftSetting,string]>).map(([key,label]) => <label key={key} className="grid gap-1 text-sm">{label}<input type="time" value={setting[key] as string} onChange={(e) => setSetting({ ...setting, [key]: e.target.value })} className="rounded border p-2" /></label>)}<NumberInput label="標準休憩（分）" value={setting.defaultBreakMinutes} onChange={(value) => updateNumber('defaultBreakMinutes',value)} /></div><Save onClick={saveSetting} /></Card>
    <Card title="クラス別必要人数"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr><th>クラス</th><th>平日</th><th>土曜</th><th>有効</th></tr></thead><tbody>{requirements.map((row,index) => <tr key={row.classType}><td>{labels[row.classType] ?? row.classType}</td><td><input aria-label={`${labels[row.classType]} 平日`} type="number" min="0" value={row.weekdayRequired} onChange={(e) => setRequirements((all) => all.map((item,i) => i === index ? { ...item, weekdayRequired: Number(e.target.value) } : item))} className="m-1 w-20 rounded border p-2" /></td><td><input aria-label={`${labels[row.classType]} 土曜`} type="number" min="0" value={row.saturdayRequired} onChange={(e) => setRequirements((all) => all.map((item,i) => i === index ? { ...item, saturdayRequired: Number(e.target.value) } : item))} className="m-1 w-20 rounded border p-2" /></td><td><input aria-label={`${labels[row.classType]} 有効`} type="checkbox" checked={row.isActive} onChange={(e) => setRequirements((all) => all.map((item,i) => i === index ? { ...item, isActive: e.target.checked } : item))} /></td></tr>)}</tbody></table></div><Save onClick={saveRequirements} /></Card>
    <Card title="休園日"><div className="flex flex-wrap gap-2"><input aria-label="休園日対象月" type="month" value={month} onChange={(e) => setMonth(e.target.value)} className="rounded border p-2" /><input aria-label="休園日の日付" type="date" value={closed.closedDate} onChange={(e) => setClosed({ ...closed, closedDate: e.target.value })} className="rounded border p-2" /><input aria-label="休園日名称" placeholder="名称" value={closed.name} onChange={(e) => setClosed({ ...closed, name: e.target.value })} className="rounded border p-2" /><input aria-label="休園日備考" placeholder="備考" value={closed.note} onChange={(e) => setClosed({ ...closed, note: e.target.value })} className="rounded border p-2" /><button onClick={addClosed} disabled={!closed.name} className="rounded bg-emerald-700 px-4 py-2 font-semibold text-white disabled:opacity-40">登録</button></div><ul className="mt-4 space-y-2">{closedDates.map((row) => <li key={row.id} className="flex flex-wrap items-center justify-between gap-2 rounded border p-3"><span>{row.closedDate.slice(0,10)}：{row.name}{row.note ? `（${row.note}）` : ''}</span><button onClick={() => removeClosed(row.id)} className="rounded border border-red-300 px-3 py-1 text-red-700">削除</button></li>)}</ul></Card></section>;
}
function Card({ title, children }: { title: string; children: ReactNode }) { return <article className="card"><h3 className="font-bold">{title}</h3><div className="mt-4">{children}</div></article>; }
function NumberInput({ label, value, onChange }: { label: string; value: number; onChange: (value: string) => void }) { return <label className="grid gap-1 text-sm">{label}<input aria-label={label} type="number" min="0" value={value} onChange={(e) => onChange(e.target.value)} className="rounded border p-2" /></label>; }
function Save({ onClick }: { onClick: () => void }) { return <button onClick={onClick} className="btn-primary mt-4">保存</button>; }
