import { useEffect, useState } from 'react';
import { api, type AssignedClass, type Session, type ShiftStaffingRequirement, type ShiftStaffingRequirementInput, type StaffAttributeDefinition, type StaffingConstraintLevel } from '../../api/client';
import { useFeature } from '../features/use-feature';

const classLabels:Record<AssignedClass,string>={AGE_0:'0歳児',AGE_1:'1歳児',AGE_2:'2歳児',AGE_3:'3歳児',AGE_4:'4歳児',AGE_5:'5歳児',FREE:'フリー',SUPPORT:'支援'};
const categoryLabels={ROLE:'役職',QUALIFICATION:'資格',ASSIGNMENT:'担当区分',SKILL:'能力・経験'} as const;
const dayLabels=['日','月','火','水','木','金','土'];
const empty:ShiftStaffingRequirementInput={code:'',name:'',attributeDefinitionId:'',classType:null,dayOfWeek:null,startDate:null,endDate:null,requiredCount:1,constraintLevel:'HARD',reason:null,displayOrder:0,isActive:true};

export function StaffingRequirementManagement({session}:{session:Session}){
  const feature=useFeature(session.accessToken,'ADVANCED_STAFFING_REQUIREMENTS');
  const [rows,setRows]=useState<ShiftStaffingRequirement[]>([]);const [definitions,setDefinitions]=useState<StaffAttributeDefinition[]>([]);const [input,setInput]=useState<ShiftStaffingRequirementInput|null>(null);const [editing,setEditing]=useState<string|null>(null);const [message,setMessage]=useState('');
  const canEdit=session.role==='ADMIN'&&feature.loaded&&feature.enabled;
  async function load(){try{const [requirements,attrs]=await Promise.all([api.staffingRequirements(session.accessToken),api.staffAttributes(session.accessToken)]);setRows(requirements);setDefinitions(attrs);}catch(error){setMessage(error instanceof Error?error.message:'属性別配置条件を取得できませんでした。');}}
  useEffect(()=>{void load();},[session.accessToken]);
  function start(row?:ShiftStaffingRequirement){setEditing(row?.id??null);setInput(row?{code:row.code,name:row.name,attributeDefinitionId:row.attributeDefinitionId,classType:row.classType,dayOfWeek:row.dayOfWeek,startDate:row.startDate?.slice(0,10)??null,endDate:row.endDate?.slice(0,10)??null,requiredCount:row.requiredCount,constraintLevel:row.constraintLevel,reason:row.reason,displayOrder:row.displayOrder,isActive:row.isActive}:empty);}
  async function save(){if(!input)return;try{editing?await api.updateStaffingRequirement(session.accessToken,editing,input):await api.createStaffingRequirement(session.accessToken,input);setInput(null);setMessage('配置条件を保存しました。');await load();}catch(error){setMessage(error instanceof Error?error.message:'配置条件を保存できませんでした。');}}
  async function deactivate(id:string){try{await api.deactivateStaffingRequirement(session.accessToken,id);setMessage('配置条件を無効化しました。');await load();}catch(error){setMessage(error instanceof Error?error.message:'配置条件を無効化できませんでした。');}}
  async function reactivate(row:ShiftStaffingRequirement){try{await api.updateStaffingRequirement(session.accessToken,row.id,{code:row.code,name:row.name,attributeDefinitionId:row.attributeDefinitionId,classType:row.classType,dayOfWeek:row.dayOfWeek,startDate:row.startDate?.slice(0,10)??null,endDate:row.endDate?.slice(0,10)??null,requiredCount:row.requiredCount,constraintLevel:row.constraintLevel,reason:row.reason,displayOrder:row.displayOrder,isActive:true});setMessage('配置条件を再有効化しました。');await load();}catch(error){setMessage(error instanceof Error?error.message:'配置条件を再有効化できませんでした。');}}
  return <article className="card"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold">属性別配置条件</h3><p className="mt-2 rounded-lg bg-amber-50 p-3 text-sm font-medium text-amber-900">この配置条件は現在、自動シフト生成には反映されません。</p></div>{canEdit&&<button className="btn-primary" onClick={()=>start()}>新規登録</button>}</div>
    {!feature.loaded?<p className="mt-4 text-sm">利用可否を確認しています…</p>:!feature.enabled&&<p className="mt-4 rounded border bg-slate-50 p-3 text-sm">現在のプランでは読み取り専用です。</p>}{message&&<p role="status" className="mt-4 rounded bg-slate-100 p-3 text-sm">{message}</p>}
    <div className="mt-4 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr><th>コード・名称</th><th>対象</th><th>属性</th><th>曜日・期間</th><th>人数</th><th>レベル</th><th>状態</th><th>操作</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><span className="font-mono text-xs">{row.code}</span><br/>{row.name}</td><td>{row.classType?classLabels[row.classType]:'園全体'}</td><td>{categoryLabels[row.attributeDefinition.category]}：{row.attributeDefinition.name}{!row.attributeDefinition.isActive?'（無効）':''}</td><td>{row.dayOfWeek==null?'全日':`${dayLabels[row.dayOfWeek]}曜`}<br/>{row.startDate&&row.endDate?`${row.startDate.slice(0,10)}〜${row.endDate.slice(0,10)}`:'無期限'}</td><td>{row.requiredCount}人</td><td>{row.constraintLevel}</td><td>{row.isActive?'有効':'無効'}</td><td>{canEdit&&<><button className="rounded border px-2 py-1" onClick={()=>start(row)}>編集</button>{row.isActive?<button className="ml-2 rounded border border-rose-200 px-2 py-1 text-rose-700" onClick={()=>void deactivate(row.id)}>無効化</button>:<button className="ml-2 rounded border border-emerald-200 px-2 py-1 text-emerald-700" onClick={()=>void reactivate(row)}>再有効化</button>}</>}</td></tr>)}</tbody></table>{rows.length===0&&<p className="p-4 text-center text-slate-500">登録済みの属性別配置条件はありません。</p>}</div>
    {input&&canEdit&&<section className="mt-5 rounded-xl border bg-slate-50 p-4"><h4 className="font-bold">{editing?'配置条件を編集':'配置条件を登録'}</h4><div className="mt-3 grid gap-3 sm:grid-cols-2"><label>コード<input disabled={editing!=null} className="mt-1 w-full rounded border p-2" value={input.code} onChange={e=>setInput({...input,code:e.target.value.toUpperCase()})}/></label><label>名称<input maxLength={100} className="mt-1 w-full rounded border p-2" value={input.name} onChange={e=>setInput({...input,name:e.target.value})}/></label><label>対象<select className="mt-1 w-full rounded border p-2" value={input.classType??''} onChange={e=>setInput({...input,classType:(e.target.value||null) as AssignedClass|null})}><option value="">園全体</option>{Object.entries(classLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>属性<select className="mt-1 w-full rounded border p-2" value={input.attributeDefinitionId} onChange={e=>setInput({...input,attributeDefinitionId:e.target.value})}><option value="">選択してください</option>{definitions.map(d=><option key={d.id} value={d.id}>{categoryLabels[d.category]}：{d.name}{d.isActive?'':'（無効）'}</option>)}</select></label><label>曜日<select className="mt-1 w-full rounded border p-2" value={input.dayOfWeek??''} onChange={e=>setInput({...input,dayOfWeek:e.target.value===''?null:Number(e.target.value)})}><option value="">全日</option>{dayLabels.map((label,index)=><option key={index} value={index}>{label}曜日</option>)}</select></label><label>必要人数<input type="number" min="1" className="mt-1 w-full rounded border p-2" value={input.requiredCount} onChange={e=>setInput({...input,requiredCount:Number(e.target.value)})}/></label><label>開始日<input type="date" className="mt-1 w-full rounded border p-2" value={input.startDate??''} onChange={e=>setInput({...input,startDate:e.target.value||null})}/></label><label>終了日<input type="date" className="mt-1 w-full rounded border p-2" value={input.endDate??''} onChange={e=>setInput({...input,endDate:e.target.value||null})}/></label><label>制約レベル<select className="mt-1 w-full rounded border p-2" value={input.constraintLevel} onChange={e=>setInput({...input,constraintLevel:e.target.value as StaffingConstraintLevel})}>{['HARD','SOFT','INFO'].map(v=><option key={v}>{v}</option>)}</select></label><label>表示順<input type="number" min="0" className="mt-1 w-full rounded border p-2" value={input.displayOrder} onChange={e=>setInput({...input,displayOrder:Number(e.target.value)})}/></label><label className="sm:col-span-2">理由<textarea maxLength={500} className="mt-1 w-full rounded border p-2" value={input.reason??''} onChange={e=>setInput({...input,reason:e.target.value||null})}/></label></div><div className="mt-4 flex justify-end gap-2"><button className="rounded border px-4 py-2" onClick={()=>setInput(null)}>キャンセル</button><button className="btn-primary" onClick={()=>void save()}>保存</button></div></section>}
  </article>;
}
