import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma, type StaffAttributeAssignment, type StaffAttributeDefinition } from '@prisma/client';
import type { AuthenticatedUser } from '../../infrastructure/auth/auth.types';
import { PrismaService } from '../../infrastructure/database/prisma.service';
import { AuditService } from '../audit/audit.service';
import type { StaffAttributeAssignmentInputDto, StaffAttributeDefinitionCreateDto, StaffAttributeDefinitionUpdateDto } from './staff-attribute.dto';

const CONTROL=/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/;
@Injectable()
export class StaffAttributesService {
  constructor(private readonly prisma:PrismaService,private readonly audit:AuditService){}
  listDefinitions(user:AuthenticatedUser){return this.prisma.staffAttributeDefinition.findMany({where:{tenantId:user.tenantId},orderBy:[{isActive:'desc'},{displayOrder:'asc'},{code:'asc'}]});}
  async createDefinition(user:AuthenticatedUser,input:StaffAttributeDefinitionCreateDto){this.validateDefinition(input);const inactive=await this.prisma.staffAttributeDefinition.findFirst({where:{tenantId:user.tenantId,code:input.code,isActive:false}});if(inactive){const before=inactive;const row=await this.prisma.staffAttributeDefinition.update({where:{id:inactive.id},data:{...this.cleanDefinition(input),isActive:true}});await this.logDefinition(user,'STAFF_ATTRIBUTE_DEFINITION_REACTIVATED',before,row);return row;}try{const row=await this.prisma.staffAttributeDefinition.create({data:{tenantId:user.tenantId,...this.cleanDefinition(input),isSystem:false}});await this.logDefinition(user,'STAFF_ATTRIBUTE_DEFINITION_CREATED',null,row);return row;}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')throw new ConflictException('同じコードの属性定義があります。');throw error;}}
  async updateDefinition(user:AuthenticatedUser,id:string,input:StaffAttributeDefinitionUpdateDto){this.validateDefinition(input);const before=await this.definition(user.tenantId,id);if(input.code!==before.code)throw new BadRequestException('属性コードは作成後に変更できません。');if(before.isSystem&&(input.category!==before.category||!input.isActive))throw new BadRequestException('システム属性のカテゴリ変更・無効化はできません。');if(input.category!==before.category&&await this.prisma.staffAttributeAssignment.count({where:{tenantId:user.tenantId,attributeDefinitionId:id}}))throw new BadRequestException('使用履歴がある属性のカテゴリは変更できません。');const row=await this.prisma.staffAttributeDefinition.update({where:{id},data:this.cleanDefinition(input)});const action=row.isActive&&!before.isActive?'STAFF_ATTRIBUTE_DEFINITION_REACTIVATED':!row.isActive&&before.isActive?'STAFF_ATTRIBUTE_DEFINITION_DEACTIVATED':'STAFF_ATTRIBUTE_DEFINITION_UPDATED';await this.logDefinition(user,action,before,row);return row;}
  async deactivateDefinition(user:AuthenticatedUser,id:string){const before=await this.definition(user.tenantId,id);if(before.isSystem)throw new BadRequestException('システム属性は無効化できません。');const row=await this.prisma.staffAttributeDefinition.update({where:{id},data:{isActive:false}});await this.logDefinition(user,'STAFF_ATTRIBUTE_DEFINITION_DEACTIVATED',before,row);return row;}
  async listAssignments(user:AuthenticatedUser,staffId:string){await this.staff(user.tenantId,staffId,false);return this.prisma.staffAttributeAssignment.findMany({where:{tenantId:user.tenantId,staffId},include:{attributeDefinition:true},orderBy:[{isActive:'desc'},{createdAt:'asc'}]});}
  async createAssignment(user:AuthenticatedUser,staffId:string,input:StaffAttributeAssignmentInputDto){await this.staff(user.tenantId,staffId,true);const data=await this.assignmentData(user.tenantId,staffId,input);const inactive=await this.findExact(data,false);await this.checkAssignment(data,inactive?.id);const{category:_,...write}=data;const row=inactive?await this.prisma.staffAttributeAssignment.update({where:{id:inactive.id},data:{...write,isActive:true}}):await this.prisma.staffAttributeAssignment.create({data:write});await this.logAssignment(user,inactive?'STAFF_ATTRIBUTE_ASSIGNMENT_REACTIVATED':'STAFF_ATTRIBUTE_ASSIGNMENT_CREATED',inactive,row);return row;}
  async updateAssignment(user:AuthenticatedUser,staffId:string,id:string,input:StaffAttributeAssignmentInputDto){await this.staff(user.tenantId,staffId,true);const before=await this.assignment(user.tenantId,staffId,id);const data=await this.assignmentData(user.tenantId,staffId,input,before.attributeDefinitionId);await this.checkAssignment(data,id);const{category:_,...write}=data;const row=await this.prisma.staffAttributeAssignment.update({where:{id},data:write});const action=row.isActive&&!before.isActive?'STAFF_ATTRIBUTE_ASSIGNMENT_REACTIVATED':!row.isActive&&before.isActive?'STAFF_ATTRIBUTE_ASSIGNMENT_DEACTIVATED':'STAFF_ATTRIBUTE_ASSIGNMENT_UPDATED';await this.logAssignment(user,action,before,row);return row;}
  async deactivateAssignment(user:AuthenticatedUser,staffId:string,id:string){const before=await this.assignment(user.tenantId,staffId,id);const row=await this.prisma.staffAttributeAssignment.update({where:{id},data:{isActive:false,isPrimary:false}});await this.logAssignment(user,'STAFF_ATTRIBUTE_ASSIGNMENT_DEACTIVATED',before,row);return row;}
  private validateDefinition(input:StaffAttributeDefinitionCreateDto){if(!input.name.trim())throw new BadRequestException('名称を入力してください。');if((input.description&&CONTROL.test(input.description))||(input.shortName&&CONTROL.test(input.shortName)))throw new BadRequestException('制御文字は使用できません。');}
  private cleanDefinition(input:StaffAttributeDefinitionCreateDto){return{code:input.code,name:input.name.trim(),shortName:input.shortName?.trim()||null,category:input.category,description:input.description?.trim()||null,displayOrder:input.displayOrder,color:input.color??null,isActive:input.isActive};}
  private async assignmentData(tenantId:string,staffId:string,input:StaffAttributeAssignmentInputDto,currentDefinitionId?:string){if((input.startDate==null)!==(input.endDate==null))throw new BadRequestException('適用開始日と終了日は両方設定してください。');if(input.startDate&&input.endDate&&input.startDate>input.endDate)throw new BadRequestException('適用開始日は終了日以前にしてください。');if(input.notes&&CONTROL.test(input.notes))throw new BadRequestException('備考に制御文字は使用できません。');const definition=await this.definition(tenantId,input.attributeDefinitionId);if(!definition.isActive&&(definition.id!==currentDefinitionId||input.isActive))throw new BadRequestException('無効な属性定義は新規割当・再有効化に指定できません。');if(input.isPrimary&&!['ROLE','ASSIGNMENT'].includes(definition.category))throw new BadRequestException('主属性は役職または担当区分だけに設定できます。');return{tenantId,staffId,attributeDefinitionId:definition.id,startDate:input.startDate?new Date(`${input.startDate}T00:00:00.000Z`):null,endDate:input.endDate?new Date(`${input.endDate}T00:00:00.000Z`):null,notes:input.notes?.trim()||null,isPrimary:input.isPrimary,isActive:input.isActive,category:definition.category};}
  private async checkAssignment(data:any,excludeId?:string){if(!data.isActive)return;const rows=await this.prisma.staffAttributeAssignment.findMany({where:{tenantId:data.tenantId,staffId:data.staffId,isActive:true,...(excludeId?{id:{not:excludeId}}:{})},include:{attributeDefinition:true}});if(rows.some(row=>row.attributeDefinitionId===data.attributeDefinitionId&&this.overlap(row.startDate,row.endDate,data.startDate,data.endDate)))throw new ConflictException('同じ属性の適用期間が重複しています。');if(data.isPrimary&&rows.some(row=>row.isPrimary&&row.attributeDefinition.category===data.category&&this.overlap(row.startDate,row.endDate,data.startDate,data.endDate)))throw new ConflictException('同一カテゴリの主属性期間が重複しています。既存主属性の期間を調整してください。');}
  private findExact(data:any,isActive:boolean){return this.prisma.staffAttributeAssignment.findFirst({where:{tenantId:data.tenantId,staffId:data.staffId,attributeDefinitionId:data.attributeDefinitionId,startDate:data.startDate,endDate:data.endDate,isActive}});}
  private overlap(aS:Date|null,aE:Date|null,bS:Date|null,bE:Date|null){if(!aS||!aE||!bS||!bE)return true;return aS<=bE&&bS<=aE;}
  private staff(tenantId:string,id:string,active:boolean){return this.prisma.staff.findFirst({where:{tenantId,id}}).then(row=>{if(!row)throw new NotFoundException('職員が見つかりません。');if(active&&!row.isActive)throw new BadRequestException('無効な職員へ属性を割り当てできません。');return row;});}
  private async definition(tenantId:string,id:string){const row=await this.prisma.staffAttributeDefinition.findFirst({where:{tenantId,id}});if(!row)throw new NotFoundException('属性定義が見つかりません。');return row;}
  private async assignment(tenantId:string,staffId:string,id:string){const row=await this.prisma.staffAttributeAssignment.findFirst({where:{tenantId,staffId,id}});if(!row)throw new NotFoundException('職員属性が見つかりません。');return row;}
  private date(v:Date|null){return v?.toISOString().slice(0,10)??null;}
  private definitionSnapshot(row:StaffAttributeDefinition){return{code:row.code,name:row.name,shortName:row.shortName,category:row.category,description:row.description,displayOrder:row.displayOrder,color:row.color,isSystem:row.isSystem,isActive:row.isActive};}
  private assignmentSnapshot(row:StaffAttributeAssignment){return{attributeDefinitionId:row.attributeDefinitionId,startDate:this.date(row.startDate),endDate:this.date(row.endDate),notes:row.notes,isPrimary:row.isPrimary,isActive:row.isActive};}
  private logDefinition(user:AuthenticatedUser,action:string,before:StaffAttributeDefinition|null,after:StaffAttributeDefinition){return this.audit.create(user.tenantId,user.sub,action,'StaffAttributeDefinition',after.id,{tenantId:user.tenantId,attributeDefinitionId:after.id,category:after.category,code:after.code,before:before?this.definitionSnapshot(before):null,after:this.definitionSnapshot(after)});}
  private logAssignment(user:AuthenticatedUser,action:string,before:StaffAttributeAssignment|null,after:StaffAttributeAssignment){return this.definition(user.tenantId,after.attributeDefinitionId).then(def=>this.audit.create(user.tenantId,user.sub,action,'StaffAttributeAssignment',after.id,{tenantId:user.tenantId,staffId:after.staffId,attributeDefinitionId:def.id,assignmentId:after.id,category:def.category,code:def.code,before:before?this.assignmentSnapshot(before):null,after:this.assignmentSnapshot(after)}));}
}
