import { useState } from 'react';
export type ManagerReviewCard = { id: string; groupId: string; revision: number; dates: string[]; targetLabel: string; reason: string; knownConditions: string[]; impact: string; status: string; kind: string; answer?: Answer | null; options: {value: string; label: string}[] };
export type Answer = {option: string; time?: string; startTime?: string; endTime?: string};
export function ManagerResolutionCards({ items, isAdmin, onAnswer, onReevaluate }: { items: ManagerReviewCard[]; isAdmin: boolean; onReevaluate?: (id:string,revision:number)=>Promise<void>; onAnswer: (id:string, revision:number, answer:Answer)=>Promise<void> }) {
  if(!isAdmin) return null;
  return <section aria-labelledby="manager-review-heading"><h2 id="manager-review-heading">シフト作成で確認が必要です</h2><p>確認事項 {new Set(items.filter(i=>i.status!=='RESOLVED').map(i=>i.groupId)).size}件</p><p>管理者確認・注意事項・確定不可は別の状態です。回答後も再評価が完了するまで確定できません。</p>{items.map(item=><ReviewCard key={`${item.id}:${item.revision}`} item={item} onAnswer={onAnswer} onReevaluate={onReevaluate}/>)}</section>;
}
function ReviewCard({item,onAnswer,onReevaluate}:{item:ManagerReviewCard;onReevaluate?: (id:string,revision:number)=>Promise<void>;onAnswer:(id:string,revision:number,answer:Answer)=>Promise<void>}) {
  const [editing,setEditing]=useState(false);const [option,setOption]=useState('');const [time,setTime]=useState('');const [startTime,setStart]=useState('');const [endTime,setEnd]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [saved,setSaved]=useState(false);
  const editable=(item.status==='NEEDS_MANAGER_REVIEW'||editing)&&!saved;
  return <article style={{border:'1px solid #64748b',borderRadius:8,padding:16,marginBottom:16,overflowWrap:'anywhere'}}><h3>{item.reason}</h3><p>{item.dates.join('、')}／{item.targetLabel}</p><strong>{saved||item.status==='ANSWERED_PENDING_REEVALUATION'?'回答保存済み・再評価待ち':item.status==='RESOLVED'?'解決済み':'管理者確認待ち'}</strong><p>{item.answer?`回答済み：${item.options.find(o=>o.value===item.answer?.option)?.label??item.answer.option} ${item.answer.time??item.answer.startTime??''} ${item.answer.endTime??''}`:null}</p><ul>{item.knownConditions.map((text,index)=><li key={index}>{text}</li>)}</ul><p>判断による影響：{item.impact}</p>{editable&&<form onSubmit={async event=>{event.preventDefault();if(busy)return;setBusy(true);setError('');try{const answer:Answer={option};if(item.kind==='EARLY_DEPARTURE')answer.time=time;if(item.kind==='HALF_DAY_BASE'&&option==='OTHER_TIME'){answer.startTime=startTime;answer.endTime=endTime;}await onAnswer(item.id,item.revision,answer);setSaved(true);}catch{setError('回答を保存できませんでした。現在の状態を再読込して確認してください。');}finally{setBusy(false);}}}><fieldset disabled={busy}><legend>管理者回答</legend>{item.options.map(choice=><label key={choice.value} style={{display:'block',padding:'8px 0'}}><input required type="radio" name={`review-${item.id}`} value={choice.value} checked={option===choice.value} onChange={()=>setOption(choice.value)}/>{choice.label}</label>)}{item.kind==='EARLY_DEPARTURE'&&<label>退勤時刻<input required type="time" value={time} onChange={e=>setTime(e.target.value)}/></label>}{item.kind==='HALF_DAY_BASE'&&option==='OTHER_TIME'&&<><label>通常の出勤時刻<input required type="time" value={startTime} onChange={e=>setStart(e.target.value)}/></label><label>通常の退勤時刻<input required type="time" value={endTime} onChange={e=>setEnd(e.target.value)}/></label></>}<button type="submit" disabled={busy}>回答を保存</button></fieldset></form>}{item.status==='ANSWERED_PENDING_REEVALUATION'&&onReevaluate&&<><button disabled={busy} type="button" onClick={async()=>{setBusy(true);setError('');try{await onReevaluate(item.id,item.revision);}catch{setError('再評価できませんでした。勤務条件・競合を確認し、必要なら回答を修正してください。');}finally{setBusy(false);}}}>回答を反映して再評価</button><button disabled={busy} type="button" onClick={()=>setEditing(true)}>回答を修正</button></>}{error&&<p role="alert">{error}</p>}</article>;
}
