import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import type { Prisma, StaffWorkRule } from '@prisma/client';
import type { AuthenticatedUser } from '../../infrastructure/auth/auth.types';
import { PrismaService } from '../../infrastructure/database/prisma.service';
import { AuditService } from '../audit/audit.service';
import type { StaffWorkRuleInputDto, StaffWorkRuleTypeValue } from './staff-work-rule.dto';

const PATTERN_RULES = new Set<StaffWorkRuleTypeValue>(['AVAILABLE_WORK_PATTERN','UNAVAILABLE_WORK_PATTERN','FIXED_WORK_PATTERN','PREFERRED_WORK_PATTERN']);
const DAY_RULES = new Set<StaffWorkRuleTypeValue>(['AVAILABLE_DAY_OF_WEEK','UNAVAILABLE_DAY_OF_WEEK','REQUIRED_DAY_OFF']);
const TIME_RULES = new Set<StaffWorkRuleTypeValue>(['AVAILABLE_TIME_RANGE','UNAVAILABLE_TIME_RANGE']);
const NUMERIC_LIMITS: Partial<Record<StaffWorkRuleTypeValue, number>> = { MAX_WORK_DAYS_PER_WEEK:7, MAX_WORK_DAYS_PER_MONTH:31, MIN_WORK_DAYS_PER_MONTH:31, MAX_CONSECUTIVE_WORK_DAYS:31, MAX_WORK_MINUTES_PER_MONTH:44640, MIN_WORK_MINUTES_PER_MONTH:44640 };
const OPPOSITE: Partial<Record<StaffWorkRuleTypeValue, StaffWorkRuleTypeValue>> = { AVAILABLE_WORK_PATTERN:'UNAVAILABLE_WORK_PATTERN',UNAVAILABLE_WORK_PATTERN:'AVAILABLE_WORK_PATTERN',AVAILABLE_DAY_OF_WEEK:'UNAVAILABLE_DAY_OF_WEEK',UNAVAILABLE_DAY_OF_WEEK:'AVAILABLE_DAY_OF_WEEK',AVAILABLE_TIME_RANGE:'UNAVAILABLE_TIME_RANGE',UNAVAILABLE_TIME_RANGE:'AVAILABLE_TIME_RANGE' };

type RuleData = { tenantId:string;staffId:string;ruleType:StaffWorkRuleTypeValue;workPatternId:string|null;dayOfWeek:number|null;startDate:Date|null;endDate:Date|null;startTime:string|null;endTime:string|null;numericValue:number|null;booleanValue:boolean|null;priority:number;isHardConstraint:boolean;reason:string|null;isActive:boolean };

@Injectable()
export class StaffWorkRulesService {
  constructor(private readonly prisma: PrismaService, private readonly audit: AuditService) {}
  async list(user:AuthenticatedUser,staffId:string){await this.staff(user.tenantId,staffId,false);return this.prisma.staffWorkRule.findMany({where:{tenantId:user.tenantId,staffId},include:{workPattern:true},orderBy:[{isActive:'desc'},{priority:'asc'},{createdAt:'asc'}]});}
  async create(user:AuthenticatedUser,staffId:string,input:StaffWorkRuleInputDto){await this.staff(user.tenantId,staffId,true);const data=await this.prepare(user.tenantId,staffId,input);const inactive=await this.findExact(data,false);await this.checkConflicts(data,inactive?.id);if(inactive){const row=await this.prisma.staffWorkRule.update({where:{id:inactive.id},data:{...data,isActive:true}});await this.audit.create(user.tenantId,user.sub,'STAFF_WORK_RULE_REACTIVATED','StaffWorkRule',row.id,this.detail(staffId,inactive,row));return row;}const row=await this.prisma.staffWorkRule.create({data});await this.audit.create(user.tenantId,user.sub,'STAFF_WORK_RULE_CREATED','StaffWorkRule',row.id,this.detail(staffId,null,row));return row;}
  async update(user:AuthenticatedUser,staffId:string,ruleId:string,input:StaffWorkRuleInputDto){await this.staff(user.tenantId,staffId,true);const before=await this.rule(user.tenantId,staffId,ruleId);const data=await this.prepare(user.tenantId,staffId,input,before.workPatternId);await this.checkConflicts(data,ruleId);const row=await this.prisma.staffWorkRule.update({where:{id:ruleId},data});await this.audit.create(user.tenantId,user.sub,row.isActive&&!before.isActive?'STAFF_WORK_RULE_REACTIVATED':'STAFF_WORK_RULE_UPDATED','StaffWorkRule',row.id,this.detail(staffId,before,row));return row;}
  async deactivate(user:AuthenticatedUser,staffId:string,ruleId:string){await this.staff(user.tenantId,staffId,false);const before=await this.rule(user.tenantId,staffId,ruleId);const row=await this.prisma.staffWorkRule.update({where:{id:ruleId},data:{isActive:false}});await this.audit.create(user.tenantId,user.sub,'STAFF_WORK_RULE_DEACTIVATED','StaffWorkRule',row.id,this.detail(staffId,before,row));return row;}

  private async prepare(tenantId:string,staffId:string,input:StaffWorkRuleInputDto,currentPatternId?:string|null):Promise<RuleData>{this.validate(input);if(input.workPatternId){const p=await this.prisma.workPattern.findFirst({where:{id:input.workPatternId,tenantId}});if(!p)throw new BadRequestException('勤務パターンが見つかりません。');if(!p.isActive&&p.id!==currentPatternId)throw new BadRequestException('無効な勤務パターンは新たに指定できません。');}return{tenantId,staffId,ruleType:input.ruleType,workPatternId:input.workPatternId??null,dayOfWeek:input.dayOfWeek??null,startDate:input.startDate?new Date(`${input.startDate}T00:00:00.000Z`):null,endDate:input.endDate?new Date(`${input.endDate}T00:00:00.000Z`):null,startTime:input.startTime??null,endTime:input.endTime??null,numericValue:input.numericValue??null,booleanValue:null,priority:input.priority,isHardConstraint:input.isHardConstraint,reason:input.reason?.trim()||null,isActive:input.isActive};}
  private validate(input:StaffWorkRuleInputDto){const pattern=input.workPatternId!=null,day=input.dayOfWeek!=null,time=input.startTime!=null||input.endTime!=null,numeric=input.numericValue!=null;if(input.booleanValue!=null)throw new BadRequestException('booleanValueは現在の勤務条件種別では使用できません。');if(input.reason&&/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/.test(input.reason))throw new BadRequestException('理由に制御文字は使用できません。');if((input.startDate==null)!==(input.endDate==null))throw new BadRequestException('適用開始日と終了日は両方設定してください。');if(input.startDate&&input.endDate&&input.startDate>input.endDate)throw new BadRequestException('適用開始日は終了日以前にしてください。');if((input.startTime==null)!==(input.endTime==null))throw new BadRequestException('開始時刻と終了時刻は両方設定してください。');if(input.startTime&&input.endTime&&input.startTime>=input.endTime)throw new BadRequestException('同日内で終了時刻は開始時刻より後にしてください。');if(PATTERN_RULES.has(input.ruleType)){if(!pattern||time||numeric)throw new BadRequestException('勤務パターンルールの入力項目が正しくありません。');}else if(DAY_RULES.has(input.ruleType)){if(!day||pattern||time||numeric)throw new BadRequestException('曜日ルールの入力項目が正しくありません。');}else if(TIME_RULES.has(input.ruleType)){if(!time||pattern||numeric)throw new BadRequestException('時間帯ルールの入力項目が正しくありません。');}else{const max=NUMERIC_LIMITS[input.ruleType];if(max==null||!numeric||pattern||day||time||input.numericValue!>max)throw new BadRequestException(`数値ルールは0〜${max??0}の整数で指定してください。`);}}
  private async findExact(data:RuleData,isActive:boolean){return this.prisma.staffWorkRule.findFirst({where:{tenantId:data.tenantId,staffId:data.staffId,isActive,ruleType:data.ruleType,workPatternId:data.workPatternId,dayOfWeek:data.dayOfWeek,startDate:data.startDate,endDate:data.endDate,startTime:data.startTime,endTime:data.endTime,numericValue:data.numericValue,booleanValue:null}});}
  private async checkConflicts(data:RuleData,excludeId?:string){const rows=await this.prisma.staffWorkRule.findMany({where:{tenantId:data.tenantId,staffId:data.staffId,isActive:true,...(excludeId?{id:{not:excludeId}}:{})}});if(rows.some(r=>this.exact(r,data)))throw new ConflictException('同じ勤務条件が既に登録されています。');const overlapping=rows.filter(r=>this.periodsOverlap(r.startDate,r.endDate,data.startDate,data.endDate)&&this.daysOverlap(r.dayOfWeek,data.dayOfWeek));const opposite=OPPOSITE[data.ruleType];if(opposite&&overlapping.some(r=>r.ruleType===opposite&&r.workPatternId===data.workPatternId&&r.startTime===data.startTime&&r.endTime===data.endTime))throw new ConflictException('重複する期間に矛盾する勤務条件があります。');if(data.ruleType==='FIXED_WORK_PATTERN'&&overlapping.some(r=>r.ruleType==='FIXED_WORK_PATTERN'&&r.workPatternId!==data.workPatternId))throw new ConflictException('重複する期間・曜日に複数の固定勤務パターンは指定できません。');const pair:Record<string,string>={MIN_WORK_DAYS_PER_MONTH:'MAX_WORK_DAYS_PER_MONTH',MAX_WORK_DAYS_PER_MONTH:'MIN_WORK_DAYS_PER_MONTH',MIN_WORK_MINUTES_PER_MONTH:'MAX_WORK_MINUTES_PER_MONTH',MAX_WORK_MINUTES_PER_MONTH:'MIN_WORK_MINUTES_PER_MONTH'};const other=overlapping.find(r=>r.ruleType===pair[data.ruleType]);if(other&&((data.ruleType.startsWith('MIN_')&&data.numericValue!>other.numericValue!)||(data.ruleType.startsWith('MAX_')&&data.numericValue!<other.numericValue!)))throw new ConflictException('最小値が最大値を超える勤務条件は設定できません。');}
  private exact(row:StaffWorkRule,data:RuleData){return row.ruleType===data.ruleType&&row.workPatternId===data.workPatternId&&row.dayOfWeek===data.dayOfWeek&&this.date(row.startDate)===this.date(data.startDate)&&this.date(row.endDate)===this.date(data.endDate)&&row.startTime===data.startTime&&row.endTime===data.endTime&&row.numericValue===data.numericValue&&row.booleanValue===null;}
  private periodsOverlap(aStart:Date|null,aEnd:Date|null,bStart:Date|null,bEnd:Date|null){if(!aStart||!aEnd||!bStart||!bEnd)return true;return aStart<=bEnd&&bStart<=aEnd;}
  private daysOverlap(a:number|null,b:number|null){return a==null||b==null||a===b;}
  private date(value:Date|null){return value?.toISOString().slice(0,10)??null;}
  private async staff(tenantId:string,id:string,active:boolean){const row=await this.prisma.staff.findFirst({where:{id,tenantId}});if(!row)throw new NotFoundException('職員が見つかりません。');if(active&&!row.isActive)throw new BadRequestException('無効な職員へ勤務条件を追加・更新できません。');return row;}
  private async rule(tenantId:string,staffId:string,id:string){const row=await this.prisma.staffWorkRule.findFirst({where:{id,tenantId,staffId}});if(!row)throw new NotFoundException('勤務条件が見つかりません。');return row;}
  private detail(staffId:string,before:StaffWorkRule|null,after:StaffWorkRule):Prisma.InputJsonValue{return{staffId,ruleId:after.id,ruleType:after.ruleType,before:before?this.snapshot(before):null,after:this.snapshot(after)} as Prisma.InputJsonValue;}
  // reason is operationally required and retained in full (max 500 chars); UI escaping and control-character rejection reduce disclosure/injection risk.
  private snapshot(row:StaffWorkRule){return{ruleType:row.ruleType,workPatternId:row.workPatternId,dayOfWeek:row.dayOfWeek,startDate:this.date(row.startDate),endDate:this.date(row.endDate),startTime:row.startTime,endTime:row.endTime,numericValue:row.numericValue,booleanValue:row.booleanValue,priority:row.priority,isHardConstraint:row.isHardConstraint,reason:row.reason,isActive:row.isActive};}
}
