import { FormEvent, useEffect, useState } from 'react';
import { api, type PaidLeaveBalance, type PaidLeaveGrant, type PaidLeaveUsage, type Staff } from '../../api/client';

export function PaidLeaveManagement({token}:{token:string}){
  const [staff,setStaff]=useState<Staff[]>([]);const [staffId,setStaffId]=useState('');const [grants,setGrants]=useState<PaidLeaveGrant[]>([]);const [usages,setUsages]=useState<PaidLeaveUsage[]>([]);const [balance,setBalance]=useState<PaidLeaveBalance|null>(null);const [message,setMessage]=useState('');const [cancellingId,setCancellingId]=useState('');
  useEffect(()=>{api.staff(token,true).then(rows=>{setStaff(rows);setStaffId(value=>value||rows[0]?.id||'');}).catch(error=>setMessage(error instanceof Error?error.message:'職員を取得できませんでした。'));},[token]);
  const reload=async(id=staffId)=>{if(!id)return;try{const [g,u,b]=await Promise.all([api.paidLeaveGrants(token,id),api.paidLeaveUsages(token,id),api.paidLeaveBalance(token,id)]);setGrants(g);setUsages(u);setBalance(b);setMessage('');}catch(error){setMessage(error instanceof Error?error.message:'有給情報を取得できませんでした。');}};
  useEffect(()=>{void reload(staffId);},[staffId]);
  return <section className="card mt-6"><div><h2 className="text-xl font-black">有給管理</h2><p className="mt-1 text-sm text-slate-600">人間が確認した付与と取得実績だけを記録します。AI提案や未確定候補は残高に含みません。</p></div>
    <label className="mt-5 block text-sm font-semibold">職員<select className="input mt-2" value={staffId} onChange={event=>setStaffId(event.target.value)}>{staff.map(row=><option key={row.id} value={row.id}>{row.employeeNumber} {row.displayName}</option>)}</select></label>
    {message&&<p role="alert" className="mt-4 rounded bg-amber-50 p-3 text-sm text-amber-800">{message}</p>}
    {balance&&<div className="mt-5 grid gap-3 sm:grid-cols-3"><Metric label="付与合計" value={days(balance.grantedHalfDays)}/><Metric label="取得済み" value={days(balance.usedHalfDays)}/><Metric label="現在残高" value={days(balance.availableHalfDays)}/></div>}
    {staffId&&<div className="mt-6 grid gap-6 lg:grid-cols-2"><GrantForm token={token} staffId={staffId} onSaved={()=>reload()}/><UsageForm token={token} staffId={staffId} grants={balance?.grants.filter(row=>row.available&&row.remainingHalfDays>0)??[]} onSaved={()=>reload()}/></div>}
    <div className="mt-7 overflow-x-auto"><h3 className="font-bold">付与履歴</h3><table className="mt-2 w-full min-w-[700px] text-left text-sm"><thead><tr>{['付与日','有効期間','種別','付与量','状態'].map(x=><th className="px-3 py-2" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y">{grants.map(row=><tr key={row.id}><td className="px-3 py-2">{row.grantDate.slice(0,10)}</td><td className="px-3 py-2">{row.validFrom.slice(0,10)}〜{row.expiresAt.slice(0,10)}</td><td className="px-3 py-2">{row.source==='INITIAL_BALANCE'?'初期導入残高':row.source==='ADJUSTMENT'?'調整':'通常付与'}</td><td className="px-3 py-2">{days(row.grantedHalfDays)}</td><td className="px-3 py-2">{row.voidedAt?'取消済み':'有効'}</td></tr>)}</tbody></table></div>
    <div className="mt-7 overflow-x-auto"><h3 className="font-bold">取得・訂正履歴</h3><table className="mt-2 w-full min-w-[760px] text-left text-sm"><thead><tr>{['取得日','単位','取得量','状態','人間確認','操作'].map(x=><th className="px-3 py-2" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y">{usages.map(row=><tr key={row.id}><td className="px-3 py-2">{row.usageDate.slice(0,10)}</td><td className="px-3 py-2">{row.unit==='DAY'?'1日':'半日'}</td><td className="px-3 py-2">{days(row.usedHalfDays)}</td><td className="px-3 py-2">{statusLabel(row.status)}</td><td className="px-3 py-2">{row.confirmedAt?`確定 ${new Date(row.confirmedAt).toLocaleString('ja-JP')}`:'未確定'}</td><td className="px-3 py-2">{row.status==='CONFIRMED'?<button disabled={Boolean(cancellingId)} className="btn-quiet disabled:opacity-50" onClick={async()=>{const reason=window.prompt('取消理由を入力してください');if(!reason?.trim())return;if(!window.confirm(`この有給取得を取り消しますか？\n取得日: ${row.usageDate.slice(0,10)}\n理由: ${reason.trim()}`))return;setCancellingId(row.id);try{await api.cancelPaidLeaveUsage(token,staffId,row.id,reason.trim());await reload();}catch(error){setMessage(error instanceof Error?error.message:'有給取得を取り消せませんでした。');}finally{setCancellingId('');}}}>{cancellingId===row.id?'取消中…':'取消'}</button>:'—'}</td></tr>)}</tbody></table></div>
  </section>;
}

function GrantForm({token,staffId,onSaved}:{token:string;staffId:string;onSaved:()=>Promise<void>}){const today=new Date().toISOString().slice(0,10);const [grantDate,setGrantDate]=useState(today);const [validFrom,setValidFrom]=useState(today);const [expiresAt,setExpiresAt]=useState(today);const [halfDays,setHalfDays]=useState(20);const [source,setSource]=useState<PaidLeaveGrant['source']>('INITIAL_BALANCE');const [note,setNote]=useState('');const [submitting,setSubmitting]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();if(submitting)return;setSubmitting(true);try{await api.createPaidLeaveGrant(token,staffId,{grantDate,validFrom,expiresAt,grantedHalfDays:halfDays,source,note:note||null});await onSaved();}finally{setSubmitting(false);}};return <form onSubmit={submit} className="rounded-xl border p-4"><h3 className="font-bold">付与・初期残高を登録</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="付与日" value={grantDate} set={setGrantDate}/><Field label="有効開始日" value={validFrom} set={setValidFrom}/><Field label="失効日" value={expiresAt} set={setExpiresAt}/><label className="text-sm">付与量（0.5日単位）<input className="input mt-1" type="number" min="0.5" step="0.5" value={halfDays/2} onChange={e=>setHalfDays(Math.round(Number(e.target.value)*2))}/></label><label className="text-sm sm:col-span-2">種別<select className="input mt-1" value={source} onChange={e=>setSource(e.target.value as PaidLeaveGrant['source'])}><option value="INITIAL_BALANCE">初期導入残高</option><option value="NORMAL_GRANT">通常付与</option><option value="ADJUSTMENT">調整</option></select></label><label className="text-sm sm:col-span-2">確認メモ<textarea className="input mt-1" value={note} onChange={e=>setNote(e.target.value)}/></label></div><button disabled={submitting} className="btn-primary mt-4 disabled:opacity-50">{submitting?'登録中…':'人間確認済みとして登録'}</button></form>}
function UsageForm({token,staffId,grants,onSaved}:{token:string;staffId:string;grants:PaidLeaveBalance['grants'];onSaved:()=>Promise<void>}){const [usageDate,setUsageDate]=useState(new Date().toISOString().slice(0,10));const [unit,setUnit]=useState<'DAY'|'HALF_DAY'>('DAY');const [grantId,setGrantId]=useState('');const [note,setNote]=useState('');const [submitting,setSubmitting]=useState(false);useEffect(()=>setGrantId(value=>grants.some(row=>row.grantId===value)?value:grants[0]?.grantId||''),[grants]);const submit=async(e:FormEvent)=>{e.preventDefault();if(!grantId||submitting)return;const amount=unit==='DAY'?2:1;setSubmitting(true);try{await api.confirmPaidLeaveUsage(token,staffId,{usageDate,unit,allocations:[{grantId,allocatedHalfDays:amount}],decisionNote:note});setNote('');await onSaved();}finally{setSubmitting(false);}};return <form onSubmit={submit} className="rounded-xl border p-4"><h3 className="font-bold">取得実績を人間確定</h3><p className="mt-1 text-xs text-slate-500">候補ではなく、職員と管理者が相談して確定した実績だけを登録してください。</p><div className="mt-3 grid gap-3"><Field label="取得日" value={usageDate} set={setUsageDate}/><label className="text-sm">単位<select className="input mt-1" value={unit} onChange={e=>setUnit(e.target.value as 'DAY'|'HALF_DAY')}><option value="DAY">1日</option><option value="HALF_DAY">半日</option></select></label><label className="text-sm">消化する付与<select required className="input mt-1" value={grantId} onChange={e=>setGrantId(e.target.value)}><option value="">選択してください</option>{grants.map(row=><option value={row.grantId} key={row.grantId}>{row.validFrom}／残{days(row.remainingHalfDays)}</option>)}</select><span className="mt-1 block text-xs text-slate-500">表示順は自動消化順ではありません。管理者が対象の付与を明示的に選択します。</span></label><label className="text-sm">相談結果・確定理由<textarea required className="input mt-1" value={note} onChange={e=>setNote(e.target.value)}/></label></div><button disabled={!grantId||!note.trim()||submitting} className="btn-primary mt-4 disabled:opacity-50">{submitting?'確定中…':'取得を確定'}</button></form>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div>}
function Field({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="text-sm">{label}<input required className="input mt-1" type="date" value={value} onChange={e=>set(e.target.value)}/></label>}
function days(halfDays:number){return `${(halfDays/2).toFixed(halfDays%2?1:0)}日`;}
function statusLabel(value:PaidLeaveUsage['status']){return {PROPOSED:'提案（未算入）',CONFIRMED:'人間確定',CANCELLED:'取消済み',CORRECTED:'訂正済み'}[value];}
