import { useEffect, useState, type FormEvent } from 'react';
import { api, type Staff, type StaffLoginAccount } from '../../api/client';

export function StaffLoginAccountManagement({token,staff,onClose}:{token:string;staff:Staff;onClose:()=>void}) {
  const [account,setAccount]=useState<StaffLoginAccount|null>(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
  const [loginId,setLoginId]=useState(''); const [email,setEmail]=useState(staff.email??''); const [role,setRole]=useState<'DIRECTOR'|'CHIEF'|'STAFF'>('STAFF');
  const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState(''); const [reason,setReason]=useState('');
  async function load(){setAccount(await api.staffLoginAccount(token,staff.id));}
  useEffect(()=>{void load().catch(e=>setMessage(e instanceof Error?e.message:'状態を確認できませんでした。'));},[staff.id,token]);
  async function issue(event:FormEvent){event.preventDefault();if(busy)return;const roleLabel={STAFF:'一般職員',CHIEF:'主任',DIRECTOR:'園長'}[role];const warning=role==='DIRECTOR'?' 園長権限では管理機能を利用できます。':'';if(!window.confirm(`${staff.displayName}さんへ「${roleLabel}」権限でログインを発行しますか？${warning}`))return;setBusy(true);setMessage('');try{await api.createStaffLoginAccount(token,staff.id,{loginId,email:email||undefined,role,temporaryPassword:password,confirmPassword:confirm});setPassword('');setConfirm('');setMessage('ログインを発行しました。仮パスワードは画面や履歴に保存されません。');await load();}catch(e){setMessage(e instanceof Error?e.message:'発行できませんでした。');}finally{setBusy(false)}}
  async function reset(event:FormEvent){event.preventDefault();if(!window.confirm('仮パスワードを再発行し、現在のログイン状態を無効にしますか？'))return;setBusy(true);try{await api.resetStaffPassword(token,staff.id,{temporaryPassword:password,confirmPassword:confirm,reason});setPassword('');setConfirm('');setReason('');setMessage('仮パスワードを再発行しました。本人は次回ログイン時に変更が必要です。');await load();}catch(e){setMessage(e instanceof Error?e.message:'再発行できませんでした。');}finally{setBusy(false)}}
  async function toggle(){if(!account)return;const next=!account.enabled;const label=next?'再開':'停止';if(!reason.trim()||!window.confirm(`この職員のログインを${label}しますか？`))return;setBusy(true);try{if(next)await api.reactivateStaffLogin(token,staff.id,reason);else await api.deactivateStaffLogin(token,staff.id,reason);setReason('');setMessage(`ログインを${label}しました。`);await load();}catch(e){setMessage(e instanceof Error?e.message:`${label}できませんでした。`);}finally{setBusy(false)}}
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/50 p-5" role="dialog" aria-modal="true"><div className="mx-auto my-6 w-full max-w-xl rounded-2xl bg-white p-6"><div className="flex justify-between gap-4"><div><h3 className="text-xl font-bold">ログイン管理</h3><p className="mt-1 text-sm text-slate-600">{staff.displayName}さん</p></div><button onClick={onClose} className="rounded-lg border px-3">閉じる</button></div>{message&&<p role="status" className="mt-4 rounded-lg bg-slate-100 p-3 text-sm">{message}</p>}{account?.enabled!==undefined&&!account.loginId?<form onSubmit={issue} className="mt-5 grid gap-4"><label>ログインID<input className="input mt-1" value={loginId} onChange={e=>setLoginId(e.target.value.toLowerCase())} pattern="[a-z0-9][a-z0-9._-]{2,63}" required /></label><label>メールアドレス（任意）<input className="input mt-1" type="email" value={email} onChange={e=>setEmail(e.target.value)} /></label><label>権限<select className="input mt-1" value={role} onChange={e=>setRole(e.target.value as typeof role)}><option value="STAFF">一般職員</option><option value="CHIEF">主任</option><option value="DIRECTOR">園長</option></select></label><PasswordFields password={password} confirm={confirm} setPassword={setPassword} setConfirm={setConfirm}/><button disabled={busy} className="btn-primary">{busy?'発行中…':'ログインを発行'}</button><p className="text-xs text-slate-600">仮パスワードは別の安全な手段で本人だけに伝えてください。AeN Shiftには平文保存されません。</p></form>:account?.loginId?<div className="mt-5"><dl className="grid gap-2 text-sm"><div><dt className="text-slate-500">ログインID</dt><dd className="font-semibold">{account.loginId}</dd></div><div><dt className="text-slate-500">状態</dt><dd>{account.enabled?'有効':'停止中'}{account.mustChangePassword?'・初回変更待ち':''}</dd></div></dl><form onSubmit={reset} className="mt-5 grid gap-4"><h4 className="font-bold">仮パスワード再発行</h4><PasswordFields password={password} confirm={confirm} setPassword={setPassword} setConfirm={setConfirm}/><label>理由<input className="input mt-1" value={reason} onChange={e=>setReason(e.target.value)} required /></label><button disabled={busy} className="rounded-lg border px-4 py-3 font-semibold">再発行を確認</button></form><div className="mt-5 border-t pt-5"><label>停止・再開理由<input className="input mt-1" value={reason} onChange={e=>setReason(e.target.value)} /></label><button disabled={busy||!reason.trim()} onClick={()=>void toggle()} className="mt-3 rounded-lg border border-rose-200 px-4 py-3 font-semibold text-rose-700">ログインを{account.enabled?'停止':'再開'}</button></div></div>:<p className="mt-5">読み込み中…</p>}</div></div>;
}
function PasswordFields({password,confirm,setPassword,setConfirm}:{password:string;confirm:string;setPassword:(v:string)=>void;setConfirm:(v:string)=>void}){return <><label>仮パスワード<input className="input mt-1" type="password" autoComplete="new-password" minLength={12} value={password} onChange={e=>setPassword(e.target.value)} required /></label><label>仮パスワード（確認）<input className="input mt-1" type="password" autoComplete="new-password" minLength={12} value={confirm} onChange={e=>setConfirm(e.target.value)} required /></label></>}
