import { useEffect, useState } from 'react';
import { api, type Staff, type StaffWorkRule, type StaffWorkRuleInput, type StaffWorkRuleType, type WorkPattern } from '../../api/client';
import { useFeature } from '../features/use-feature';

const labels:Record<StaffWorkRuleType,string>={AVAILABLE_WORK_PATTERN:'利用可能な勤務パターン',UNAVAILABLE_WORK_PATTERN:'利用不可の勤務パターン',AVAILABLE_DAY_OF_WEEK:'勤務可能曜日',UNAVAILABLE_DAY_OF_WEEK:'勤務不可曜日',AVAILABLE_TIME_RANGE:'勤務可能時間帯',UNAVAILABLE_TIME_RANGE:'勤務不可時間帯',MAX_WORK_DAYS_PER_WEEK:'週の最大勤務日数',MAX_WORK_DAYS_PER_MONTH:'月の最大勤務日数',MAX_WORK_MINUTES_PER_MONTH:'月の最大勤務分数',MIN_WORK_DAYS_PER_MONTH:'月の最低勤務日数',MIN_WORK_MINUTES_PER_MONTH:'月の最低勤務分数',MAX_CONSECUTIVE_WORK_DAYS:'最大連続勤務日数',REQUIRED_DAY_OFF:'必須休日',FIXED_WORK_PATTERN:'固定勤務パターン',PREFERRED_WORK_PATTERN:'希望勤務パターン'};
const dayLabels=['日','月','火','水','木','金','土'];
const initial:StaffWorkRuleInput={ruleType:'UNAVAILABLE_DAY_OF_WEEK',workPatternId:null,dayOfWeek:0,startDate:null,endDate:null,startTime:null,endTime:null,numericValue:null,booleanValue:null,priority:100,isHardConstraint:true,reason:null,isActive:true};
const patternRules=new Set<StaffWorkRuleType>(['AVAILABLE_WORK_PATTERN','UNAVAILABLE_WORK_PATTERN','FIXED_WORK_PATTERN','PREFERRED_WORK_PATTERN']);
const dayRules=new Set<StaffWorkRuleType>(['AVAILABLE_DAY_OF_WEEK','UNAVAILABLE_DAY_OF_WEEK','REQUIRED_DAY_OFF']);
const timeRules=new Set<StaffWorkRuleType>(['AVAILABLE_TIME_RANGE','UNAVAILABLE_TIME_RANGE']);

export function StaffWorkRuleManagement({token,staff,readOnly=false,onClose}:{token:string;staff:Staff;readOnly?:boolean;onClose:()=>void}){
  const feature=useFeature(token,'STAFF_WORK_RULES'); const [rows,setRows]=useState<StaffWorkRule[]>([]); const [patterns,setPatterns]=useState<WorkPattern[]>([]); const [editing,setEditing]=useState<StaffWorkRule|null|undefined>(undefined); const [input,setInput]=useState<StaffWorkRuleInput>(initial); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(true);
  async function load(){setLoading(true);try{const [rules,workPatterns]=await Promise.all([api.staffWorkRules(token,staff.id),api.workPatterns(token)]);setRows(rules);setPatterns(workPatterns);}catch(e){setMessage(e instanceof Error?e.message:'勤務条件を取得できませんでした。');}finally{setLoading(false);}}
  useEffect(()=>{void load();},[staff.id,token]);
  function start(row?:StaffWorkRule){setEditing(row??null);setInput(row?{ruleType:row.ruleType,workPatternId:row.workPatternId,dayOfWeek:row.dayOfWeek,startDate:row.startDate?.slice(0,10)??null,endDate:row.endDate?.slice(0,10)??null,startTime:row.startTime,endTime:row.endTime,numericValue:row.numericValue,booleanValue:row.booleanValue,priority:row.priority,isHardConstraint:row.isHardConstraint,reason:row.reason,isActive:row.isActive}:initial);}
  async function save(){try{if(editing)await api.updateStaffWorkRule(token,staff.id,editing.id,input);else await api.createStaffWorkRule(token,staff.id,input);setEditing(undefined);setMessage('勤務条件を保存しました。');await load();}catch(e){setMessage(e instanceof Error?e.message:'勤務条件を保存できませんでした。');}}
  async function disable(row:StaffWorkRule){try{await api.deactivateStaffWorkRule(token,staff.id,row.id);setMessage('勤務条件を無効化しました。');await load();}catch(e){setMessage(e instanceof Error?e.message:'勤務条件を無効化できませんでした。');}}
  const canEdit=!readOnly&&feature.loaded&&feature.enabled;
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/50 p-4" role="dialog" aria-modal="true"><section className="mx-auto max-w-5xl rounded-2xl bg-white p-5 shadow-2xl"><div className="flex items-start justify-between gap-3"><div><h3 className="text-xl font-bold">{staff.displayName}さんの勤務条件</h3><p className="mt-1 text-sm text-slate-600">職員別の条件を管理します。現在の自動生成は従来の職員項目を使用します。</p></div><button className="rounded-lg border px-4 py-2" onClick={onClose}>閉じる</button></div>
  {!feature.loaded?<p className="mt-4">利用可否を確認中…</p>:!feature.enabled?<p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">現在のプランでは勤務条件の追加・編集・無効化は利用できません。登録済み条件は参照できます。</p>:<button className="btn-primary mt-4" onClick={()=>start()}>勤務条件を追加</button>}{message&&<p role="status" className="mt-3 text-sm">{message}</p>}
  <div className="mt-5 overflow-x-auto">{loading?<p className="py-8 text-center text-slate-500">読み込み中…</p>:rows.length===0?<p className="py-8 text-center text-slate-500">登録済みの勤務条件はありません。</p>:<table className="w-full min-w-[850px] text-left text-sm"><thead><tr>{['条件種別','勤務パターン／曜日／値','適用期間','制約','理由','状態','操作'].map(x=><th className="border-b p-2" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><td className="border-b p-2">{labels[row.ruleType]}</td><td className="border-b p-2">{ruleValue(row)}</td><td className="border-b p-2">{row.startDate&&row.endDate?`${row.startDate.slice(0,10)}〜${row.endDate.slice(0,10)}`:'常時適用'}</td><td className="border-b p-2">{row.isHardConstraint?'必ず守る条件':'できるだけ考慮する希望'}</td><td className="max-w-xs break-words border-b p-2">{row.reason??'—'}</td><td className="border-b p-2">{row.isActive?'有効':'無効'}</td><td className="border-b p-2">{canEdit&&<div className="flex gap-2"><button className="rounded border px-2 py-1" onClick={()=>start(row)}>編集</button>{row.isActive&&<button className="rounded border border-rose-200 px-2 py-1 text-rose-700" onClick={()=>void disable(row)}>無効化</button>}</div>}</td></tr>)}</tbody></table>}</div>
  {editing!==undefined&&canEdit&&<div className="mt-6 rounded-xl border bg-slate-50 p-4"><div className="grid gap-3 sm:grid-cols-2"><label>条件種別<select className="mt-1 w-full rounded border p-2" value={input.ruleType} onChange={e=>setInput({...initial,ruleType:e.target.value as StaffWorkRuleType})}>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>{patternRules.has(input.ruleType)&&<label>勤務パターン<select className="mt-1 w-full rounded border p-2" value={input.workPatternId??''} onChange={e=>setInput({...input,workPatternId:e.target.value||null})}><option value="">選択してください</option>{patterns.map(p=><option key={p.id} value={p.id}>{p.name}{p.isActive?'':'（勤務パターン無効）'}</option>)}</select></label>}{dayRules.has(input.ruleType)&&<label>曜日<select className="mt-1 w-full rounded border p-2" value={input.dayOfWeek??0} onChange={e=>setInput({...input,dayOfWeek:Number(e.target.value)})}>{dayLabels.map((d,i)=><option key={d} value={i}>{d}曜日</option>)}</select></label>}{timeRules.has(input.ruleType)&&<><label>開始時刻<input type="time" className="mt-1 w-full rounded border p-2" value={input.startTime??''} onChange={e=>setInput({...input,startTime:e.target.value||null})}/></label><label>終了時刻<input type="time" className="mt-1 w-full rounded border p-2" value={input.endTime??''} onChange={e=>setInput({...input,endTime:e.target.value||null})}/></label></>}{!patternRules.has(input.ruleType)&&!dayRules.has(input.ruleType)&&!timeRules.has(input.ruleType)&&<label>数値<input type="number" min="0" className="mt-1 w-full rounded border p-2" value={input.numericValue??''} onChange={e=>setInput({...input,numericValue:e.target.value===''?null:Number(e.target.value)})}/></label>}<label>適用開始日<input type="date" className="mt-1 w-full rounded border p-2" value={input.startDate??''} onChange={e=>setInput({...input,startDate:e.target.value||null})}/></label><label>適用終了日<input type="date" className="mt-1 w-full rounded border p-2" value={input.endDate??''} onChange={e=>setInput({...input,endDate:e.target.value||null})}/></label><label>優先度<input type="number" min="0" max="1000" className="mt-1 w-full rounded border p-2" value={input.priority} onChange={e=>setInput({...input,priority:Number(e.target.value)})}/></label><label className="flex items-center gap-2"><input type="checkbox" checked={input.isHardConstraint} onChange={e=>setInput({...input,isHardConstraint:e.target.checked})}/>必ず守る条件として分類</label><label className="sm:col-span-2">理由<textarea className="mt-1 w-full rounded border p-2" maxLength={500} value={input.reason??''} onChange={e=>setInput({...input,reason:e.target.value||null})}/></label></div><div className="mt-4 flex justify-end gap-2"><button className="rounded border px-4 py-2" onClick={()=>setEditing(undefined)}>キャンセル</button><button className="btn-primary" onClick={()=>void save()}>保存</button></div></div>}</section></div>;
}
function ruleValue(row:StaffWorkRule){if(row.workPattern)return `${row.workPattern.name}${row.workPattern.isActive?'':'（勤務パターン無効）'}`;if(row.dayOfWeek!=null)return `${dayLabels[row.dayOfWeek]}曜日`;if(row.startTime&&row.endTime)return `${row.startTime}〜${row.endTime}`;if(row.numericValue!=null)return row.ruleType.includes('MINUTES')?`${Math.floor(row.numericValue/60)}時間${row.numericValue%60?`${row.numericValue%60}分`:''}（${row.numericValue}分）`:`${row.numericValue}日`;return'—';}
