import { useCallback, useEffect, useState } from 'react';
import { api, type Staff, type StaffWorkContract, type StaffWorkContractInput } from '../../api/client';

type Draft = { effectiveFrom:string;effectiveTo:string;annualHours:string;annualMinutes:string;dailyHours:string;dailyMinutes:string };
const empty:Draft={effectiveFrom:'',effectiveTo:'',annualHours:'',annualMinutes:'0',dailyHours:'',dailyMinutes:'0'};

export function StaffWorkContractManagement({token,staff,onClose}:{token:string;staff:Staff;onClose:()=>void}){
  const [rows,setRows]=useState<StaffWorkContract[]>([]);const [draft,setDraft]=useState<Draft>(empty);const [editing,setEditing]=useState<StaffWorkContract|null>(null);const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);
  const load=useCallback(async()=>{try{setRows(await api.staffWorkContracts(token,staff.id));}catch(error){setMessage(error instanceof Error?error.message:'勤務契約を読み込めませんでした。');}},[token,staff.id]);
  useEffect(()=>{void load();},[load]);
  const save=async()=>{setMessage('');const input=toInput(draft);if(!input){setMessage('時間と分を正しく入力してください。');return;}setSaving(true);try{if(editing)await api.updateStaffWorkContract(token,staff.id,editing.id,input);else await api.createStaffWorkContract(token,staff.id,input);setDraft(empty);setEditing(null);setMessage('勤務契約を保存しました。');await load();}catch(error){setMessage(error instanceof Error?error.message:'勤務契約を保存できませんでした。');}finally{setSaving(false);}};
  const startEdit=(row:StaffWorkContract)=>{setEditing(row);setDraft(fromRow(row));};
  const voidRow=async(row:StaffWorkContract)=>{if(!window.confirm('この契約を無効化しますか？ データは削除されず、履歴として保持されます。'))return;setSaving(true);try{await api.voidStaffWorkContract(token,staff.id,row.id);setMessage('勤務契約を履歴保持したまま無効化しました。');await load();}catch(error){setMessage(error instanceof Error?error.message:'勤務契約を無効化できませんでした。');}finally{setSaving(false);}};
  const active=rows.filter(row=>!row.voidedAt);const hasGap=active.some((row,index)=>{const next=active[index+1];return !!row.effectiveTo&&!!next&&addDay(row.effectiveTo)!==next.effectiveFrom;});
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/50 p-4" role="dialog" aria-modal="true" aria-label={`${staff.displayName}さんの勤務契約`}><div className="mx-auto my-4 max-w-4xl rounded-2xl bg-white p-5 shadow-2xl"><div className="flex items-start justify-between gap-3"><div><h3 className="text-xl font-bold">{staff.displayName}さんの勤務契約</h3><p className="mt-1 text-sm text-slate-600">年間目標と所定1日時間を、適用期間ごとに管理します。</p></div><button onClick={onClose} className="rounded-lg border px-3 py-2">閉じる</button></div>
  {message&&<p role="status" className="mt-4 rounded-lg bg-slate-100 p-3 text-sm">{message}</p>}{hasGap&&<p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">要確認：契約期間に空白があります。年間目標は登録済み期間だけで按分されます。</p>}
  <div className="mt-5 grid gap-3 rounded-xl border p-4 sm:grid-cols-2"><DateField label="適用開始日" value={draft.effectiveFrom} onChange={value=>setDraft({...draft,effectiveFrom:value})}/><DateField label="適用終了日（任意）" value={draft.effectiveTo} onChange={value=>setDraft({...draft,effectiveTo:value})}/><MinutesField label="年間目標時間" hours={draft.annualHours} minutes={draft.annualMinutes} onHours={value=>setDraft({...draft,annualHours:value})} onMinutes={value=>setDraft({...draft,annualMinutes:value})}/><MinutesField label="所定1日勤務時間" hours={draft.dailyHours} minutes={draft.dailyMinutes} onHours={value=>setDraft({...draft,dailyHours:value})} onMinutes={value=>setDraft({...draft,dailyMinutes:value})}/><div className="flex gap-2 sm:col-span-2"><button disabled={saving} onClick={()=>void save()} className="btn-primary">{editing?'契約を更新':'契約を追加'}</button>{editing&&<button onClick={()=>{setEditing(null);setDraft(empty);}} className="rounded-lg border px-4 py-2 font-semibold">編集をやめる</button>}</div></div>
  <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-slate-50"><tr>{['適用期間','年間目標','所定1日','状態','確認','操作'].map(x=><th key={x} className="px-3 py-2">{x}</th>)}</tr></thead><tbody className="divide-y">{rows.map((row,index)=><tr key={row.id} className={row.voidedAt?'text-slate-500':''}><td className="px-3 py-3">{row.effectiveFrom}〜{row.effectiveTo??'終了日なし'}</td><td className="px-3 py-3">{format(row.annualizedTargetMinutes)}</td><td className="px-3 py-3">{format(row.prescribedDailyMinutes)}</td><td className="px-3 py-3">{row.voidedAt?'無効（履歴保持）':'有効'}</td><td className="px-3 py-3">{!row.voidedAt&&gapAfter(rows,index)?'要確認':'—'}</td><td className="px-3 py-3"><div className="flex gap-2">{!row.voidedAt&&<><button onClick={()=>startEdit(row)} className="rounded border px-3 py-2 font-semibold">編集</button><button onClick={()=>void voidRow(row)} className="rounded border border-rose-200 px-3 py-2 font-semibold text-rose-700">履歴保持して無効化</button></>}</div></td></tr>)}</tbody></table>{!rows.length&&<p className="py-8 text-center text-slate-500">勤務契約は未設定です。</p>}</div></div></div>;
}
function DateField({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="grid gap-1 text-sm">{label}<input type="date" value={value} onChange={e=>onChange(e.target.value)} className="rounded border p-2"/></label>;}
function MinutesField({label,hours,minutes,onHours,onMinutes}:{label:string;hours:string;minutes:string;onHours:(v:string)=>void;onMinutes:(v:string)=>void}){return <fieldset><legend className="text-sm">{label}</legend><div className="mt-1 flex items-center gap-2"><input aria-label={`${label} 時間`} type="number" min="0" value={hours} onChange={e=>onHours(e.target.value)} className="w-24 rounded border p-2"/>時間<input aria-label={`${label} 分`} type="number" min="0" max="59" value={minutes} onChange={e=>onMinutes(e.target.value)} className="w-20 rounded border p-2"/>分</div></fieldset>;}
function toInput(d:Draft):StaffWorkContractInput|null{const ah=Number(d.annualHours),am=Number(d.annualMinutes),dh=Number(d.dailyHours),dm=Number(d.dailyMinutes);if(!d.effectiveFrom||![ah,am,dh,dm].every(Number.isInteger)||ah<0||dh<0||am<0||am>59||dm<0||dm>59)return null;const annual=ah*60+am,daily=dh*60+dm;if(annual<=0||daily<=0)return null;return{effectiveFrom:d.effectiveFrom,effectiveTo:d.effectiveTo||null,annualizedTargetMinutes:annual,prescribedDailyMinutes:daily};}
function fromRow(row:StaffWorkContract):Draft{return{effectiveFrom:row.effectiveFrom,effectiveTo:row.effectiveTo??'',annualHours:String(Math.floor(row.annualizedTargetMinutes/60)),annualMinutes:String(row.annualizedTargetMinutes%60),dailyHours:String(Math.floor(row.prescribedDailyMinutes/60)),dailyMinutes:String(row.prescribedDailyMinutes%60)};}
function format(minutes:number){return `${Math.floor(minutes/60)}時間${minutes%60?`${minutes%60}分`:''}`;}
function addDay(value:string){const d=new Date(`${value}T00:00:00.000Z`);d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10);}
function gapAfter(rows:StaffWorkContract[],index:number){const row=rows[index];if(row.voidedAt)return false;const next=rows.slice(index+1).find(item=>!item.voidedAt);return !!row.effectiveTo&&!!next&&addDay(row.effectiveTo)!==next.effectiveFrom;}
