import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common'; import { MonthlyShiftStatus, NotificationType, ShiftSwapStatus } from '@prisma/client'; import { shiftManagerRoles } from '../../domain/shifts/monthly-shift'; import type { AuthenticatedUser } from '../../infrastructure/auth/auth.types'; import { PrismaService } from '../../infrastructure/database/prisma.service'; import { AuditService } from '../audit/audit.service'; import { NotificationsService } from '../notifications/notifications.service'; import { CreateShiftSwapDto, UpdateShiftSwapDto } from './shift-swaps.dto';
const include={requester:{select:{id:true,displayName:true,email:true}},targetMember:{select:{id:true,displayName:true,email:true}}} as const;
@Injectable() export class ShiftSwapsService { constructor(private readonly prisma:PrismaService,private readonly notifications:NotificationsService,private readonly audit:AuditService){}
  list(user:AuthenticatedUser){const manager=shiftManagerRoles.includes(user.role as any);return this.prisma.shiftSwapRequest.findMany({where:{tenantId:user.tenantId,...(manager?{}:{OR:[{requesterId:user.sub},{targetMemberId:user.sub}]})},include,orderBy:{createdAt:'desc'}})}
  targets(user:AuthenticatedUser){return this.prisma.staff.findMany({where:{tenantId:user.tenantId,isActive:true,userId:{not:null},NOT:{userId:user.sub}},select:{userId:true,displayName:true,employeeNumber:true},orderBy:{employeeNumber:'asc'}})}
  async create(user:AuthenticatedUser,input:CreateShiftSwapDto){if(input.targetMemberId===user.sub)throw new BadRequestException('自分自身には交換申請できません。');const date=this.date(input.requestDate);const target=await this.prisma.membership.findFirst({where:{tenantId:user.tenantId,userId:input.targetMemberId,isActive:true}});if(!target)throw new NotFoundException('交換相手が見つかりません。');await this.requireConfirmedAssignments(user.tenantId,user.sub,input.targetMemberId,date);const row=await this.prisma.shiftSwapRequest.create({data:{tenantId:user.tenantId,requesterId:user.sub,targetMemberId:input.targetMemberId,requestDate:date,requestComment:input.requestComment?.trim()||null},include});await this.notifications.create(user.tenantId,input.targetMemberId,NotificationType.SHIFT_SWAP_REQUEST,'シフト交換申請',`${row.requester.displayName}さんから${input.requestDate}の交換申請があります。`);await this.notifications.notifyRoles(user.tenantId,['ADMIN','DIRECTOR'],NotificationType.SHIFT_SWAP_REQUEST,'シフト交換申請',`${row.requester.displayName}さんが交換申請を作成しました。`);await this.audit.create(user.tenantId,user.sub,'SHIFT_SWAP_CREATED','ShiftSwapRequest',row.id,{requestDate:input.requestDate,targetMemberId:input.targetMemberId});return row;}
  async update(user:AuthenticatedUser,id:string,input:UpdateShiftSwapDto){if(!shiftManagerRoles.includes(user.role as any))throw new ForbiddenException('交換申請を処理する権限がありません。');const current=await this.getTenant(user,id);if(current.status!==ShiftSwapStatus.PENDING)throw new ConflictException('処理済みの交換申請は変更できません。');let row; if(input.status==='APPROVED'){await this.swapAssignments(user.tenantId,current.requesterId,current.targetMemberId,current.requestDate);row=await this.prisma.shiftSwapRequest.update({where:{id},data:{status:ShiftSwapStatus.APPROVED,adminComment:input.adminComment?.trim()||null},include});}else row=await this.prisma.shiftSwapRequest.update({where:{id},data:{status:ShiftSwapStatus.REJECTED,adminComment:input.adminComment?.trim()||null},include});const type=input.status==='APPROVED'?NotificationType.SHIFT_SWAP_APPROVED:NotificationType.SHIFT_SWAP_REJECTED;const label=input.status==='APPROVED'?'承認':'却下';await Promise.all([this.notifications.create(user.tenantId,row.requesterId,type,'シフト交換申請',`${this.dateText(row.requestDate)}の交換申請が${label}されました。`),this.notifications.create(user.tenantId,row.targetMemberId,type,'シフト交換申請',`${this.dateText(row.requestDate)}の交換申請が${label}されました。`)]);await this.audit.create(user.tenantId,user.sub,`SHIFT_SWAP_${input.status}`,'ShiftSwapRequest',id,{requestDate:this.dateText(row.requestDate)});return row;}
  async cancel(user:AuthenticatedUser,id:string){const current=await this.getTenant(user,id);if(current.requesterId!==user.sub)throw new NotFoundException('交換申請が見つかりません。');if(current.status!==ShiftSwapStatus.PENDING)throw new ConflictException('処理済みの交換申請は取消できません。');const row=await this.prisma.shiftSwapRequest.update({where:{id},data:{status:ShiftSwapStatus.CANCELLED},include});await this.audit.create(user.tenantId,user.sub,'SHIFT_SWAP_CANCELLED','ShiftSwapRequest',id);return row;}
  private async getTenant(user:AuthenticatedUser,id:string){const row=await this.prisma.shiftSwapRequest.findFirst({where:{id,tenantId:user.tenantId},include});if(!row)throw new NotFoundException('交換申請が見つかりません。');return row}
  private async requireConfirmedAssignments(tenantId:string,requesterId:string,targetId:string,date:Date){const staff=await this.prisma.staff.findMany({where:{tenantId,userId:{in:[requesterId,targetId]},isActive:true},select:{id:true,userId:true}});if(staff.length!==2)throw new BadRequestException('両者の有効な職員情報が必要です。');const assignments=await this.prisma.shiftAssignment.findMany({where:{tenantId,workDate:date,staffId:{in:staff.map(x=>x.id)},monthlyShift:{status:MonthlyShiftStatus.CONFIRMED}}});if(assignments.length!==2)throw new BadRequestException('確定済みシフトが両者に必要です。');return assignments}
  private async swapAssignments(tenantId:string,requesterId:string,targetId:string,date:Date){const assignments=await this.requireConfirmedAssignments(tenantId,requesterId,targetId,date);const [a,b]=assignments;await this.prisma.$transaction([this.prisma.shiftAssignment.update({where:{id:a.id},data:{shiftType:b.shiftType,startTime:b.startTime,endTime:b.endTime,breakMinutes:b.breakMinutes,note:b.note,assignedClass:b.assignedClass}}),this.prisma.shiftAssignment.update({where:{id:b.id},data:{shiftType:a.shiftType,startTime:a.startTime,endTime:a.endTime,breakMinutes:a.breakMinutes,note:a.note,assignedClass:a.assignedClass}})]);}
  private date(value:string){const date=new Date(`${value}T00:00:00.000Z`);if(Number.isNaN(date.getTime())||date.toISOString().slice(0,10)!==value)throw new BadRequestException('requestDateが正しい日付ではありません。');return date} private dateText(value:Date){return value.toISOString().slice(0,10)} }
