import { useEffect, useState } from 'react';
import { api, type MusubiProvisionalReport, type Session } from '../../api/client';

export function MusubiProvisionalDemo({ session }: { session: Session }) {
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7));
  const [report, setReport] = useState<MusubiProvisionalReport | null>(null);
  const [message, setMessage] = useState('');
  useEffect(() => { let active = true; api.musubiProvisionalReport(session.accessToken, month).then((row) => { if (active) setReport(row); }).catch((error) => { if (active) setMessage(error instanceof Error ? error.message : '取得できませんでした。'); }); return () => { active = false; }; }, [session.accessToken, month]);
  if (!report) return <section className="mt-6">{message || '仮運用データを読み込んでいます…'}</section>;
  return <section className="mt-6 space-y-5">
    <div className="rounded-2xl border-2 border-amber-400 bg-amber-50 p-5 text-amber-950"><p className="font-black">仮運用・本番利用禁止</p><p className="mt-2 text-sm leading-6">{report.notice}</p><p className="mt-2 text-sm font-bold">{report.staffCountNotice}</p></div>
    <div className="flex flex-wrap items-end justify-between gap-3 print:hidden"><label className="text-sm font-bold">確認月<input className="input mt-1 block" type="month" value={month} onChange={(event) => setMonth(event.target.value)} /></label><button className="btn-secondary" type="button" onClick={() => window.print()}>この画面を印刷</button></div>
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-5">{[['報告総数', report.counts.reportedTotalStaffCount], ['確認済み', report.counts.representedStaffCount], ['未確認', report.counts.unconfirmedStaffCount], ['生成候補', report.counts.generatorCandidateCount], ['対象外', report.counts.generatorExcludedCount]].map(([label, value]) => <div className="card p-4" key={label}><p className="text-xs text-[var(--ink-muted)]">{label}</p><p className="mt-1 text-2xl font-black">{value}名</p></div>)}</div>
    <div className="card p-5"><h2 className="text-lg font-black">子育て支援担当</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{report.supportRules.map((row) => <article className="rounded-xl bg-[var(--canvas)] p-4" key={row.code}><p className="font-black">{row.code} <span className="text-sm">{row.time}</span></p><p className="mt-1 text-sm">{row.rule}</p></article>)}</div></div>
    <div className="card p-5"><h2 className="text-lg font-black">1か月の仮集計</h2><p className="mt-2 text-sm">生成状態: {report.schedule ? `${report.schedule.status}・割当${report.schedule.assignmentCount}件` : '未生成'}</p><p className="mt-1 text-sm">乳児グループ {report.groupAssignmentCounts.infant}件／幼児グループ {report.groupAssignmentCounts.child}件</p>{report.warnings.length ? <ul className="mt-3 space-y-2">{report.warnings.map((row) => <li className="rounded-xl bg-red-50 p-3 text-sm text-red-900" key={`${row.code}-${row.date}`}><strong>{row.level}</strong> {row.date} {row.message}</li>)}</ul> : <p className="mt-3 text-sm text-emerald-700">新人だけの遅出配置警告はありません。</p>}</div>
    <div className="card overflow-x-auto p-5"><h2 className="text-lg font-black">匿名職員23名</h2><table className="mt-3 min-w-full text-left text-sm"><thead><tr><th className="p-2">コード</th><th className="p-2">対象</th><th className="p-2">仮クラス</th><th className="p-2">仮経験</th><th className="p-2">早/通/遅/休</th></tr></thead><tbody>{report.staff.map((row) => <tr className="border-t border-[var(--border)]" key={row.code}><td className="p-2 font-bold">{row.code}</td><td className="p-2">{row.generatorEligible ? '候補' : '対象外'}</td><td className="p-2">{row.assignedClass}</td><td className="p-2">{row.experience ?? '未確認'}</td><td className="p-2">{row.shiftCounts.EARLY}/{row.shiftCounts.NORMAL}/{row.shiftCounts.LATE}/{row.shiftCounts.OFF}</td></tr>)}</tbody></table></div>
    <div className="card p-5"><h2 className="text-lg font-black">次回確認事項</h2><ul className="mt-3 list-disc space-y-1 pl-5 text-sm">{report.unresolvedItems.map((row) => <li key={row}>{row}</li>)}</ul></div>
  </section>;
}
