import { useState } from 'react';
import { api, type BackupValidation, type PrintShiftData, type Session } from '../../api/client';
import { MessageBanner } from '../../components/UiStates';
import { currentMonthKey } from '../shifts/month-utils.js';
import { adminPrintHtml, defaultAdminPrintOptions, openPrintWindow, personalCalendarPrintHtml, type PrintOptions } from './shift-print-layout';

const save = ({ blob, name }: { blob: Blob; name: string }) => { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); };
function print(data: PrintShiftData, classFilter = '', options = defaultAdminPrintOptions) { openPrintWindow(data.ownOnly ? personalCalendarPrintHtml(data) : adminPrintHtml(data, classFilter, options)); }

export function DataExportManagement({ session }: { session: Session }) {
  const [month, setMonth] = useState(currentMonthKey());
  const [classFilter, setClassFilter] = useState('AGE_0');
  const [printOptions, setPrintOptions] = useState<PrintOptions>(defaultAdminPrintOptions);
  const [message, setMessage] = useState(''); const [messageError, setMessageError] = useState(false);
  const [backup, setBackup] = useState<Record<string, unknown> | null>(null); const [validation, setValidation] = useState<BackupValidation | null>(null); const [preview, setPreview] = useState<any>(null);
  const busy = async (label: string, action: () => Promise<void>) => { setMessageError(false); setMessage(`${label}中…`); try { await action(); setMessage(`${label}が完了しました。`); } catch (error) { setMessageError(true); setMessage(error instanceof Error ? error.message : `${label}を完了できませんでした。時間をおいてもう一度お試しください。`); } };
  const readBackup = async (file: File) => { if (file.size > 10 * 1024 * 1024) throw new Error('バックアップファイルは10MB以下にしてください。'); const parsed = JSON.parse(await file.text()); if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) throw new Error('AeN Shiftのバックアップファイルを選択してください。'); setBackup(parsed as Record<string, unknown>); setValidation(null); setPreview(null); };
  return <section className="mt-6 space-y-5">
    <div className="card"><h3 className="font-bold">管理者用｜全職員シフト表</h3><p className="mt-2 text-sm text-slate-600">全体配置・人員確認用の月間一覧です。PDF保存はブラウザの印刷画面から行います。</p>
      <div className="mt-3 flex flex-wrap gap-2"><input aria-label="出力対象月" type="month" value={month} onChange={(event) => setMonth(event.target.value)} className="input max-w-48" /><select aria-label="印刷用紙" value={printOptions.paper} onChange={(event) => setPrintOptions({ ...printOptions, paper: event.target.value as PrintOptions['paper'] })} className="input max-w-32"><option value="A4">A4</option><option value="A3">A3</option><option value="B4">B4</option></select><select aria-label="印刷方向" value={printOptions.orientation} onChange={(event) => setPrintOptions({ ...printOptions, orientation: event.target.value as PrintOptions['orientation'] })} className="input max-w-32"><option value="portrait">縦</option><option value="landscape">横</option></select><button type="button" onClick={() => void busy('月間シフトCSV出力', async () => save(await api.downloadShiftCsv(session.accessToken, month)))} className="btn-primary">月間シフトCSV</button><button type="button" onClick={() => void busy('希望休CSV出力', async () => save(await api.downloadRequestsCsv(session.accessToken, month)))} className="btn-secondary">希望休CSV</button><button type="button" onClick={() => void busy('全職員シフト表表示', async () => print(await api.printShifts(session.accessToken, month), '', printOptions))} className="btn-secondary">全職員シフト表 印刷／PDF</button><button type="button" onClick={() => void busy('勤務カレンダー表示', async () => print(await api.printShifts(session.accessToken, month, true)))} className="btn-secondary">わたしの勤務カレンダー 印刷／PDF</button></div>
      <div className="mt-3 flex flex-wrap gap-2"><select aria-label="印刷対象クラス" value={classFilter} onChange={(event) => setClassFilter(event.target.value)} className="input max-w-48"><option value="AGE_0">0歳児</option><option value="AGE_1">1歳児</option><option value="AGE_2">2歳児</option><option value="AGE_3">3歳児</option><option value="AGE_4">4歳児</option><option value="AGE_5">5歳児</option><option value="FREE">フリー</option><option value="SUPPORT">補助</option></select><button type="button" onClick={() => void busy('クラス別印刷画面表示', async () => print(await api.printShifts(session.accessToken, month), classFilter, printOptions))} className="btn-secondary">クラス別 印刷／PDF</button></div>
    </div>
    <div className="card"><h3 className="font-bold">マスター・履歴CSV</h3><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={() => void busy('職員CSV出力', async () => save(await api.downloadStaffCsv(session.accessToken)))} className="btn-secondary">職員一覧CSV</button><button type="button" onClick={() => void busy('監査ログCSV出力', async () => save(await api.downloadAuditCsv(session.accessToken)))} className="btn-secondary">監査ログCSV</button></div></div>
    <div className="card"><h3 className="font-bold">バックアップ</h3><p className="mt-2 text-sm text-slate-600">バックアップには認証情報を含めません。読み込んだ内容は検証と復元プレビューだけを行い、現在のデータは変更しません。</p><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={() => void busy('バックアップ保存', async () => save(await api.exportBackup(session.accessToken)))} className="btn-primary">バックアップを保存</button><label className="btn-secondary">バックアップを読み込む<input className="sr-only" type="file" accept="application/json,.json" onChange={(event) => { const file = event.target.files?.[0]; if (file) void busy('バックアップ読み込み', () => readBackup(file)); }} /></label>{backup && <><button type="button" onClick={() => void busy('バックアップ検証', async () => setValidation(await api.validateBackup(session.accessToken, backup)))} className="btn-secondary">バックアップ検証</button><button type="button" onClick={() => void busy('復元プレビュー', async () => setPreview(await api.previewBackup(session.accessToken, backup)))} className="btn-secondary">復元プレビュー</button></>}</div>{validation && <div className="message-banner message-success mt-4"><strong>有効</strong>／version {validation.metadata.version}／{validation.metadata.tenantName}<pre className="mt-2 overflow-auto">{JSON.stringify(validation.counts, null, 2)}</pre></div>}{preview && <div className="message-banner message-warning mt-4"><strong>これは復元内容の確認画面です。現在のデータは変更されません。</strong><pre className="mt-2 overflow-auto">{JSON.stringify(preview.preview, null, 2)}</pre></div>}</div>
    {message && <MessageBanner kind={messageError ? 'error' : 'info'}>{message}</MessageBanner>}
  </section>;
}
