const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {chromium,webkit}=require('playwright');
(async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'aen-review-'));const root=path.resolve(__dirname,'..');
const source=`import React from 'react';import{createRoot}from'react-dom/client';import{ManagerResolutionCards}from'./src/features/manager-resolution/ManagerResolutionCards';
const reasons=['退勤時刻','半休の基礎勤務','半休の基礎勤務','行事との競合','希望欄の意味','長期休暇区分','長期休暇区分','行事と有給'];
const items=reasons.map((reason,i)=>({id:'test-'+i,groupId:'q-'+(i===6?5:i===7?6:i),revision:1,dates:['2026-09-14'],targetLabel:'匿名対象 '+(i+1),reason,knownConditions:['確認済み条件のみ表示'],impact:'対象セルの再評価が必要',status:'NEEDS_MANAGER_REVIEW',kind:i===0?'EARLY_DEPARTURE':'REQUEST_MEANING',options:[{value:i===0?'TIME':'CHECK',label:i===0?'退勤時刻を指定':'確認済み内容を回答'}]}));
window.calls=[];createRoot(document.getElementById('root')).render(<ManagerResolutionCards items={items} isAdmin={!location.hash.includes('staff')} onAnswer={async(id,revision,answer)=>{window.calls.push({id,revision,answer});}}/>);`;
const {build}=await import('vite'); const {default:react}=await import('@vitejs/plugin-react'); const entry=path.join(root,'review-fixture.tsx'); await build({configFile:false,root,define:{'process.env.NODE_ENV':'"production"'},plugins:[{name:'anonymous-fixture',resolveId:id=>id===entry?entry:null,load:id=>id===entry?source:null},react()],build:{outDir:dir,emptyOutDir:false,lib:{entry,name:'ReviewFixture',formats:['iife'],fileName:()=> 'app.js'}}});
for(const engine of [chromium,webkit]){const browser=await engine.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});page.on('pageerror',error=>console.error(error.message));await page.goto('about:blank');await page.setContent('<meta name="viewport" content="width=device-width,initial-scale=1"><main id="root"></main>');await page.addScriptTag({path:path.join(dir,'app.js')});await page.getByText('確認事項 7件',{exact:true}).waitFor();assert.equal(await page.locator('article').count(),8);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>390),false);const card=page.locator('article').first();await card.getByLabel('退勤時刻を指定').check();await card.getByLabel('退勤時刻',{exact:true}).fill('15:00');await card.getByRole('button',{name:'回答を保存'}).click();await card.getByText('回答保存済み・再評価待ち').waitFor();assert.equal(await page.evaluate(()=>window.calls.length),1);assert.equal(await card.locator('button').count(),0);
await page.goto('about:blank#staff');await page.setContent('<div id="root"></div>');await page.addScriptTag({path:path.join(dir,'app.js')});await page.waitForTimeout(50);assert.equal(await page.locator('article').count(),0);await browser.close();console.log(engine.name()+': 390px / seven groups / separate answers / save pending / staff hidden PASS');}
fs.rmSync(dir,{recursive:true});})().catch(e=>{console.error(e.message);process.exit(1)});
