const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {chromium,webkit}=require('playwright');
(async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'aen-submission-')),root=path.resolve(__dirname,'..'),entry=path.join(root,'submission-fixture.tsx');
 const source=`import React from 'react';import{createRoot}from'react-dom/client';import{MonthlySubmissionPanel}from'./src/features/manager-resolution/MonthlySubmissionPanel';import{api}from'./src/api/client';import{adminPrintHtml}from'./src/features/exports/shift-print-layout';
 let items=['REQUESTS','LEAVE','EVENTS','CLOSED_DATES'].map(category=>({category,state:'NOT_SUBMITTED',count:category==='EVENTS'?1:0,pending:0,revision:0,inputDigest:'a'.repeat(64),confirmedAt:null}));window.calls=[];window.ready=[];
 api.monthlySubmission=async()=>({month:'2026-10',items:structuredClone(items),hasUnsubmitted:items.some(i=>i.state==='NOT_SUBMITTED')});api.confirmMonthlySubmission=async(t,m,c,b)=>{window.calls.push({month:m,category:c,state:b.state});items=items.map(i=>i.category===c?{...i,state:b.state,revision:i.revision+1}:i);};
 window.printHtml=adminPrintHtml({tenantName:'Anonymous',month:'2026-10',status:'DRAFT',hasUnsubmitted:true,printedAt:'2026-10-02T00:00:00Z',assignments:[],closedDates:[],ownOnly:false});
 createRoot(document.getElementById('root')).render(<MonthlySubmissionPanel token="anonymous-test" month="2026-10" onReady={x=>window.ready.push(x)}/>);`;
 const{build}=await import('vite'),{default:react}=await import('@vitejs/plugin-react');await build({configFile:false,root,define:{'process.env.NODE_ENV':'"production"'},plugins:[{name:'fixture',resolveId:id=>id===entry?entry:null,load:id=>id===entry?source:null},react()],build:{outDir:dir,emptyOutDir:false,lib:{entry,name:'Fixture',formats:['iife'],fileName:()=> 'app.js'}}});
 for(const engine of[chromium,webkit]){const b=await engine.launch({headless:true});try{const page=await b.newPage({viewport:{width:390,height:844}});page.on('dialog',d=>d.accept());await page.setContent('<meta name="viewport" content="width=device-width,initial-scale=1"><main id="root"></main>');await page.addScriptTag({path:path.join(dir,'app.js')});await page.getByRole('heading',{name:'希望休：未提出'}).waitFor();assert.equal(await page.locator('article').count(),4);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>390),false);assert(await page.evaluate(()=>window.ready.at(-1)===false));const first=page.locator('article').first();await first.getByRole('button',{name:'今月はありません'}).click();await first.getByRole('heading',{name:'希望休：提出済み・該当0件'}).waitFor();assert.equal(await page.evaluate(()=>window.calls.length),1);assert.equal(await page.evaluate(()=>window.ready.at(-1)),false);await page.getByRole('button',{name:'登録内容を確認して提出'}).click();await page.getByRole('heading',{name:'行事：提出済み・入力あり'}).waitFor();while(await page.getByRole('button',{name:'今月はありません'}).count()){await page.getByRole('button',{name:'今月はありません'}).first().click();await page.waitForTimeout(50);}assert.equal(await page.evaluate(()=>window.ready.at(-1)),true);assert.equal(await page.evaluate(()=>window.calls.length),4);const html=await page.evaluate(()=>window.printHtml);assert(html.includes('仮シフト（DRAFT）'));assert(html.includes('未提出情報あり・未確定情報あり'));assert(!html.includes('確定済み'));console.log(engine.name()+':390px labels/explicit empty/data/one remaining/refusal readiness/print notice PASS');}finally{await b.close();}}
 fs.rmSync(dir,{recursive:true});})().catch(e=>{console.error(e.message);process.exitCode=1});
