import { useEffect, useState, type ReactNode } from 'react';
import { api, type WorkPattern, type WorkPatternInput } from '../../api/client';

const empty: WorkPatternInput = { code: '', name: '', shortName: '', displayOrder: 50, startTime: '09:00', endTime: '18:00', breakMinutes: 60, color: '#0f766e', isWorking: true, isDefault: false, isActive: true };

export function WorkPatternManagement({ token }: { token: string }) {
  const [rows, setRows] = useState<WorkPattern[]>([]); const [advanced, setAdvanced] = useState(false);
  const [editing, setEditing] = useState<WorkPattern | null | undefined>(undefined); const [input, setInput] = useState<WorkPatternInput>(empty); const [message, setMessage] = useState('');
  const load = () => Promise.all([api.workPatterns(token), api.features(token)]).then(([patterns, features]) => { setRows(patterns); setAdvanced(features.enabledFeatures.includes('ADVANCED_WORK_PATTERNS')); });
  useEffect(() => { void load().catch((error: Error) => setMessage(error.message)); }, [token]);
  const open = (row?: WorkPattern) => { setEditing(row ?? null); setInput(row ? { code: row.code, name: row.name, shortName: row.shortName, displayOrder: row.displayOrder, startTime: row.startTime, endTime: row.endTime, breakMinutes: row.breakMinutes, color: row.color, isWorking: row.isWorking, isDefault: row.isDefault, isActive: row.isActive } : empty); setMessage(''); };
  const save = async () => { try { if (editing) await api.updateWorkPattern(token, editing.id, input); else await api.createWorkPattern(token, input); setEditing(undefined); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : '保存できませんでした。'); } };
  const remove = async (row: WorkPattern) => { if (!window.confirm(`${row.name}を無効化しますか？`)) return; try { await api.deleteWorkPattern(token, row.id); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : '削除できませんでした。'); } };
  return <section className="space-y-4">
    <div className="card flex flex-wrap items-center justify-between gap-3 p-5"><div><h2 className="text-lg font-black">勤務パターン</h2><p className="mt-1 text-sm text-[var(--ink-muted)]">勤務区分の名称・時間・表示色を管理します。</p></div>{advanced ? <button className="btn-primary" onClick={() => open()}>勤務パターンを追加</button> : <p className="rounded-lg bg-amber-50 px-3 py-2 text-sm font-bold text-amber-900">現在のプランでは標準4パターンを利用できます。</p>}</div>
    {message && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm font-bold text-red-800">{message}</p>}
    <div className="grid gap-3 sm:grid-cols-2">{rows.map((row) => <article key={row.id} className="card p-5"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-xl font-black text-white" style={{ backgroundColor: row.color ?? '#64748b' }}>{row.shortName}</span><div><h3 className="font-black">{row.name}</h3><p className="text-xs text-[var(--ink-muted)]">{row.code}・{row.isSystem ? '標準' : '追加'}</p></div></div><span className={row.isActive ? 'status-chip status-ok' : 'status-chip'}>{row.isActive ? '有効' : '無効'}</span></div><p className="mt-4 text-sm font-bold">{row.isWorking ? `${row.startTime}〜${row.endTime}（休憩${row.breakMinutes}分）` : '勤務なし'}</p><div className="mt-4 flex gap-2"><button className="btn-quiet" onClick={() => open(row)}>編集</button>{advanced && !row.isSystem && <button className="btn-quiet text-red-700" onClick={() => void remove(row)}>削除</button>}</div></article>)}</div>
    {editing !== undefined && <div className="card p-5"><h3 className="text-lg font-black">{editing ? '勤務パターンを編集' : '勤務パターンを追加'}</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="コード"><input value={input.code} disabled={!!editing?.isSystem} onChange={(e) => setInput({ ...input, code: e.target.value.toUpperCase() })} /></Field><Field label="名称"><input value={input.name} onChange={(e) => setInput({ ...input, name: e.target.value })} /></Field><Field label="略称"><input value={input.shortName} onChange={(e) => setInput({ ...input, shortName: e.target.value })} /></Field><Field label="表示順"><input type="number" value={input.displayOrder} onChange={(e) => setInput({ ...input, displayOrder: Number(e.target.value) })} /></Field><Field label="開始"><input type="time" disabled={!input.isWorking} value={input.startTime ?? ''} onChange={(e) => setInput({ ...input, startTime: e.target.value || null })} /></Field><Field label="終了"><input type="time" disabled={!input.isWorking} value={input.endTime ?? ''} onChange={(e) => setInput({ ...input, endTime: e.target.value || null })} /></Field><Field label="休憩（分）"><input type="number" disabled={!input.isWorking} value={input.breakMinutes} onChange={(e) => setInput({ ...input, breakMinutes: Number(e.target.value) })} /></Field><Field label="色"><input type="color" value={input.color ?? '#64748b'} onChange={(e) => setInput({ ...input, color: e.target.value })} /></Field></div><label className="mt-4 flex gap-2"><input type="checkbox" checked={input.isWorking} onChange={(e) => setInput({ ...input, isWorking: e.target.checked, startTime: e.target.checked ? '09:00' : null, endTime: e.target.checked ? '18:00' : null, breakMinutes: e.target.checked ? 60 : 0 })} />勤務として扱う</label><label className="mt-2 flex gap-2"><input type="checkbox" checked={input.isDefault} onChange={(e) => setInput({ ...input, isDefault: e.target.checked })} />通常の既定パターン</label><div className="mt-5 flex gap-2"><button className="btn-primary" onClick={() => void save()}>保存</button><button className="btn-quiet" onClick={() => setEditing(undefined)}>キャンセル</button></div></div>}
  </section>;
}
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="grid gap-1 text-sm font-bold">{label}<span className="contents [&_input]:rounded-lg [&_input]:border [&_input]:p-2">{children}</span></label>; }
