const assert=require('node:assert/strict');
const {randomUUID,scryptSync}=require('node:crypto');
const {PrismaClient}=require('@prisma/client');
const {JwtService}=require('@nestjs/jwt');
const {resolveIsolatedDatabaseUrl,resolveLocalApiBaseUrl}=require('./helpers/isolated-database.cjs');
const prisma=new PrismaClient({datasourceUrl:resolveIsolatedDatabaseUrl()});const base=resolveLocalApiBaseUrl();const run=randomUUID().slice(0,8);const password=`Access-${run}!`;const created={tenantIds:[],userIds:[]};
const hash=value=>{const salt=randomUUID().replaceAll('-','');return `${salt}:${scryptSync(value,salt,64).toString('hex')}`};
async function call(path,init={},token){const response=await fetch(base+path,{...init,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})}});return{status:response.status,body:await response.json().catch(()=>null)}}
function assertSafeSwap(row,label){assert.deepEqual(Object.keys(row).sort(),['adminComment','createdAt','id','requestComment','requestDate','requester','requesterId','status','targetMember','targetMemberId'].sort(),`${label} root allow-list`);for(const key of ['requester','targetMember'])assert.deepEqual(Object.keys(row[key]).sort(),['displayName','id'],`${label} ${key} allow-list`);const serialized=JSON.stringify(row);for(const forbidden of ['email','passwordHash','tokenVersion','membershipTokenVersion','loginId','tenantId','role','isActive','memberships','updatedAt'])assert.equal(serialized.includes(`"${forbidden}"`),false,`${label} forbids ${forbidden}`)}
async function actor(tenantId,role,label,{active=true}={}){const user=await prisma.user.create({data:{loginId:`access.${label.toLowerCase()}.${run}`,email:`${label.toLowerCase()}.${run}@audit.invalid`,displayName:label,passwordHash:hash(password),isActive:active}});created.userIds.push(user.id);const membership=await prisma.membership.create({data:{tenantId,userId:user.id,role}});const login=active?await call('/auth/login',{method:'POST',body:JSON.stringify({loginId:user.loginId,password})}):null;if(active)assert.equal(login.status,200,JSON.stringify(login.body));return{user,membership,token:login?.body.accessToken??null}}
async function main(){
  const tenantA=await prisma.tenant.create({data:{name:`Access A ${run}`}});const tenantB=await prisma.tenant.create({data:{name:`Access B ${run}`}});created.tenantIds.push(tenantA.id,tenantB.id);for(const tenantId of created.tenantIds)await prisma.tenantSubscription.create({data:{tenantId,plan:'PROFESSIONAL',status:'ACTIVE'}});
  const adminA=await actor(tenantA.id,'ADMIN','adminA');const directorA=await actor(tenantA.id,'DIRECTOR','directorA');const chiefA=await actor(tenantA.id,'CHIEF','chiefA');const staffA=await actor(tenantA.id,'STAFF','staffA');const staffA2=await actor(tenantA.id,'STAFF','staffA2');const adminB=await actor(tenantB.id,'ADMIN','adminB');const staffB=await actor(tenantB.id,'STAFF','staffB');const inactive=await actor(tenantA.id,'STAFF','inactive',{active:false});
  const mkStaff=(tenantId,userId,code)=>prisma.staff.create({data:{tenantId,userId,employeeNumber:`${code}-${run}`,displayName:code,email:`private-${code}@audit.invalid`}});const [sa,sa2,sb]=await Promise.all([mkStaff(tenantA.id,staffA.user.id,'SA'),mkStaff(tenantA.id,staffA2.user.id,'SA2'),mkStaff(tenantB.id,staffB.user.id,'SB')]);
  const [scheduleA,scheduleB]=await Promise.all([prisma.monthlyShift.create({data:{tenantId:tenantA.id,targetMonth:new Date('2035-01-01Z'),status:'CONFIRMED',createdByUserId:adminA.user.id,confirmedByUserId:adminA.user.id,confirmedAt:new Date()}}),prisma.monthlyShift.create({data:{tenantId:tenantB.id,targetMonth:new Date('2035-01-01Z'),status:'DRAFT',createdByUserId:adminB.user.id}})]);
  await prisma.shiftAssignment.createMany({data:[{tenantId:tenantA.id,monthlyShiftId:scheduleA.id,staffId:sa.id,workDate:new Date('2035-01-10Z'),shiftType:'NORMAL',startTime:'08:30',endTime:'17:00',breakMinutes:60},{tenantId:tenantA.id,monthlyShiftId:scheduleA.id,staffId:sa2.id,workDate:new Date('2035-01-10Z'),shiftType:'NORMAL',startTime:'08:30',endTime:'17:00',breakMinutes:60},{tenantId:tenantB.id,monthlyShiftId:scheduleB.id,staffId:sb.id,workDate:new Date('2035-01-10Z'),shiftType:'NORMAL',startTime:'08:30',endTime:'17:00',breakMinutes:60}]});
  const [requestA2,requestB]=await Promise.all([prisma.shiftRequest.create({data:{tenantId:tenantA.id,staffId:sa2.id,requestDate:new Date('2035-01-12Z'),requestType:'DAY_OFF',reason:'A2 private reason'}}),prisma.shiftRequest.create({data:{tenantId:tenantB.id,staffId:sb.id,requestDate:new Date('2035-01-12Z'),requestType:'DAY_OFF',reason:'B private reason'}})]);
  const notificationB=await prisma.notification.create({data:{tenantId:tenantB.id,memberId:staffB.user.id,type:'SYSTEM',title:'B secret',message:'B only'}});const closedB=await prisma.tenantClosedDate.create({data:{tenantId:tenantB.id,closedDate:new Date('2035-01-15Z'),name:'B closed'}});const eventB=await prisma.tenantEvent.create({data:{tenantId:tenantB.id,eventDate:new Date('2035-01-16Z'),eventType:'OTHER',name:'B event',sourceType:'ADMIN_CONFIRMED'}});const exceptionB=await prisma.tenantRuleException.create({data:{tenantId:tenantB.id,exceptionDate:new Date('2035-01-17Z'),exceptionType:'WEEKLY_ROTATION_LIMIT',reason:'B exception',configuration:{maxWeeklyRotationCount:3},sourceType:'ADMIN_CONFIRMED',confirmedAt:new Date(),isActive:true}});
  const contractB=await prisma.staffWorkContract.create({data:{tenantId:tenantB.id,staffId:sb.id,effectiveFrom:new Date('2035-01-01Z'),annualizedTargetMinutes:100000,prescribedDailyMinutes:480}});const ruleB=await prisma.staffWorkRule.create({data:{tenantId:tenantB.id,staffId:sb.id,ruleType:'REQUIRED_DAY_OFF',dayOfWeek:0,isActive:true}});const attributeB=await prisma.staffAttributeDefinition.create({data:{tenantId:tenantB.id,code:`B_${run}`,name:'B attribute',category:'QUALIFICATION'}});const requirementB=await prisma.shiftStaffingRequirement.create({data:{tenantId:tenantB.id,code:`B_${run}`,name:'B required',attributeDefinitionId:attributeB.id,requiredCount:1,constraintLevel:'HARD',isActive:true}});
  const grantB=await prisma.paidLeaveGrant.create({data:{tenantId:tenantB.id,staffId:sb.id,grantDate:new Date('2034-04-01Z'),validFrom:new Date('2034-04-01Z'),expiresAt:new Date('2036-03-31Z'),grantedHalfDays:20,source:'INITIAL_BALANCE',createdByUserId:adminB.user.id}});const usageB=await prisma.paidLeaveUsage.create({data:{tenantId:tenantB.id,staffId:sb.id,usageDate:new Date('2035-01-20Z'),unit:'DAY',usedHalfDays:2,status:'CONFIRMED',confirmedByUserId:adminB.user.id,confirmedAt:new Date(),decisionNote:'B secret usage'}});await prisma.paidLeaveAllocation.create({data:{tenantId:tenantB.id,usageId:usageB.id,grantId:grantB.id,allocatedHalfDays:2}});
  const swap=await prisma.shiftSwapRequest.create({data:{tenantId:tenantA.id,requesterId:staffA.user.id,targetMemberId:staffA2.user.id,requestDate:new Date('2035-01-10Z'),requestComment:'private swap'}});

  const protectedPaths=['/staff','/shifts?month=2035-01','/requests?month=2035-01','/me/calendar?month=2035-01','/backups/export'];for(const path of protectedPaths)assert.equal((await call(path,{method:path==='/backups/export'?'POST':'GET'})).status,401,`unauth ${path}`);
  assert.equal((await call('/staff',{},'broken.jwt.value')).status,401);const jwt=new JwtService({secret:process.env.JWT_SECRET});const payload={sub:staffA.user.id,tenantId:tenantA.id,role:'STAFF',loginId:staffA.user.loginId,tokenVersion:staffA.user.tokenVersion,membershipTokenVersion:staffA.membership.tokenVersion};assert.equal((await call('/me',{},await jwt.signAsync(payload,{expiresIn:-10}))).status,401);assert.equal((await call('/me',{},await jwt.signAsync({...payload,sub:randomUUID()}))).status,401);assert.equal((await call('/staff',{},await jwt.signAsync({...payload,role:'ADMIN'}))).status,403,'JWT role改ざんをMembership照合で拒否');const inactiveToken=await jwt.signAsync({sub:inactive.user.id,tenantId:tenantA.id,role:'STAFF',loginId:inactive.user.loginId,tokenVersion:inactive.user.tokenVersion,membershipTokenVersion:inactive.membership.tokenVersion});assert.equal((await call('/me',{},inactiveToken)).status,401);
  const forbidden=[['POST','/staff'],['PATCH',`/staff/${sa.id}`],['DELETE',`/staff/${sa.id}`],['GET',`/staff/${sa.id}/work-contracts`],['GET',`/staff/${sa.id}/work-rules`],['GET','/staffing-requirements'],['POST','/tenant-calendar/events'],['GET',`/staff/${sa.id}/paid-leave/balance`],['POST','/shifts'],['POST',`/shifts/${scheduleA.id}/generate`],['POST',`/shifts/${scheduleA.id}/confirm`],['POST','/backups/export'],['PATCH','/settings/shifts']];for(const who of [staffA,chiefA])for(const [method,path] of forbidden){const result=await call(path,{method,body:method==='GET'||method==='DELETE'?undefined:'{}'},who.token);assert.equal(result.status,403,`${who.user.displayName} ${method} ${path}`)}
  assert.equal((await call('/staff',{},directorA.token)).status,200);assert.equal((await call(`/staff/${sa.id}/work-contracts`,{},directorA.token)).status,200);assert.equal((await call('/backups/export',{method:'POST'},directorA.token)).status,201);
  const cross=[['GET',`/staff/${sb.id}`],['PATCH',`/staff/${sb.id}`],['DELETE',`/staff/${sb.id}`],['GET',`/shifts/${scheduleB.id}`],['POST',`/shifts/${scheduleB.id}/confirm`],['GET',`/requests/${requestB.id}`],['DELETE',`/requests/${requestB.id}`],['GET',`/staff/${sb.id}/work-contracts`],['POST',`/staff/${sa.id}/work-contracts/${contractB.id}/void`],['GET',`/staff/${sb.id}/work-rules`],['DELETE',`/staff/${sa.id}/work-rules/${ruleB.id}`],['DELETE',`/closed-dates/${closedB.id}`],['DELETE',`/tenant-calendar/events/${eventB.id}`],['DELETE',`/tenant-calendar/rule-exceptions/${exceptionB.id}`],['DELETE',`/staffing-requirements/${requirementB.id}`],['GET',`/staff/${sb.id}/paid-leave/balance`],['POST',`/staff/${sa.id}/paid-leave/usages/${usageB.id}/cancel`]];for(const [method,path] of cross){const result=await call(path,{method,body:method==='GET'||method==='DELETE'?undefined:JSON.stringify({reason:'cross'})},adminA.token);assert.ok([400,404].includes(result.status),`cross ${method} ${path} returned ${result.status}`)}
  assert.equal((await call(`/notifications/${notificationB.id}/read`,{method:'PATCH'},staffA.token)).status,404);assert.equal((await call(`/requests?month=2035-01&staffId=${sa2.id}`,{},staffA.token)).status,403);assert.equal((await call(`/requests/${requestA2.id}`,{},staffA.token)).status,404);assert.equal((await call(`/shifts?month=2035-01&staffId=${sa2.id}`,{},staffA.token)).status,403);
  const mass=await call('/requests',{method:'POST',body:JSON.stringify({requestDate:'2035-01-22',requestType:'DAY_OFF',reason:'mass',staffId:sa.id,tenantId:tenantB.id,status:'APPROVED',role:'ADMIN',isActive:false})},staffA.token);assert.equal(mass.status,201,JSON.stringify(mass.body));const massRow=await prisma.shiftRequest.findUniqueOrThrow({where:{id:mass.body.id}});assert.equal(massRow.tenantId,tenantA.id);assert.equal(massRow.staffId,sa.id);assert.equal(massRow.status,'PENDING');
  const swapList=await call('/shift-swaps',{},staffA.token);assert.equal(swapList.status,200);assertSafeSwap(swapList.body.find(row=>row.id===swap.id),'GET /shift-swaps');
  const createdSwap=await call('/shift-swaps',{method:'POST',body:JSON.stringify({targetMemberId:staffA2.user.id,requestDate:'2035-01-10',requestComment:'schema create'})},staffA.token);assert.equal(createdSwap.status,201,JSON.stringify(createdSwap.body));assertSafeSwap(createdSwap.body,'POST /shift-swaps');
  const updatedSwap=await call(`/shift-swaps/${createdSwap.body.id}`,{method:'PATCH',body:JSON.stringify({status:'APPROVED',adminComment:'schema update'})},adminA.token);assert.equal(updatedSwap.status,200,JSON.stringify(updatedSwap.body));assertSafeSwap(updatedSwap.body,'PATCH /shift-swaps/:id');
  const cancelSource=await call('/shift-swaps',{method:'POST',body:JSON.stringify({targetMemberId:staffA2.user.id,requestDate:'2035-01-10',requestComment:'schema cancel'})},staffA.token);assert.equal(cancelSource.status,201);const cancelledSwap=await call(`/shift-swaps/${cancelSource.body.id}`,{method:'DELETE'},staffA.token);assert.equal(cancelledSwap.status,200,JSON.stringify(cancelledSwap.body));assertSafeSwap(cancelledSwap.body,'DELETE /shift-swaps/:id');
  const targets=await call('/shift-swaps/targets',{},staffA.token);assert.equal(targets.status,200);assert.ok(targets.body.some(row=>row.userId===staffA2.user.id));for(const row of targets.body){assert.deepEqual(Object.keys(row).sort(),['displayName','employeeNumber','userId']);assert.equal(JSON.stringify(row).includes('email'),false)}
  console.log(JSON.stringify({result:'AUDIT_COMPLETE',unauthenticated:'PASS',roleEscalation:'PASS',tenantCrossing:'PASS',idor:'PASS',massAssignment:'PASS',ownScope:'PASS',overResponse:'PASS',shiftSwapProjection:{list:'PASS',create:'PASS',update:'PASS',cancel:'PASS',targets:'PASS'}},null,2));
}
main().finally(async()=>{for(const tenantId of created.tenantIds)await prisma.tenant.delete({where:{id:tenantId}}).catch(()=>undefined);if(created.userIds.length)await prisma.user.deleteMany({where:{id:{in:created.userIds}}}).catch(()=>undefined);await prisma.$disconnect()}).catch(error=>{console.error(error);process.exitCode=1});
