const assert = require('node:assert/strict');
const { adaptFormalPackage, contract } = require('../scripts/lib/formal-package-adapter.cjs');
const { anonymousFormalPackage } = require('./helpers/anonymous-formal-package.cjs');
const adapt = input => adaptFormalPackage(input, { adminEmployeeNumber: 'S001' });
const result = adapt(anonymousFormalPackage());
assert.equal(result.productionUseApproved, false);
assert.equal(result.isolatedValidationOnly, true);
assert.equal(result.staff.length, 23);
assert.deepEqual(['CHILDCARE','CHILDCARE_SUPPORT','FOOD_SERVICE'].map(code => result.staff.filter(row => row.departmentCode === code).length), [18,2,3]);
assert.equal(result.staff.filter(row => row.generatorEligible).length, 20);
assert.equal(result.staff.find(row => row.employeeNumber === 'S016').canWorkSaturdays, false);
assert.equal(result.staff.find(row => row.employeeNumber === 'S016').regularWorkEndTime, '16:40');
assert.equal(Object.values(contract.staff).flatMap(row => Object.values(row)).filter(cell => cell.requiredClass === 'REQUIRED_FOR_GENERATION').length, 457);
let negatives = 0;
function rejects(mutate) { const input = anonymousFormalPackage(); mutate(input); assert.throws(() => adapt(input), /SYSTEM_SAFETY_BLOCK:FORMAL_PACKAGE/); negatives++; }
rejects(p => { p.staff[1].employeeNumber = 'S001'; });
rejects(p => { delete p.staff[0].provenance.canWorkEarly; });
rejects(p => { p.staff[15].canWorkSaturdays = true; });
rejects(p => { p.staff[15].regularWorkEndTime = '16:30'; });
rejects(p => { p.staff[20].generatorEligible = true; });
rejects(p => { p.staff[20].canWorkEarly = true; });
rejects(p => { p.workPatterns.find(row => row.value[0] === 'P05').value[2] = '10:30'; });
rejects(p => { p.workPatterns.find(row => row.value[0] === 'P09').provenance.approvalStatus = 'APPROVED'; });
rejects(p => { p.provisionalValues[1].provenance.approvalStatus = 'APPROVED'; });
rejects(p => { p.staff[0].provenance.canWorkSaturdays.approvalAuthority = 'RECORDED_ADMIN_ANSWER'; });
rejects(p => { p.individualContracts.push({ value: { annualizedTargetMinutes: 390 * 260 }, provenance: p.workPatterns[0].provenance }); });
rejects(p => { p.staff[0].monthlyTargetWorkHours = 0; });
rejects(p => { p.tenantIdentity.environment = 'PRODUCTION'; });
rejects(p => { p.sourceRegistryReferences.find(row => row.sourceId === 'MUSUBI-2026-039').sha256 = '0'.repeat(64); });
console.log(`Formal adapter PASS: 23 staff, 457 required matrix fields, ${negatives} negative cases, no DB writes`);
