const {test}=require('node:test');const assert=require('node:assert/strict');
const path=require('node:path');const fs=require('node:fs');
const ts=require('typescript');
require.extensions['.ts']=(module,file)=>module._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,file);
const core=require('../src/application/manager-resolution/resolution.ts');const {saveManagerAnswer}=require('../src/application/manager-resolution/resolution-store.ts');
const actor={tenantId:'tenant-test',userId:'admin-test',role:'ADMIN'};
const base=()=>({id:'item-1',groupId:'question-1',tenantId:actor.tenantId,month:'2026-09',dates:['2026-09-14'],staffIds:['anonymous-1'],kind:'EARLY_DEPARTURE',reason:'退勤時刻未確定',knownConditions:[],impact:'対象セルを確定しない',options:['TIME'],sourceReferences:['TEST:MONTHLY'],status:'NEEDS_MANAGER_REVIEW',revision:1});
function memory(initial,failAudit=false){let data=structuredClone(initial),audit=[];return{read:()=>structuredClone(data),events:()=>audit,transaction:async run=>{let pending=structuredClone(data),events=[];const result=await run({load:async(t,id)=>pending.tenantId===t&&pending.id===id?pending:null,compareAndSet:async(prev,next)=>{if(data.revision!==prev.revision)return false;pending=next;return true},audit:async event=>{if(failAudit)throw Error('AUDIT_FAILED');events.push(event)}});data=pending;audit.push(...events);return result}};}
test('answer is captured without claiming condition applied or resolved',async()=>{const store=memory(base());const item=await saveManagerAnswer(store,actor,'item-1',1,{option:'TIME',time:'15:00'},'2026-10-01T00:00:00Z');assert.equal(item.status,'ANSWERED_PENDING_REEVALUATION');assert.equal(store.events().length,1);assert.equal(item.answeredBy,actor.userId);assert.throws(()=>core.assertFinalAllowed([item],actor.tenantId,item.month,0),/FINAL_BLOCKED/);});
test('tenant boundary and ordinary staff denied, no writes',async()=>{for(const user of [{...actor,tenantId:'other'}, {...actor,role:'STAFF'}]){const store=memory(base());await assert.rejects(()=>saveManagerAnswer(store,user,'item-1',1,{option:'TIME',time:'15:00'},new Date().toISOString()));assert.equal(store.read().revision,1);assert.equal(store.events().length,0);}});
test('duplicate and stale submission do not append audit',async()=>{const store=memory(base());await saveManagerAnswer(store,actor,'item-1',1,{option:'TIME',time:'15:00'},new Date().toISOString());await assert.rejects(()=>saveManagerAnswer(store,actor,'item-1',1,{option:'TIME',time:'15:00'},new Date().toISOString()));assert.equal(store.events().length,1);});
test('audit failure rolls back answer in transaction contract',async()=>{const store=memory(base(),true);await assert.rejects(()=>saveManagerAnswer(store,actor,'item-1',1,{option:'TIME',time:'15:00'},new Date().toISOString()));assert.equal(store.read().revision,1);assert.equal(store.events().length,0);});
test('unsafe answer, missing half-day base, unavailable option rejected',()=>{const i=base();for(const a of [{option:'TIME',time:'25:00'},{option:'TIME',time:'15:00',secret:'not-a-secret'},{option:'UNKNOWN'}])assert.throws(()=>core.submitAnswer(i,actor,1,a,new Date().toISOString()));const half={...i,kind:'HALF_DAY_BASE',options:['NORMAL','OTHER_TIME']};assert.throws(()=>core.submitAnswer(half,actor,1,{option:'P09'},new Date().toISOString()));assert.throws(()=>core.submitAnswer(half,actor,1,{option:'OTHER_TIME',startTime:'17:00',endTime:'08:30'},new Date().toISOString()));});
test('open cells are excluded before generation; unaffected cells remain eligible',()=>{const input=[base(),{...base(),id:'item-2',dates:['2026-09-24','2026-09-29'],kind:'HALF_DAY_BASE'}];const before=JSON.stringify(input);const scope=core.draftScope(input,actor.tenantId,'2026-09');assert.equal(scope.blockedCells.length,3);assert(!scope.blockedCells.includes(JSON.stringify(['anonymous-2','2026-09-14'])));assert.equal(scope.canFinalize,false);assert.equal(JSON.stringify(input),before);assert.throws(()=>core.draftScope(input,'other','2026-09'));});
test('HARD remains blocking independently of review resolution',()=>{const item={...base(),status:'RESOLVED'};assert.throws(()=>core.assertFinalAllowed([item],actor.tenantId,item.month,1));core.assertFinalAllowed([item],actor.tenantId,item.month,0);assert.throws(()=>core.assertFinalAllowed([item],actor.tenantId,item.month,NaN));});
test('invalid and out-of-month dates rejected',()=>{for(const date of ['2026-09-31','2026-10-01'])assert.throws(()=>core.validateItem({...base(),dates:[date]}));});
