'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {randomUUID}=require('node:crypto'),{spawnSync,spawn}=require('node:child_process');
require('./helpers/isolated-database.cjs').resolveIsolatedDatabaseUrl();
const {PrismaClient}=require('@prisma/client');
const {ManagerResolutionService}=require('../dist/presentation/shifts/manager-resolution.service');
const {MonthlyGenerationContextBuilder}=require('../dist/application/shifts/monthly-generation-context-builder');
const {ShiftsService}=require('../dist/presentation/shifts/shifts.service');
const {SettingsService}=require('../dist/presentation/settings/settings.service');
const {WorkPatternsService}=require('../dist/presentation/work-patterns/work-patterns.service');
const {FeaturesService}=require('../dist/presentation/features/features.service');
const {SubscriptionsService}=require('../dist/presentation/subscriptions/subscriptions.service');
const {AuditService}=require('../dist/presentation/audit/audit.service');
const {draftScope}=require('../dist/application/manager-resolution/resolution');
const p=new PrismaClient();let phase='start';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'aen-anonymous-db-'));fs.chmodSync(dir,0o700);
const day=s=>new Date(s+'T00:00:00Z'),ref={sourceReferences:['TEST-SOURCE'],manifestDigest:'a'.repeat(64)};
function file(name,value){const f=path.join(dir,name+'.json');fs.writeFileSync(f,JSON.stringify(value),{mode:0o600});return f;}
function cli(script,args,pass=true){const r=spawnSync(process.execPath,[path.join(__dirname,'../scripts',script),...args],{env:process.env,encoding:'utf8'});assert.equal(r.status===0,pass,script+' status');return r;}
function concurrentCLI(script,args){return new Promise(resolve=>{const c=spawn(process.execPath,[path.join(__dirname,'../scripts',script),...args],{env:process.env,stdio:'ignore'});c.on('exit',resolve);});}
async function snap(id){const out={};for(const n of ['tenant','staff','workPattern','tenantEvent','shiftRequest','staffWorkRule','tenantRuleException','monthlyShift','shiftAssignment','auditLog'])out[n]=await p[n].findMany({where:n==='tenant'?{id}:{tenantId:id},orderBy:{id:'asc'}});return JSON.stringify(out);}
async function main(){
 phase='fixture';const t=await p.tenant.create({data:{name:'Anonymous integration '+randomUUID()}}),other=await p.tenant.create({data:{name:'Anonymous sentinel '+randomUUID()}});
 const u=await p.user.create({data:{displayName:'Anonymous admin',passwordHash:'DISABLED_TEST_ACCOUNT'}});await p.membership.create({data:{tenantId:t.id,userId:u.id,role:'ADMIN'}});
 const staff=[];for(let i=1;i<=23;i++)staff.push(await p.staff.create({data:{tenantId:t.id,employeeNumber:'TEST'+i,displayName:'Anonymous '+i}}));
 await p.staff.create({data:{tenantId:other.id,employeeNumber:'FOREIGN',displayName:'Anonymous sentinel'}});
 const actor={tenantId:t.id,sub:u.id,role:'ADMIN'},audit=new AuditService(p),notify={notifyRoles:async()=>{},notifyTenant:async()=>{}};
 const features=new FeaturesService(p,new SubscriptionsService(p,audit,notify),audit);
 for(const featureCode of ['STAFF_WORK_RULES','TENANT_CUSTOM_RULES','ADVANCED_STAFFING_REQUIREMENTS'])await p.tenantFeature.create({data:{tenantId:t.id,featureCode,enabled:true,source:'MANUAL',configuration:featureCode==='TENANT_CUSTOM_RULES'?{fillOpenUnassignedWithNormal:true}:{}}});
 const patterns=new WorkPatternsService(p,features,audit);await patterns.ensureSystemPatterns(t.id);
 await p.tenantShiftSetting.create({data:{tenantId:t.id,weekdayEarlyRequired:0,weekdayLateRequired:0,saturdayEarlyRequired:0,saturdayLateRequired:0,saturdayMinimumStaff:0,maxConsecutiveWorkDays:6}});
 for(const classType of ['AGE_0','AGE_1','AGE_2','AGE_3','AGE_4','AGE_5'])await p.classStaffingRequirement.create({data:{tenantId:t.id,classType,weekdayRequired:0,saturdayRequired:0}});
 const ctx=new MonthlyGenerationContextBuilder(p,features),reviews=new ManagerResolutionService(p,ctx),settings=new SettingsService(p,audit),shifts=new ShiftsService(p,settings,notify,audit,patterns,features,ctx,reviews);
 const schedule=await shifts.create(actor,'2026-09'),sentinel=await snap(other.id);
 const kinds=['EARLY_DEPARTURE','HALF_DAY_BASE','HALF_DAY_BASE','EVENT_CONFLICT','REQUEST_MEANING','LEAVE_CATEGORY','EVENT_CONFLICT'],dates=['2026-09-14','2026-09-24','2026-09-29','2026-09-24','2026-09-03','2026-09-08','2026-09-16'];
 const manifest={schemaVersion:1,packageType:'MONTHLY_MANAGER_REVIEW',month:'2026-09',items:kinds.map((kind,i)=>({key:'question-'+i,groupId:'group-'+i,kind,dates:[dates[i]],staffCodes:['TEST'+(i+1)],reason:'Anonymous clarification',knownConditions:['Anonymous condition'],impact:'Review date',...ref,optionEffects:i===3?{KEEP:[{type:'KEEP_CONDITIONS'}]}:i===6?{ATTEND:[{type:'CANCEL_REQUEST',requestType:'PAID_LEAVE'},{type:'PATTERN',code:'NORMAL'}]}:kind==='EARLY_DEPARTURE'?{TIME:[{type:'TIME',basePatternCode:'NORMAL',startTime:'08:30',endTime:'17:00'}]}:kind==='LEAVE_CATEGORY'?{OFF:[{type:'NO_WORK'}]}:{NORMAL:[{type:'PATTERN',code:'NORMAL'}]}}))};
 await p.shiftRequest.create({data:{tenantId:t.id,staffId:staff[6].id,requestDate:day(dates[6]),requestType:'PAID_LEAVE',status:'APPROVED',adminComment:JSON.stringify(ref)}});
 const args=['--manifest',file('review',manifest),'--tenant-id',t.id];
 phase='review CLI';let before=await snap(t.id);cli('import-manager-review-manifest.cjs',args);assert.equal(await snap(t.id),before);cli('import-manager-review-manifest.cjs',[...args,'--apply']);const items=await reviews.rows(t.id,'2026-09');assert.equal(items.length,7);assert(items.every(i=>i.status==='NEEDS_MANAGER_REVIEW'));assert.equal(draftScope(items,t.id,'2026-09').blockedCells.length,7);
 before=await snap(t.id);cli('import-manager-review-manifest.cjs',[...args,'--apply']);assert.equal(await snap(t.id),before);assert.equal(await p.tenantRuleException.count({where:{tenantId:t.id,sourceType:'MONTHLY_PACKAGE'}}),7);
 const duplicate=structuredClone(manifest);duplicate.items[0].key='insert-before-fail';duplicate.items[1].reason='conflicting existing';cli('import-manager-review-manifest.cjs',['--manifest',file('rollback',duplicate),'--tenant-id',t.id,'--apply'],false);assert.equal(await snap(t.id),before,'partial CLI rollback');
 const foreign=structuredClone(manifest);foreign.items[0].staffCodes=['FOREIGN'];cli('import-manager-review-manifest.cjs',['--manifest',file('foreign',foreign),'--tenant-id',t.id,'--apply'],false);assert.equal(await snap(t.id),before);
 const codes=await Promise.all([concurrentCLI('import-manager-review-manifest.cjs',[...args,'--apply']),concurrentCLI('import-manager-review-manifest.cjs',[...args,'--apply'])]);assert(codes.some(c=>c===0));assert.equal(await snap(t.id),before);
 phase='monthly CLI';const monthly={schemaVersion:1,packageType:'MONTHLY_APPROVED_INPUT',month:'2026-09',events:[{date:'2026-09-25',name:'Anonymous event',eventType:'ONSITE',targetStaffCodes:['TEST20'],targetClasses:[],allowedWorkPatternCodes:['NORMAL'],fixedTimeStaffAllowed:false,...ref}],requests:[{date:'2026-09-10',staffCode:'TEST21',requestType:'HALF_DAY_PM',baseWorkPatternCode:'NORMAL',startTime:'08:30',endTime:'17:00',...ref}],dateFixedRules:[{date:'2026-09-11',staffCode:'TEST22',patternCode:'NORMAL',startTime:'08:30',endTime:'15:00',...ref}]};
 const ma=['--manifest',file('monthly',monthly),'--tenant-id',t.id];before=await snap(t.id);cli('import-monthly-input-manifest.cjs',ma);assert.equal(await snap(t.id),before);cli('import-monthly-input-manifest.cjs',[...ma,'--apply']);before=await snap(t.id);cli('import-monthly-input-manifest.cjs',[...ma,'--apply']);assert.equal(await snap(t.id),before);
 const ev=await p.tenantEvent.findFirst({where:{tenantId:t.id}});assert.deepEqual(ev.targetStaffCodes,['TEST20']);assert.deepEqual(ev.allowedWorkPatternCodes,['NORMAL']);assert.equal(ev.fixedTimeStaffAllowed,false);assert(JSON.parse(ev.sourceReference).references.includes('TEST-SOURCE'));
 const early=await p.staffWorkRule.findFirst({where:{tenantId:t.id,staffId:staff[21].id}});assert.equal(early.endTime,'15:00');const half=await p.staffWorkRule.findFirst({where:{tenantId:t.id,staffId:staff[20].id}});assert.equal(half.startTime,'08:30');assert.equal(half.endTime,'17:00');assert((await p.shiftRequest.findFirst({where:{tenantId:t.id}})).adminComment.includes('TEST-SOURCE'));
 const fail=structuredClone(monthly);fail.events[0].name='Rollback event';fail.managerReviews=[{...manifest.items[0],key:'rollback-open'}];fail.closedDates=[{date:'2026-09-23',name:'Anonymous closure',...ref}];fail.requests[0].staffCode='FOREIGN';cli('import-monthly-input-manifest.cjs',['--manifest',file('monthly-fail',fail),'--tenant-id',t.id,'--apply'],false);assert.equal(await snap(t.id),before);
 for(const index of [1,2])await p.shiftRequest.create({data:{tenantId:t.id,staffId:staff[index].id,requestDate:day(dates[index]),requestType:'HALF_DAY_PM',status:'APPROVED',adminComment:JSON.stringify(ref)}});
 phase='open draft';await shifts.generate(actor,schedule.id);for(const i of items)assert.equal(await p.shiftAssignment.count({where:{monthlyShiftId:schedule.id,staffId:i.staffIds[0],workDate:day(i.dates[0])}}),0);assert((await p.shiftAssignment.count({where:{monthlyShiftId:schedule.id,shiftType:'NORMAL'}}))>0);await assert.rejects(()=>shifts.confirm(actor,schedule.id));assert.equal((await p.monthlyShift.findUnique({where:{id:schedule.id}})).status,'DRAFT');
 phase='authorization';await assert.rejects(()=>reviews.list({...actor,role:'STAFF'},'2026-09'),e=>e.getStatus()===403);await assert.rejects(()=>reviews.detail({...actor,tenantId:other.id},'2026-09',items[0].id),e=>e.getStatus()===404);
 const first=items.find(i=>i.kind==='EARLY_DEPARTURE');before=await snap(t.id);await assert.rejects(()=>reviews.answer(actor,'2026-09',first.id,1,{option:'TIME',time:'25:00'}));assert.equal(await snap(t.id),before);
 phase='audit rollback';await assert.rejects(()=>reviews.answer({...actor,sub:randomUUID()},'2026-09',first.id,1,{option:'TIME',time:'15:00'}));assert.equal(await snap(t.id),before,'audit FK failure rolls answer back');
 phase='concurrent answers';const results=await Promise.allSettled([reviews.answer(actor,'2026-09',first.id,1,{option:'TIME',time:'15:00'}),reviews.answer(actor,'2026-09',first.id,1,{option:'TIME',time:'16:00'})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(await p.auditLog.count({where:{tenantId:t.id,action:'MONTHLY_MANAGER_ANSWERED',targetId:first.id}}),1);const row=await p.tenantRuleException.findUnique({where:{id:first.id}});assert.equal(row.configuration.status,'ANSWERED_PENDING_REEVALUATION');assert.equal(row.version,2);
 before=await snap(t.id);await assert.rejects(()=>reviews.answer(actor,'2026-09',first.id,1,{option:'TIME',time:'15:00'}));assert.equal(await snap(t.id),before);
 phase='reevaluate';await reviews.reevaluate(actor,'2026-09',first.id,2);assert.equal((await p.tenantRuleException.findUnique({where:{id:first.id}})).configuration.status,'RESOLVED');for(const i of items.filter(i=>i.id!==first.id)){await reviews.answer(actor,'2026-09',i.id,1,{option:i.options[0]});await reviews.reevaluate(actor,'2026-09',i.id,2);}
 assert((await reviews.rows(t.id,'2026-09')).every(i=>i.status==='RESOLVED'));assert.equal(await p.auditLog.count({where:{tenantId:t.id,action:'MONTHLY_MANAGER_ANSWERED'}}),7);assert.equal(await p.auditLog.count({where:{tenantId:t.id,action:'MONTHLY_MANAGER_REEVALUATED'}}),7);assert((await p.auditLog.findMany({where:{tenantId:t.id,action:'MONTHLY_MANAGER_ANSWERED'}})).every(a=>a.detail.sourceType==='MANAGER_CONFIRMED'&&a.detail.sourceReferences[0]==='TEST-SOURCE'));
 before=await snap(t.id);cli('import-manager-review-manifest.cjs',[...args,'--apply'],false);assert.equal(await snap(t.id),before,'reimport never resets answered records');
 phase='stale FINAL';await assert.rejects(()=>shifts.confirm(actor,schedule.id));await shifts.generate(actor,schedule.id);
 // Real DB validation/locks; intercept only the final write so CONFIRMED is never persisted.
 const finalReached=new Error('FINAL_GATE_REACHED_NO_WRITE');let reached=0;const guarded=new Proxy(p,{get(target,key){if(key==='$transaction')return (fn,opts)=>target.$transaction(tx=>fn(new Proxy(tx,{get(db,k){if(k==='monthlyShift')return new Proxy(db.monthlyShift,{get(model,m){if(m==='update')return args=>{if(args.data.status==='CONFIRMED'){reached++;throw finalReached;}return model.update(args);};return model[m];}});return db[k];}})),opts);return target[key];}});
 const check=new ShiftsService(guarded,settings,notify,audit,patterns,features,ctx,reviews);phase='resolved FINAL gate';await assert.rejects(()=>check.confirm(actor,schedule.id),e=>e===finalReached);assert.equal(reached,1);assert.equal((await p.monthlyShift.findUnique({where:{id:schedule.id}})).status,'DRAFT');
 phase='HARD FINAL';await p.tenantEvent.update({where:{id:ev.id},data:{allowedWorkPatternCodes:['EARLY']}});await assert.rejects(()=>check.confirm(actor,schedule.id),e=>e!==finalReached);assert.equal(reached,1);await p.tenantEvent.update({where:{id:ev.id},data:{allowedWorkPatternCodes:['NORMAL']}});
 phase='digest FINAL';const last=await p.auditLog.findFirst({where:{tenantId:t.id,action:'MANAGER_REVIEW_DRAFT_EVALUATED'},orderBy:{createdAt:'desc'}});await p.auditLog.update({where:{id:last.id},data:{detail:{...last.detail,reviewDigest:'stale-test'}}});await assert.rejects(()=>check.confirm(actor,schedule.id),e=>e!==finalReached);assert.equal(reached,1);assert.equal(await snap(other.id),sentinel);assert.equal(await p.staff.count({where:{tenantId:t.id}}),23);assert.equal(await p.monthlyShift.count({where:{tenantId:t.id,status:'CONFIRMED'}}),0);
 console.log('PASS: real PostgreSQL CLI/readback/provenance/idempotency/rollback/concurrency/Tenant/23 anonymous staff/answer/Audit/reevaluation/unknown-cell exclusion/FINAL guards; no FINAL written');
}
main().catch(e=>{console.error('DB_E2E_HOLD phase='+phase+' code='+(e.code||e.name));if(e.getResponse){const r=e.getResponse();console.error(JSON.stringify({diagnosticCodes:r.diagnostics?.map(d=>d.code),warningCodes:r.warnings?.map(w=>w.code)}));}console.error(e.stack?.split('\n').filter(l=>l.trim().startsWith('at ')).slice(0,2).join('\n'));process.exitCode=1;}).finally(()=>p.$disconnect());
