const assert = require('node:assert/strict');
const { readFileSync } = require('node:fs');
const { join } = require('node:path');

const fixture = JSON.parse(readFileSync(join(__dirname, '../prisma/fixtures/musubi-nursery-2026-09-confirmed.json'), 'utf8'));
assert.equal(fixture.targetMonth, '2026-09');
assert.equal(fixture.staff.length, 23);
assert.equal(fixture.staff.filter((row) => row.rotationEligible).length, 20);
assert.deepEqual(fixture.staff.filter((row) => !row.rotationEligible).map((row) => row.department), ['FOOD_SERVICE','FOOD_SERVICE','FOOD_SERVICE']);
assert.equal(fixture.patterns.some((row) => row.code === '09' && row.label === '⑨'), true, '最新正式回答どおり土曜新⑨を園fixtureに持つ');
assert.deepEqual(fixture.confirmedCorrections.saturdayRenumbering.flatMap((row) => row.dates).sort(), ['2026-09-05','2026-09-05','2026-09-19']);
assert.ok(fixture.confirmedCorrections.saturdayRenumbering.every((row) => row.sourcePattern === '08' && row.pattern === '09'));
const noRotation = fixture.patterns.find((row) => row.code === 'NO_ROTATION');
assert.equal(noRotation.isWorking, true, 'シフト無しは出勤');
assert.equal(noRotation.countsTowardRotation, false, 'シフト無しは保育ローテーション外');
assert.notEqual(noRotation.code, 'OFF', 'シフト無しを休へ変換しない');
assert.equal(fixture.confirmedCorrections.nonRotationWork.reduce((sum,row) => sum + (row.dates?.length ?? 0),0), 6);
assert.deepEqual(fixture.confirmedCorrections.individualException, { staffCode:'S012',date:'2026-09-28',pattern:'NORMAL',endTime:'15:00' });
assert.deepEqual(fixture.confirmedCorrections.monthlyPatternLimit, { staffCode:'S012',pattern:'01',count:1,sourceMeaning:'①は月1回' });
assert.deepEqual(fixture.patterns.find((row) => row.code === '01'), { code:'01',label:'①',startTime:'07:30',endTime:'16:00',countsTowardRotation:true });
assert.deepEqual(fixture.patterns.find((row) => row.code === '02'), { code:'02',label:'②',startTime:'08:00',endTime:'16:30',countsTowardRotation:true });
assert.deepEqual(fixture.patterns.find((row) => row.code === '05'), { code:'05',label:'⑤',startTime:'10:00',endTime:'18:30',countsTowardRotation:true });
assert.equal(fixture.staff.find((row) => row.code === 'S019').fixedPattern, '01', '①の固定1名は支援担当S019');
assert.equal(fixture.staff.find((row) => row.code === 'S016').fixedPattern, '02', '②の固定1名は原資料22行のS016');
assert.equal(fixture.confirmedCorrections.withdrawnConditions[0].status, 'WITHDRAWN_THEN_SUPERSEDED');
assert.deepEqual(fixture.confirmedCorrections.weeklyPatternGroupLimit.patterns, ['01','02','03','04','05','06']);
assert.deepEqual(fixture.confirmedCorrections.weeklyPatternGroupLimit.exemptStaffCodes, ['S008','S019','S016']);
assert.equal(fixture.confirmedCorrections.weeklyPatternGroupLimit.fixedPreferenceOverridesLimit, true);
assert.deepEqual(fixture.confirmedCorrections.weeklyPatternGroupLimit.relaxation, { enabled:true,maxPerWeek:2,minimumOnly:true,automaticThirdAssignment:false,activationMode:'FORMAL',historyYears:3,recentWindowDays:90,explanationLevel:'INFO' });
assert.deepEqual(fixture.confirmedCorrections.fixedPreferenceOverrides.map((row)=>`${row.staffCode}:${row.date}:${row.pattern}`), ['S005:2026-09-24:01','S010:2026-09-24:06','S013:2026-09-04:01']);
assert.deepEqual(fixture.confirmedCorrections.crossMonthTransition, { fromPattern:'05',toPattern:'01',rule:'⑤の翌日に①を割り当てない',readsPreviousConfirmedDate:true });
assert.deepEqual(fixture.confirmedCorrections.knownDateRepairs.map((row) => row.dates), [['2026-09-11','2026-09-14'],['2026-09-09','2026-09-29'],['2026-09-26']]);
console.log('Musubi September 2026 confirmed-data audit: PASS');
