const assert = require('node:assert/strict');
const { randomUUID, scryptSync } = require('node:crypto');
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const base = process.env.API_BASE_URL || 'http://localhost:8080/api';
const run = randomUUID().slice(0, 8); const password = `Paid-${run}!`; const email = `paid-${run}@e2e.invalid`;
const created = { tenantIds: [], userIds: [] };
const hash = (value) => { const salt = randomUUID().replaceAll('-', ''); return `${salt}:${scryptSync(value, salt, 64).toString('hex')}`; };
async function call(path, init = {}, token) { const response = await fetch(base + path, { ...init, headers: { 'content-type': 'application/json', ...(token ? { authorization: `Bearer ${token}` } : {}) } }); return { status: response.status, body: await response.json().catch(() => null) }; }
async function main() {
  const tenant = await prisma.tenant.create({ data: { name: `Paid leave ${run}` } }); created.tenantIds.push(tenant.id);
  const user = await prisma.user.create({ data: { email, displayName: 'Paid Admin', passwordHash: hash(password) } }); created.userIds.push(user.id);
  const staffUser = await prisma.user.create({ data: { email: `paid-staff-${run}@e2e.invalid`, displayName: 'Paid General Staff', passwordHash: hash(password) } }); created.userIds.push(staffUser.id);
  await prisma.membership.create({ data: { tenantId: tenant.id, userId: user.id, role: 'ADMIN' } });
  await prisma.membership.create({ data: { tenantId: tenant.id, userId: staffUser.id, role: 'STAFF' } });
  await prisma.tenantSubscription.create({ data: { tenantId: tenant.id, plan: 'STANDARD', status: 'ACTIVE', currentPeriodStartedAt: new Date() } });
  const staff = await prisma.staff.create({ data: { tenantId: tenant.id, employeeNumber: `P-${run}`, displayName: 'Paid Staff' } });
  const otherTenant = await prisma.tenant.create({ data: { name: `Paid other ${run}` } }); created.tenantIds.push(otherTenant.id);
  const otherStaff = await prisma.staff.create({ data: { tenantId: otherTenant.id, employeeNumber: `O-${run}`, displayName: 'Other Staff' } });
  const otherGrant = await prisma.paidLeaveGrant.create({ data: { tenantId: otherTenant.id, staffId: otherStaff.id, grantDate: new Date('2030-04-01Z'), validFrom: new Date('2030-04-01Z'), expiresAt: new Date('2032-03-31Z'), grantedHalfDays: 20, source: 'NORMAL_GRANT', createdByUserId: user.id } });
  const login = await call('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); assert.equal(login.status, 200); const token = login.body.accessToken;
  const staffLogin = await call('/auth/login', { method: 'POST', body: JSON.stringify({ email: `paid-staff-${run}@e2e.invalid`, password }) }); assert.equal(staffLogin.status, 200); assert.equal((await call(`/staff/${staff.id}/paid-leave/grants`, {}, staffLogin.body.accessToken)).status, 403, 'general staff cannot access paid leave administration');
  assert.equal((await call(`/staff/${staff.id}/paid-leave/grants`, {}, token)).status, 200);
  const grantResult = await call(`/staff/${staff.id}/paid-leave/grants`, { method: 'POST', body: JSON.stringify({ grantDate: '2030-04-01', validFrom: '2030-04-01', expiresAt: '2032-03-31', grantedHalfDays: 20, source: 'INITIAL_BALANCE', note: '人間確認済み初期残高' }) }, token); assert.equal(grantResult.status, 201, JSON.stringify(grantResult.body)); const grant = grantResult.body;
  const smallResult = await call(`/staff/${staff.id}/paid-leave/grants`, { method: 'POST', body: JSON.stringify({ grantDate: '2030-04-01', validFrom: '2030-04-01', expiresAt: '2032-03-31', grantedHalfDays: 1, source: 'ADJUSTMENT', note: '不足検証' }) }, token); assert.equal(smallResult.status, 201); const small = smallResult.body;
  const full = await call(`/staff/${staff.id}/paid-leave/usages/confirm`, { method: 'POST', body: JSON.stringify({ usageDate: '2030-05-01', unit: 'DAY', allocations: [{ grantId: grant.id, allocatedHalfDays: 2 }], decisionNote: '本人と管理者が相談し確定' }) }, token); assert.equal(full.status, 201, JSON.stringify(full.body)); assert.equal(full.body.status, 'CONFIRMED'); assert.equal(full.body.confirmedByUserId, user.id); assert.ok(full.body.confirmedAt);
  const half = await call(`/staff/${staff.id}/paid-leave/usages/confirm`, { method: 'POST', body: JSON.stringify({ usageDate: '2030-05-02', unit: 'HALF_DAY', allocations: [{ grantId: grant.id, allocatedHalfDays: 1 }], decisionNote: '半日取得を人間確定' }) }, token); assert.equal(half.status, 201); assert.equal(half.body.usedHalfDays, 1);
  const cross = await call(`/staff/${staff.id}/paid-leave/usages/confirm`, { method: 'POST', body: JSON.stringify({ usageDate: '2030-05-03', unit: 'HALF_DAY', allocations: [{ grantId: otherGrant.id, allocatedHalfDays: 1 }], decisionNote: '越境不可' }) }, token); assert.equal(cross.status, 400);
  const over = await call(`/staff/${staff.id}/paid-leave/usages/confirm`, { method: 'POST', body: JSON.stringify({ usageDate: '2030-05-03', unit: 'DAY', allocations: [{ grantId: small.id, allocatedHalfDays: 2 }], decisionNote: '二重計上防止' }) }, token); assert.equal(over.status, 409);
  const proposal = await prisma.paidLeaveUsage.create({ data: { tenantId: tenant.id, staffId: staff.id, usageDate: new Date('2030-05-04Z'), unit: 'DAY', usedHalfDays: 2, status: 'PROPOSED', decisionNote: 'AI候補は未確定' } });
  await prisma.paidLeaveAllocation.create({ data: { tenantId: tenant.id, usageId: proposal.id, grantId: grant.id, allocatedHalfDays: 2 } });
  let balance = await call(`/staff/${staff.id}/paid-leave/balance?asOf=2030-06-01`, {}, token); assert.equal(balance.status, 200); assert.equal(balance.body.usedHalfDays, 3, 'proposal must not consume balance'); assert.equal(balance.body.availableHalfDays, 18);
  const corrected = await call(`/staff/${staff.id}/paid-leave/usages/${full.body.id}/correct`, { method: 'POST', body: JSON.stringify({ usageDate: '2030-05-01', unit: 'HALF_DAY', allocations: [{ grantId: grant.id, allocatedHalfDays: 1 }], decisionNote: '相談結果により半日へ訂正', reason: '入力単位訂正' }) }, token); assert.equal(corrected.status, 201, JSON.stringify(corrected.body)); assert.equal(corrected.body.corrected.status, 'CORRECTED'); assert.equal(corrected.body.replacement.status, 'CONFIRMED');
  const cancelled = await call(`/staff/${staff.id}/paid-leave/usages/${half.body.id}/cancel`, { method: 'POST', body: JSON.stringify({ reason: '本人との相談で取消' }) }, token); assert.equal(cancelled.status, 201); assert.equal(cancelled.body.status, 'CANCELLED');
  balance = await call(`/staff/${staff.id}/paid-leave/balance?asOf=2030-06-01`, {}, token); assert.equal(balance.body.usedHalfDays, 1); assert.equal(balance.body.availableHalfDays, 20);
  const audits = await prisma.auditLog.findMany({ where: { tenantId: tenant.id, targetType: { in: ['PaidLeaveGrant', 'PaidLeaveUsage'] } } }); for (const action of ['PAID_LEAVE_GRANT_CREATED','PAID_LEAVE_USAGE_CONFIRMED','PAID_LEAVE_USAGE_CORRECTED','PAID_LEAVE_USAGE_CANCELLED']) assert.ok(audits.some(row => row.action === action), action); assert.ok(audits.every(row => row.memberId === user.id));
  await prisma.staffWorkContract.create({ data: { tenantId: tenant.id, staffId: staff.id, effectiveFrom: new Date('2030-04-01Z'), annualizedTargetMinutes: 120000, prescribedDailyMinutes: 480 } });
  const backup = await call('/backups/export', { method: 'POST' }, token); assert.equal(backup.status, 201); assert.equal(backup.body.version, 3); for (const key of ['staffWorkContracts','paidLeaveGrants','paidLeaveUsages','paidLeaveAllocations']) assert.ok(Array.isArray(backup.body.data[key]) && backup.body.counts[key] === backup.body.data[key].length, key);
  const usages = await call(`/staff/${staff.id}/paid-leave/usages`, {}, token); assert.equal(usages.status, 200); assert.ok(usages.body.some(row => row.id === proposal.id && row.status === 'PROPOSED'));
  await prisma.tenant.update({ where: { id: tenant.id }, data: { timezone: 'Invalid/Timezone' } }); assert.equal((await call(`/staff/${staff.id}/paid-leave/balance`, {}, token)).status, 409, 'invalid tenant timezone fails closed'); await prisma.tenant.update({ where: { id: tenant.id }, data: { timezone: 'Asia/Tokyo' } });
  for (let index = 0; index < 5; index += 1) {
    const day = String(index + 10).padStart(2, '0');
    const raceGrantResult = await call(`/staff/${staff.id}/paid-leave/grants`, { method: 'POST', body: JSON.stringify({ grantDate: `2031-01-${day}`, validFrom: '2031-01-01', expiresAt: '2031-12-31', grantedHalfDays: 2, source: 'ADJUSTMENT', note: `同時確定 ${index}` }) }, token); assert.equal(raceGrantResult.status, 201); const raceGrant = raceGrantResult.body;
    const confirmBody = JSON.stringify({ usageDate: `2031-02-${day}`, unit: 'DAY', allocations: [{ grantId: raceGrant.id, allocatedHalfDays: 2 }], decisionNote: `同時確定 ${index}` });
    const confirms = await Promise.all([call(`/staff/${staff.id}/paid-leave/usages/confirm`, { method: 'POST', body: confirmBody }, token), call(`/staff/${staff.id}/paid-leave/usages/confirm`, { method: 'POST', body: confirmBody }, token)]);
    assert.deepEqual(confirms.map(row => row.status).sort(), [201, 409], `同時確定 ${index}`);
    const allocated = await prisma.paidLeaveAllocation.aggregate({ where: { grantId: raceGrant.id, usage: { status: 'CONFIRMED' } }, _sum: { allocatedHalfDays: true } }); assert.equal(allocated._sum.allocatedHalfDays, 2);

    const cancelTarget = confirms.find(row => row.status === 201).body;
    const cancels = await Promise.all([call(`/staff/${staff.id}/paid-leave/usages/${cancelTarget.id}/cancel`, { method: 'POST', body: JSON.stringify({ reason: `同時取消A ${index}` }) }, token), call(`/staff/${staff.id}/paid-leave/usages/${cancelTarget.id}/cancel`, { method: 'POST', body: JSON.stringify({ reason: `同時取消B ${index}` }) }, token)]);
    assert.deepEqual(cancels.map(row => row.status).sort(), [201, 409], `同時取消 ${index}`);
    const cancelLogs = await prisma.auditLog.findMany({ where: { tenantId: tenant.id, action: 'PAID_LEAVE_USAGE_CANCELLED', targetId: cancelTarget.id } }); assert.equal(cancelLogs.length, 1); const cancelledRow = await prisma.paidLeaveUsage.findUniqueOrThrow({ where: { id: cancelTarget.id } }); assert.equal(cancelledRow.cancellationReason, cancels.find(row => row.status === 201).body.cancellationReason);

    const voidGrantResult = await call(`/staff/${staff.id}/paid-leave/grants`, { method: 'POST', body: JSON.stringify({ grantDate: `2031-03-${day}`, validFrom: '2031-03-01', expiresAt: '2031-12-31', grantedHalfDays: 1, source: 'ADJUSTMENT', note: `確定対無効化 ${index}` }) }, token); assert.equal(voidGrantResult.status, 201); const voidGrant = voidGrantResult.body;
    const race = await Promise.all([call(`/staff/${staff.id}/paid-leave/usages/confirm`, { method: 'POST', body: JSON.stringify({ usageDate: `2031-04-${day}`, unit: 'HALF_DAY', allocations: [{ grantId: voidGrant.id, allocatedHalfDays: 1 }], decisionNote: `確定対無効化 ${index}` }) }, token), call(`/staff/${staff.id}/paid-leave/grants/${voidGrant.id}/void`, { method: 'POST', body: JSON.stringify({ reason: `競合無効化 ${index}` }) }, token)]);
    assert.equal(race.filter(row => row.status === 201).length, 1, `確定と無効化の片方だけ成功 ${index}`); assert.ok(race.some(row => row.status === 409), `競合は409 ${index}`);
    const finalGrant = await prisma.paidLeaveGrant.findUniqueOrThrow({ where: { id: voidGrant.id } }); const confirmedAllocations = await prisma.paidLeaveAllocation.count({ where: { grantId: voidGrant.id, usage: { status: 'CONFIRMED' } } }); assert.equal(Boolean(finalGrant.voidedAt) && confirmedAllocations > 0, false, `無効付与に確定割当なし ${index}`);

    const correctionGrantResult = await call(`/staff/${staff.id}/paid-leave/grants`, { method: 'POST', body: JSON.stringify({ grantDate: `2031-05-${day}`, validFrom: '2031-05-01', expiresAt: '2031-12-31', grantedHalfDays: 2, source: 'ADJUSTMENT', note: `同時訂正 ${index}` }) }, token); assert.equal(correctionGrantResult.status, 201); const correctionGrant = correctionGrantResult.body;
    const correctionSource = await call(`/staff/${staff.id}/paid-leave/usages/confirm`, { method: 'POST', body: JSON.stringify({ usageDate: `2031-06-${day}`, unit: 'HALF_DAY', allocations: [{ grantId: correctionGrant.id, allocatedHalfDays: 1 }], decisionNote: `訂正元 ${index}` }) }, token); assert.equal(correctionSource.status, 201);
    const correctionBody = JSON.stringify({ usageDate: `2031-07-${day}`, unit: 'HALF_DAY', allocations: [{ grantId: correctionGrant.id, allocatedHalfDays: 1 }], decisionNote: `訂正後 ${index}`, reason: `同時訂正 ${index}` });
    const corrections = await Promise.all([call(`/staff/${staff.id}/paid-leave/usages/${correctionSource.body.id}/correct`, { method: 'POST', body: correctionBody }, token), call(`/staff/${staff.id}/paid-leave/usages/${correctionSource.body.id}/correct`, { method: 'POST', body: correctionBody }, token)]);
    assert.deepEqual(corrections.map(row => row.status).sort(), [201, 409], `同時訂正 ${index}`); const sourceAfter = await prisma.paidLeaveUsage.findUniqueOrThrow({ where: { id: correctionSource.body.id } }); assert.equal(sourceAfter.status, 'CORRECTED'); assert.ok(sourceAfter.supersededById); assert.equal(await prisma.paidLeaveUsage.count({ where: { tenantId: tenant.id, id: sourceAfter.supersededById, status: 'CONFIRMED' } }), 1);
  }
  const crossUsage = await prisma.paidLeaveUsage.create({ data: { tenantId: otherTenant.id, staffId: otherStaff.id, usageDate: new Date('2031-08-01Z'), unit: 'HALF_DAY', usedHalfDays: 1, status: 'PROPOSED' } });
  const localUsage = await prisma.paidLeaveUsage.create({ data: { tenantId: tenant.id, staffId: staff.id, usageDate: new Date('2031-08-02Z'), unit: 'HALF_DAY', usedHalfDays: 1, status: 'PROPOSED' } });
  await assert.rejects(() => prisma.paidLeaveUsage.update({ where: { id: localUsage.id }, data: { supersededById: crossUsage.id } }), error => error?.code === 'P2003');
  await assert.rejects(() => prisma.paidLeaveAllocation.create({ data: { tenantId: tenant.id, usageId: localUsage.id, grantId: otherGrant.id, allocatedHalfDays: 1 } }), error => error?.code === 'P2003');
  console.log('Phase 4-A paid leave foundation E2E: PASS (tenant, grant, full/half, balance, cancel/correct, proposal isolation, audit, backup, repeated concurrency)');
}
main().finally(async()=>{for(const tenantId of created.tenantIds)await prisma.tenant.delete({where:{id:tenantId}}).catch(()=>undefined);if(created.userIds.length)await prisma.user.deleteMany({where:{id:{in:created.userIds}}}).catch(()=>undefined);await prisma.$disconnect();}).catch(error=>{console.error(error);process.exitCode=1;});
