const assert = require('node:assert/strict');
const { randomUUID, scryptSync } = require('node:crypto');
const { PrismaClient } = require('@prisma/client');
const { resolveIsolatedDatabaseUrl, resolveLocalApiBaseUrl } = require('./helpers/isolated-database.cjs');
const prisma = new PrismaClient({ datasourceUrl: resolveIsolatedDatabaseUrl() });
const base = resolveLocalApiBaseUrl();
const run = randomUUID().slice(0, 8); const password = `Paid-${run}!`; const email = `paid-${run}@e2e.invalid`;
const created = { tenantIds: [], userIds: [] };
const hash = (value) => { const salt = randomUUID().replaceAll('-', ''); return `${salt}:${scryptSync(value, salt, 64).toString('hex')}`; };
async function call(path, init = {}, token) { const response = await fetch(base + path, { ...init, headers: { 'content-type': 'application/json', ...(token ? { authorization: `Bearer ${token}` } : {}) } }); return { status: response.status, body: await response.json().catch(() => null) }; }
async function halfAssignment(tenantId, monthlyShiftId, staffId, workDate, modifierType='PM_PAID_LEAVE') { const assignment=await prisma.shiftAssignment.create({data:{tenantId,monthlyShiftId,staffId,workDate:new Date(`${workDate}Z`),shiftType:'NORMAL',startTime:'08:30',endTime:'17:00',breakMinutes:60}});await prisma.shiftAttendanceModifier.create({data:{tenantId,shiftAssignmentId:assignment.id,modifierType,sourceType:'ADMIN_CONFIRMED'}});return assignment; }
async function main() {
  const tenant = await prisma.tenant.create({ data: { name: `Paid leave ${run}` } }); created.tenantIds.push(tenant.id);
  const user = await prisma.user.create({ data: { email, displayName: 'Paid Admin', passwordHash: hash(password) } }); created.userIds.push(user.id);
  const staffUser = await prisma.user.create({ data: { email: `paid-staff-${run}@e2e.invalid`, displayName: 'Paid General Staff', passwordHash: hash(password) } }); created.userIds.push(staffUser.id);
  await prisma.membership.create({ data: { tenantId: tenant.id, userId: user.id, role: 'ADMIN' } });
  await prisma.membership.create({ data: { tenantId: tenant.id, userId: staffUser.id, role: 'STAFF' } });
  await prisma.tenantSubscription.create({ data: { tenantId: tenant.id, plan: 'STANDARD', status: 'ACTIVE', currentPeriodStartedAt: new Date() } });
  const staff = await prisma.staff.create({ data: { tenantId: tenant.id, employeeNumber: `P-${run}`, displayName: 'Paid Staff' } });
  const otherTenant = await prisma.tenant.create({ data: { name: `Paid other ${run}` } }); created.tenantIds.push(otherTenant.id);
  const otherStaff = await prisma.staff.create({ data: { tenantId: otherTenant.id, employeeNumber: `O-${run}`, displayName: 'Other Staff' } });
  const otherGrant = await prisma.paidLeaveGrant.create({ data: { tenantId: otherTenant.id, staffId: otherStaff.id, grantDate: new Date('2030-04-01Z'), validFrom: new Date('2030-04-01Z'), expiresAt: new Date('2032-03-31Z'), grantedHalfDays: 20, source: 'NORMAL_GRANT', createdByUserId: user.id } });
  const login = await call('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); assert.equal(login.status, 200); const token = login.body.accessToken;
  const staffLogin = await call('/auth/login', { method: 'POST', body: JSON.stringify({ email: `paid-staff-${run}@e2e.invalid`, password }) }); assert.equal(staffLogin.status, 200); assert.equal((await call(`/staff/${staff.id}/paid-leave/grants`, {}, staffLogin.body.accessToken)).status, 403, 'general staff cannot access paid leave administration');
  assert.equal((await call(`/staff/${staff.id}/paid-leave/grants`, {}, token)).status, 200);
  const grantResult = await call(`/staff/${staff.id}/paid-leave/grants`, { method: 'POST', body: JSON.stringify({ grantDate: '2030-04-01', validFrom: '2030-04-01', expiresAt: '2032-03-31', grantedHalfDays: 20, source: 'INITIAL_BALANCE', note: '人間確認済み初期残高' }) }, token); assert.equal(grantResult.status, 201, JSON.stringify(grantResult.body)); const grant = grantResult.body;
  const smallResult = await call(`/staff/${staff.id}/paid-leave/grants`, { method: 'POST', body: JSON.stringify({ grantDate: '2030-04-01', validFrom: '2030-04-01', expiresAt: '2032-03-31', grantedHalfDays: 1, source: 'ADJUSTMENT', note: '不足検証' }) }, token); assert.equal(smallResult.status, 201); const small = smallResult.body;
  const goldenStaff=await prisma.staff.create({data:{tenantId:tenant.id,employeeNumber:`G-${run}`,displayName:'Half-day Golden'}});
  const goldenGrantResult=await call(`/staff/${goldenStaff.id}/paid-leave/grants`,{method:'POST',body:JSON.stringify({grantDate:'2030-04-01',validFrom:'2030-04-01',expiresAt:'2032-03-31',grantedHalfDays:20,source:'INITIAL_BALANCE',note:'半休一気通貫'})},token);assert.equal(goldenGrantResult.status,201);const goldenGrant=goldenGrantResult.body;
  const goldenRequest=await prisma.shiftRequest.create({data:{tenantId:tenant.id,staffId:goldenStaff.id,requestDate:new Date('2030-09-25Z'),requestType:'HALF_DAY_PM',status:'APPROVED',reason:'午後半休'}});
  const goldenSchedule=await prisma.monthlyShift.create({data:{tenantId:tenant.id,targetMonth:new Date('2030-09-01Z'),status:'CONFIRMED',createdByUserId:user.id,confirmedByUserId:user.id,confirmedAt:new Date()}});
  const goldenAssignment=await prisma.shiftAssignment.create({data:{tenantId:tenant.id,monthlyShiftId:goldenSchedule.id,staffId:goldenStaff.id,workDate:new Date('2030-09-25Z'),shiftType:'NORMAL',startTime:'08:00',endTime:'16:30',breakMinutes:60}});
  await prisma.shiftAttendanceModifier.create({data:{tenantId:tenant.id,shiftAssignmentId:goldenAssignment.id,modifierType:'PM_PAID_LEAVE',sourceType:'APPROVED_SHIFT_REQUEST',sourceReference:goldenRequest.id}});
  const goldenBody={usageDate:'2030-09-25',unit:'HALF_DAY',allocations:[{grantId:goldenGrant.id,allocatedHalfDays:1}],shiftRequestId:goldenRequest.id,shiftAssignmentId:goldenAssignment.id,decisionNote:'勤務＋午後半休を確定'};
  const goldenUsage=await call(`/staff/${goldenStaff.id}/paid-leave/usages/confirm`,{method:'POST',body:JSON.stringify(goldenBody)},token);assert.equal(goldenUsage.status,201,JSON.stringify(goldenUsage.body));assert.equal(goldenUsage.body.usedHalfDays,1);assert.equal(goldenUsage.body.allocations[0].allocatedHalfDays,1);
  assert.equal((await call(`/staff/${goldenStaff.id}/paid-leave/usages/confirm`,{method:'POST',body:JSON.stringify(goldenBody)},token)).status,409,'同一申請と勤務の二重確定を拒否');
  const goldenBalance=await call(`/staff/${goldenStaff.id}/paid-leave/balance?asOf=2030-09-25`,{},token);assert.equal(goldenBalance.body.usedHalfDays,1);assert.equal(goldenBalance.body.availableHalfDays,19);
  const policyStaff=await prisma.staff.create({data:{tenantId:tenant.id,employeeNumber:`H-${run}`,displayName:'Holiday Policy'}});const policyGrantResult=await call(`/staff/${policyStaff.id}/paid-leave/grants`,{method:'POST',body:JSON.stringify({grantDate:'2030-04-01',validFrom:'2030-04-01',expiresAt:'2032-03-31',grantedHalfDays:6,source:'INITIAL_BALANCE',note:'休日有給方針'})},token);assert.equal(policyGrantResult.status,201);const policyGrant=policyGrantResult.body;
  const policyRequests=[];for(const [day,reason] of [['26','休園日'],['27','所定休日'],['28','希望休日']])policyRequests.push(await prisma.shiftRequest.create({data:{tenantId:tenant.id,staffId:policyStaff.id,requestDate:new Date(`2030-09-${day}Z`),requestType:'PAID_LEAVE',status:'APPROVED',reason}}));
  assert.equal(await prisma.paidLeaveUsage.count({where:{tenantId:tenant.id,staffId:policyStaff.id}}),0,'休園日・所定休日・希望休日の申請だけでは自動消化しない');
  const policyAssignment=await prisma.shiftAssignment.create({data:{tenantId:tenant.id,monthlyShiftId:goldenSchedule.id,staffId:policyStaff.id,workDate:new Date('2030-09-26Z'),shiftType:'PAID_LEAVE',startTime:null,endTime:null,breakMinutes:null}});
  const explicitPolicyUsage=await call(`/staff/${policyStaff.id}/paid-leave/usages/confirm`,{method:'POST',body:JSON.stringify({usageDate:'2030-09-26',unit:'DAY',allocations:[{grantId:policyGrant.id,allocatedHalfDays:2}],shiftRequestId:policyRequests[0].id,shiftAssignmentId:policyAssignment.id,decisionNote:'管理者が就業規則を確認して明示確定'})},token);assert.equal(explicitPolicyUsage.status,201,JSON.stringify(explicitPolicyUsage.body));assert.equal(explicitPolicyUsage.body.usedHalfDays,2,'管理者明示確定時だけ正式フローへ進む');
  const maySchedule=await prisma.monthlyShift.create({data:{tenantId:tenant.id,targetMonth:new Date('2030-05-01Z'),status:'CONFIRMED',createdByUserId:user.id,confirmedByUserId:user.id,confirmedAt:new Date()}});
  const may1Half=await halfAssignment(tenant.id,maySchedule.id,staff.id,'2030-05-01','AM_PAID_LEAVE');const may2Half=await halfAssignment(tenant.id,maySchedule.id,staff.id,'2030-05-02');const may3Half=await halfAssignment(tenant.id,maySchedule.id,staff.id,'2030-05-03');const may5Half=await halfAssignment(tenant.id,maySchedule.id,staff.id,'2030-05-05');
  assert.equal((await call(`/staff/${staff.id}/paid-leave/usages/confirm`, { method: 'POST', body: JSON.stringify({ usageDate: '2030-05-06', unit: 'HALF_DAY', allocations: [{ grantId: grant.id, allocatedHalfDays: 1 }], decisionNote: '基礎勤務なしは確定不可' }) }, token)).status,409,'半休は基礎勤務Assignmentなしで確定しない');
  const full = await call(`/staff/${staff.id}/paid-leave/usages/confirm`, { method: 'POST', body: JSON.stringify({ usageDate: '2030-05-01', unit: 'DAY', allocations: [{ grantId: grant.id, allocatedHalfDays: 2 }], decisionNote: '本人と管理者が相談し確定' }) }, token); assert.equal(full.status, 201, JSON.stringify(full.body)); assert.equal(full.body.status, 'CONFIRMED'); assert.equal(full.body.confirmedByUserId, user.id); assert.ok(full.body.confirmedAt);
  const half = await call(`/staff/${staff.id}/paid-leave/usages/confirm`, { method: 'POST', body: JSON.stringify({ usageDate: '2030-05-02', unit: 'HALF_DAY', allocations: [{ grantId: grant.id, allocatedHalfDays: 1 }], shiftAssignmentId:may2Half.id, decisionNote: '半日取得を人間確定' }) }, token); assert.equal(half.status, 201); assert.equal(half.body.usedHalfDays, 1);
  const cross = await call(`/staff/${staff.id}/paid-leave/usages/confirm`, { method: 'POST', body: JSON.stringify({ usageDate: '2030-05-03', unit: 'HALF_DAY', allocations: [{ grantId: otherGrant.id, allocatedHalfDays: 1 }], shiftAssignmentId:may3Half.id, decisionNote: '越境不可' }) }, token); assert.equal(cross.status, 400);
  const over = await call(`/staff/${staff.id}/paid-leave/usages/confirm`, { method: 'POST', body: JSON.stringify({ usageDate: '2030-05-03', unit: 'DAY', allocations: [{ grantId: small.id, allocatedHalfDays: 2 }], decisionNote: '二重計上防止' }) }, token); assert.equal(over.status, 409);
  const proposal = await prisma.paidLeaveUsage.create({ data: { tenantId: tenant.id, staffId: staff.id, usageDate: new Date('2030-05-04Z'), unit: 'DAY', usedHalfDays: 2, status: 'PROPOSED', decisionNote: 'AI候補は未確定' } });
  await prisma.paidLeaveAllocation.create({ data: { tenantId: tenant.id, usageId: proposal.id, grantId: grant.id, allocatedHalfDays: 2 } });
  let balance = await call(`/staff/${staff.id}/paid-leave/balance?asOf=2030-06-01`, {}, token); assert.equal(balance.status, 200); assert.equal(balance.body.usedHalfDays, 3, 'proposal must not consume balance'); assert.equal(balance.body.availableHalfDays, 18);
  const corrected = await call(`/staff/${staff.id}/paid-leave/usages/${full.body.id}/correct`, { method: 'POST', body: JSON.stringify({ usageDate: '2030-05-01', unit: 'HALF_DAY', allocations: [{ grantId: grant.id, allocatedHalfDays: 1 }], shiftAssignmentId:may1Half.id, decisionNote: '相談結果により半日へ訂正', reason: '入力単位訂正' }) }, token); assert.equal(corrected.status, 201, JSON.stringify(corrected.body)); assert.equal(corrected.body.corrected.status, 'CORRECTED'); assert.equal(corrected.body.replacement.status, 'CONFIRMED');
  const cancelled = await call(`/staff/${staff.id}/paid-leave/usages/${half.body.id}/cancel`, { method: 'POST', body: JSON.stringify({ reason: '本人との相談で取消' }) }, token); assert.equal(cancelled.status, 201); assert.equal(cancelled.body.status, 'CANCELLED');
  balance = await call(`/staff/${staff.id}/paid-leave/balance?asOf=2030-06-01`, {}, token); assert.equal(balance.body.usedHalfDays, 1); assert.equal(balance.body.availableHalfDays, 20);
  const halfToFullGrantResult = await call(`/staff/${staff.id}/paid-leave/grants`, { method: 'POST', body: JSON.stringify({ grantDate: '2030-04-01', validFrom: '2030-04-01', expiresAt: '2032-03-31', grantedHalfDays: 2, source: 'ADJUSTMENT', note: '半日から全日への訂正検証' }) }, token); assert.equal(halfToFullGrantResult.status, 201); const halfToFullGrant = halfToFullGrantResult.body;
  const halfToFullSource = await call(`/staff/${staff.id}/paid-leave/usages/confirm`, { method: 'POST', body: JSON.stringify({ usageDate: '2030-05-05', unit: 'HALF_DAY', allocations: [{ grantId: halfToFullGrant.id, allocatedHalfDays: 1 }], shiftAssignmentId:may5Half.id, decisionNote: '訂正前の半日有給' }) }, token); assert.equal(halfToFullSource.status, 201);
  const halfToFull = await call(`/staff/${staff.id}/paid-leave/usages/${halfToFullSource.body.id}/correct`, { method: 'POST', body: JSON.stringify({ usageDate: '2030-05-05', unit: 'DAY', allocations: [{ grantId: halfToFullGrant.id, allocatedHalfDays: 2 }], decisionNote: '相談結果により全日へ訂正', reason: '入力単位訂正' }) }, token); assert.equal(halfToFull.status, 201, JSON.stringify(halfToFull.body)); assert.equal(halfToFull.body.corrected.status, 'CORRECTED'); assert.equal(halfToFull.body.replacement.unit, 'DAY'); assert.equal(halfToFull.body.replacement.usedHalfDays, 2);
  const cancelledFullReplacement = await call(`/staff/${staff.id}/paid-leave/usages/${halfToFull.body.replacement.id}/cancel`, { method: 'POST', body: JSON.stringify({ reason: '全日訂正後の取消検証' }) }, token); assert.equal(cancelledFullReplacement.status, 201); assert.equal(cancelledFullReplacement.body.status, 'CANCELLED');
  balance = await call(`/staff/${staff.id}/paid-leave/balance?asOf=2030-06-01`, {}, token); assert.equal(balance.body.usedHalfDays, 1, '訂正後の全日有給を取消すと残高を戻す'); assert.equal(balance.body.availableHalfDays, 22);
  const audits = await prisma.auditLog.findMany({ where: { tenantId: tenant.id, targetType: { in: ['PaidLeaveGrant', 'PaidLeaveUsage'] } } }); for (const action of ['PAID_LEAVE_GRANT_CREATED','PAID_LEAVE_USAGE_CONFIRMED','PAID_LEAVE_USAGE_CORRECTED','PAID_LEAVE_USAGE_CANCELLED']) assert.ok(audits.some(row => row.action === action), action); assert.ok(audits.every(row => row.memberId === user.id));
  await prisma.staffWorkContract.create({ data: { tenantId: tenant.id, staffId: staff.id, effectiveFrom: new Date('2030-04-01Z'), annualizedTargetMinutes: 120000, prescribedDailyMinutes: 480 } });
  const backup = await call('/backups/export', { method: 'POST' }, token); assert.equal(backup.status, 201); assert.equal(backup.body.version, 3); for (const key of ['staffWorkContracts','paidLeaveGrants','paidLeaveUsages','paidLeaveAllocations']) assert.ok(Array.isArray(backup.body.data[key]) && backup.body.counts[key] === backup.body.data[key].length, key);
  const backedGolden=backup.body.data.shiftAssignments.find(row=>row.id===goldenAssignment.id);assert.equal(backedGolden.attendanceModifier.modifierType,'PM_PAID_LEAVE','backupに勤務modifierを含める');assert.ok(backup.body.data.paidLeaveUsages.some(row=>row.id===goldenUsage.body.id));assert.ok(backup.body.data.paidLeaveAllocations.some(row=>row.usageId===goldenUsage.body.id));
  const usages = await call(`/staff/${staff.id}/paid-leave/usages`, {}, token); assert.equal(usages.status, 200); assert.ok(usages.body.some(row => row.id === proposal.id && row.status === 'PROPOSED'));
  await prisma.tenant.update({ where: { id: tenant.id }, data: { timezone: 'Invalid/Timezone' } }); assert.equal((await call(`/staff/${staff.id}/paid-leave/balance`, {}, token)).status, 409, 'invalid tenant timezone fails closed'); await prisma.tenant.update({ where: { id: tenant.id }, data: { timezone: 'Asia/Tokyo' } });
  for (let index = 0; index < 5; index += 1) {
    const day = String(index + 10).padStart(2, '0');
    const raceGrantResult = await call(`/staff/${staff.id}/paid-leave/grants`, { method: 'POST', body: JSON.stringify({ grantDate: `2031-01-${day}`, validFrom: '2031-01-01', expiresAt: '2031-12-31', grantedHalfDays: 2, source: 'ADJUSTMENT', note: `同時確定 ${index}` }) }, token); assert.equal(raceGrantResult.status, 201); const raceGrant = raceGrantResult.body;
    const confirmBody = JSON.stringify({ usageDate: `2031-02-${day}`, unit: 'DAY', allocations: [{ grantId: raceGrant.id, allocatedHalfDays: 2 }], decisionNote: `同時確定 ${index}` });
    const confirms = await Promise.all([call(`/staff/${staff.id}/paid-leave/usages/confirm`, { method: 'POST', body: confirmBody }, token), call(`/staff/${staff.id}/paid-leave/usages/confirm`, { method: 'POST', body: confirmBody }, token)]);
    assert.deepEqual(confirms.map(row => row.status).sort(), [201, 409], `同時確定 ${index}`);
    const allocated = await prisma.paidLeaveAllocation.aggregate({ where: { grantId: raceGrant.id, usage: { status: 'CONFIRMED' } }, _sum: { allocatedHalfDays: true } }); assert.equal(allocated._sum.allocatedHalfDays, 2);

    const cancelTarget = confirms.find(row => row.status === 201).body;
    const cancels = await Promise.all([call(`/staff/${staff.id}/paid-leave/usages/${cancelTarget.id}/cancel`, { method: 'POST', body: JSON.stringify({ reason: `同時取消A ${index}` }) }, token), call(`/staff/${staff.id}/paid-leave/usages/${cancelTarget.id}/cancel`, { method: 'POST', body: JSON.stringify({ reason: `同時取消B ${index}` }) }, token)]);
    assert.deepEqual(cancels.map(row => row.status).sort(), [201, 409], `同時取消 ${index}`);
    const cancelLogs = await prisma.auditLog.findMany({ where: { tenantId: tenant.id, action: 'PAID_LEAVE_USAGE_CANCELLED', targetId: cancelTarget.id } }); assert.equal(cancelLogs.length, 1); const cancelledRow = await prisma.paidLeaveUsage.findUniqueOrThrow({ where: { id: cancelTarget.id } }); assert.equal(cancelledRow.cancellationReason, cancels.find(row => row.status === 201).body.cancellationReason);

    const voidGrantResult = await call(`/staff/${staff.id}/paid-leave/grants`, { method: 'POST', body: JSON.stringify({ grantDate: `2031-03-${day}`, validFrom: '2031-03-01', expiresAt: '2031-12-31', grantedHalfDays: 1, source: 'ADJUSTMENT', note: `確定対無効化 ${index}` }) }, token); assert.equal(voidGrantResult.status, 201); const voidGrant = voidGrantResult.body;
    const aprilSchedule=await prisma.monthlyShift.upsert({where:{tenantId_targetMonth:{tenantId:tenant.id,targetMonth:new Date('2031-04-01Z')}},create:{tenantId:tenant.id,targetMonth:new Date('2031-04-01Z'),status:'CONFIRMED',createdByUserId:user.id,confirmedByUserId:user.id,confirmedAt:new Date()},update:{}});const aprilHalf=await halfAssignment(tenant.id,aprilSchedule.id,staff.id,`2031-04-${day}`);
    const race = await Promise.all([call(`/staff/${staff.id}/paid-leave/usages/confirm`, { method: 'POST', body: JSON.stringify({ usageDate: `2031-04-${day}`, unit: 'HALF_DAY', allocations: [{ grantId: voidGrant.id, allocatedHalfDays: 1 }], shiftAssignmentId:aprilHalf.id, decisionNote: `確定対無効化 ${index}` }) }, token), call(`/staff/${staff.id}/paid-leave/grants/${voidGrant.id}/void`, { method: 'POST', body: JSON.stringify({ reason: `競合無効化 ${index}` }) }, token)]);
    assert.equal(race.filter(row => row.status === 201).length, 1, `確定と無効化の片方だけ成功 ${index}`); assert.ok(race.some(row => row.status === 409), `競合は409 ${index}`);
    const finalGrant = await prisma.paidLeaveGrant.findUniqueOrThrow({ where: { id: voidGrant.id } }); const confirmedAllocations = await prisma.paidLeaveAllocation.count({ where: { grantId: voidGrant.id, usage: { status: 'CONFIRMED' } } }); assert.equal(Boolean(finalGrant.voidedAt) && confirmedAllocations > 0, false, `無効付与に確定割当なし ${index}`);

    const correctionGrantResult = await call(`/staff/${staff.id}/paid-leave/grants`, { method: 'POST', body: JSON.stringify({ grantDate: `2031-05-${day}`, validFrom: '2031-05-01', expiresAt: '2031-12-31', grantedHalfDays: 2, source: 'ADJUSTMENT', note: `同時訂正 ${index}` }) }, token); assert.equal(correctionGrantResult.status, 201); const correctionGrant = correctionGrantResult.body;
    const juneSchedule=await prisma.monthlyShift.upsert({where:{tenantId_targetMonth:{tenantId:tenant.id,targetMonth:new Date('2031-06-01Z')}},create:{tenantId:tenant.id,targetMonth:new Date('2031-06-01Z'),status:'CONFIRMED',createdByUserId:user.id,confirmedByUserId:user.id,confirmedAt:new Date()},update:{}});const julySchedule=await prisma.monthlyShift.upsert({where:{tenantId_targetMonth:{tenantId:tenant.id,targetMonth:new Date('2031-07-01Z')}},create:{tenantId:tenant.id,targetMonth:new Date('2031-07-01Z'),status:'CONFIRMED',createdByUserId:user.id,confirmedByUserId:user.id,confirmedAt:new Date()},update:{}});const juneHalf=await halfAssignment(tenant.id,juneSchedule.id,staff.id,`2031-06-${day}`);const julyHalf=await halfAssignment(tenant.id,julySchedule.id,staff.id,`2031-07-${day}`,'AM_PAID_LEAVE');
    const correctionSource = await call(`/staff/${staff.id}/paid-leave/usages/confirm`, { method: 'POST', body: JSON.stringify({ usageDate: `2031-06-${day}`, unit: 'HALF_DAY', allocations: [{ grantId: correctionGrant.id, allocatedHalfDays: 1 }], shiftAssignmentId:juneHalf.id, decisionNote: `訂正元 ${index}` }) }, token); assert.equal(correctionSource.status, 201);
    const correctionBody = JSON.stringify({ usageDate: `2031-07-${day}`, unit: 'HALF_DAY', allocations: [{ grantId: correctionGrant.id, allocatedHalfDays: 1 }], shiftAssignmentId:julyHalf.id, decisionNote: `訂正後 ${index}`, reason: `同時訂正 ${index}` });
    const corrections = await Promise.all([call(`/staff/${staff.id}/paid-leave/usages/${correctionSource.body.id}/correct`, { method: 'POST', body: correctionBody }, token), call(`/staff/${staff.id}/paid-leave/usages/${correctionSource.body.id}/correct`, { method: 'POST', body: correctionBody }, token)]);
    assert.deepEqual(corrections.map(row => row.status).sort(), [201, 409], `同時訂正 ${index}`); const sourceAfter = await prisma.paidLeaveUsage.findUniqueOrThrow({ where: { id: correctionSource.body.id } }); assert.equal(sourceAfter.status, 'CORRECTED'); assert.ok(sourceAfter.supersededById); assert.equal(await prisma.paidLeaveUsage.count({ where: { tenantId: tenant.id, id: sourceAfter.supersededById, status: 'CONFIRMED' } }), 1);
  }
  const crossUsage = await prisma.paidLeaveUsage.create({ data: { tenantId: otherTenant.id, staffId: otherStaff.id, usageDate: new Date('2031-08-01Z'), unit: 'HALF_DAY', usedHalfDays: 1, status: 'PROPOSED' } });
  const localUsage = await prisma.paidLeaveUsage.create({ data: { tenantId: tenant.id, staffId: staff.id, usageDate: new Date('2031-08-02Z'), unit: 'HALF_DAY', usedHalfDays: 1, status: 'PROPOSED' } });
  await assert.rejects(() => prisma.paidLeaveUsage.update({ where: { id: localUsage.id }, data: { supersededById: crossUsage.id } }), error => error?.code === 'P2003');
  await assert.rejects(() => prisma.paidLeaveAllocation.create({ data: { tenantId: tenant.id, usageId: localUsage.id, grantId: otherGrant.id, allocatedHalfDays: 1 } }), error => error?.code === 'P2003');
  console.log('Phase 4-A paid leave foundation E2E: PASS (tenant, grant, full/half, balance, cancel/correct, proposal isolation, audit, backup, repeated concurrency)');
}
main().finally(async()=>{for(const tenantId of created.tenantIds)await prisma.tenant.delete({where:{id:tenantId}}).catch(()=>undefined);if(created.userIds.length)await prisma.user.deleteMany({where:{id:{in:created.userIds}}}).catch(()=>undefined);await prisma.$disconnect();}).catch(error=>{console.error(error);process.exitCode=1;});
