const assert = require('node:assert/strict');
const { randomUUID, scryptSync } = require('node:crypto');
const { AssignedClass, EmploymentType, MembershipRole, PrismaClient, ShiftType } = require('@prisma/client');
const prisma = new PrismaClient(); const base = process.env.API_BASE_URL || 'http://localhost:8080/api'; const run = randomUUID().slice(0, 8); let tenantId;
const hash = (password) => { const salt = randomUUID().replaceAll('-', ''); return `${salt}:${scryptSync(password, salt, 64).toString('hex')}`; };
async function call(path, init = {}, token) { const response = await fetch(`${base}${path}`, { ...init, headers: { 'content-type': 'application/json', ...(token ? { authorization: `Bearer ${token}` } : {}), ...init.headers } }); return { status: response.status, body: await response.json().catch(() => null) }; }
async function login(email, password) { const response = await call('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); assert.equal(response.status, 200); return response.body.accessToken; }
async function main() {
  const password = `Sprint6-${run}!`; const tenant = await prisma.tenant.create({ data: { name: `Sprint6園 ${run}` } }); tenantId = tenant.id;
  const admin = await prisma.user.create({ data: { email: `s6-admin-${run}@e2e.local`, displayName: '管理者', passwordHash: hash(password) } }); const staffUser = await prisma.user.create({ data: { email: `s6-staff-${run}@e2e.local`, displayName: '職員', passwordHash: hash(password) } });
  await prisma.membership.createMany({ data: [{ tenantId, userId: admin.id, role: MembershipRole.ADMIN }, { tenantId, userId: staffUser.id, role: MembershipRole.STAFF }] });
  const rows = [['S6-E1', AssignedClass.AGE_0, { canWorkEarly: true, canWorkRegular: false, canWorkLate: false, earlyShiftOnly: true }], ['S6-E2', AssignedClass.AGE_0, { canWorkEarly: true, canWorkRegular: false, canWorkLate: false, earlyShiftOnly: true }], ['S6-L1', AssignedClass.AGE_1, { canWorkEarly: false, canWorkRegular: false, canWorkLate: true, lateShiftOnly: true }], ['S6-L2', AssignedClass.FREE, { canWorkEarly: false, canWorkRegular: false, canWorkLate: true, lateShiftOnly: true }], ['S6-N1', AssignedClass.SUPPORT, { canWorkEarly: false, canWorkRegular: true, canWorkLate: false }]];
  for (const [employeeNumber, assignedClass, rules] of rows) await prisma.staff.create({ data: { tenantId, employeeNumber, displayName: employeeNumber, assignedClass, employmentType: EmploymentType.FULL_TIME, ...rules } });
  await prisma.staff.create({ data: { tenantId, userId: staffUser.id, employeeNumber: 'S6-STAFF', displayName: '職員', employmentType: EmploymentType.FULL_TIME } });
  const adminToken = await login(admin.email, password); const staffToken = await login(staffUser.email, password);
  assert.equal((await call('/settings/shifts')).status, 401); assert.equal((await call('/settings/shifts', {}, staffToken)).status, 403);
  const defaults = await call('/settings/shifts', {}, adminToken); assert.equal(defaults.status, 200); assert.equal(defaults.body.weekdayEarlyRequired, 2);
  assert.equal((await call('/settings/shifts', { method: 'PATCH', body: JSON.stringify({ maxConsecutiveWorkDays: 0 }) }, adminToken)).status, 400);
  const update = await call('/settings/shifts', { method: 'PATCH', body: JSON.stringify({ sundayOperationEnabled: false, maxConsecutiveWorkDays: 1, maxConsecutiveEarlyDays: 1, maxConsecutiveLateDays: 1 }) }, adminToken); assert.equal(update.status, 200);
  const classes = await call('/settings/class-requirements', {}, adminToken); assert.equal(classes.status, 200); assert.equal(classes.body.length, 6);
  assert.equal((await call('/settings/class-requirements', { method: 'PATCH', body: JSON.stringify({ requirements: [{ classType: 'AGE_0', weekdayRequired: 1, saturdayRequired: 0, isActive: true }, { classType: 'AGE_0', weekdayRequired: 1, saturdayRequired: 0, isActive: true }] }) }, adminToken)).status, 400);
  const closedInput = { closedDate: '2034-01-02', name: 'テスト休園', note: 'Sprint6' }; const closed = await call('/closed-dates', { method: 'POST', body: JSON.stringify(closedInput) }, adminToken); assert.equal(closed.status, 201); assert.equal((await call('/closed-dates', { method: 'POST', body: JSON.stringify(closedInput) }, adminToken)).status, 409); assert.equal((await call('/closed-dates?month=2034-01', {}, adminToken)).body.length, 1); assert.equal((await call('/closed-dates?month=2034-01', {}, staffToken)).status, 200);
  const schedule = await call('/shifts', { method: 'POST', body: JSON.stringify({ month: '2034-01' }) }, adminToken); assert.equal(schedule.status, 201);
  const before = await prisma.shiftAssignment.count({ where: { monthlyShiftId: schedule.body.id } }); const precheck = await call(`/shifts/${schedule.body.id}/precheck`, { method: 'POST' }, adminToken); assert.equal(precheck.status, 201); assert.equal(precheck.body.canGenerate, true); assert.ok(precheck.body.warningSummary); assert.equal(await prisma.shiftAssignment.count({ where: { monthlyShiftId: schedule.body.id } }), before);
  assert.equal((await call(`/shifts/${schedule.body.id}/precheck`, { method: 'POST' }, staffToken)).status, 403);
  const generated = await call(`/shifts/${schedule.body.id}/generate`, { method: 'POST' }, adminToken); assert.equal(generated.status, 201); assert.ok(generated.body.warningSummary); assert.ok(generated.body.warnings.every((warning) => ['INFO','WARNING','ERROR'].includes(warning.level))); assert.equal(generated.body.closedDateCount, 1);
  const listed = await call('/shifts?month=2034-01', {}, adminToken); const closedAssignments = listed.body.assignments.filter((item) => item.workDate.slice(0, 10) === '2034-01-02'); assert.ok(closedAssignments.every((item) => item.shiftType === ShiftType.OFF)); const sunday = listed.body.assignments.filter((item) => item.workDate.slice(0, 10) === '2034-01-01'); assert.ok(sunday.every((item) => item.shiftType === ShiftType.OFF)); assert.ok(listed.body.assignments.some((item) => item.assignedClass));
  const other = await prisma.tenant.create({ data: { name: `別園 ${run}` } }); const foreign = await prisma.tenantClosedDate.create({ data: { tenantId: other.id, closedDate: new Date('2034-01-03T00:00:00.000Z'), name: '別園休園' } }); assert.equal((await call(`/closed-dates/${foreign.id}`, { method: 'DELETE' }, adminToken)).status, 404); await prisma.tenant.delete({ where: { id: other.id } });
  console.log('Sprint 6 API integration tests: PASS (18 scenarios)');
}
main().finally(async () => { if (tenantId) await prisma.tenant.deleteMany({ where: { id: tenantId } }).catch(() => undefined); await prisma.$disconnect(); }).catch((error) => { console.error(error); process.exitCode = 1; });
