const assert = require('node:assert/strict');
const { randomUUID, scryptSync } = require('node:crypto');
const { EmploymentType, MembershipRole, MonthlyShiftStatus, PrismaClient, ShiftType } = require('@prisma/client');
const prisma = new PrismaClient(); const base = process.env.API_BASE_URL || 'http://localhost:8080/api'; const run = randomUUID().slice(0,8); let tenantId;
const hash = (password) => { const salt=randomUUID().replaceAll('-',''); return `${salt}:${scryptSync(password,salt,64).toString('hex')}`; };
async function call(path,init={},token){const response=await fetch(`${base}${path}`,{...init,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`} : {}),...init.headers}});return {status:response.status,body:await response.json().catch(()=>null)};}
async function login(email,password){const response=await call('/auth/login',{method:'POST',body:JSON.stringify({email,password})});assert.equal(response.status,200);return response.body.accessToken;}
async function main(){const password=`Sprint7-${run}!`;const tenant=await prisma.tenant.create({data:{name:`Sprint7園 ${run}`}});tenantId=tenant.id;const admin=await prisma.user.create({data:{email:`s7-admin-${run}@e2e.local`,displayName:'管理者',passwordHash:hash(password)}});const requester=await prisma.user.create({data:{email:`s7-requester-${run}@e2e.local`,displayName:'申請職員',passwordHash:hash(password)}});const target=await prisma.user.create({data:{email:`s7-target-${run}@e2e.local`,displayName:'交換職員',passwordHash:hash(password)}});await prisma.membership.createMany({data:[{tenantId,userId:admin.id,role:MembershipRole.ADMIN},{tenantId,userId:requester.id,role:MembershipRole.STAFF},{tenantId,userId:target.id,role:MembershipRole.STAFF}]});const [requesterStaff,targetStaff]=await Promise.all([prisma.staff.create({data:{tenantId,userId:requester.id,employeeNumber:'S7-R',displayName:'申請職員',employmentType:EmploymentType.FULL_TIME}}),prisma.staff.create({data:{tenantId,userId:target.id,employeeNumber:'S7-T',displayName:'交換職員',employmentType:EmploymentType.FULL_TIME}})]);const schedule=await prisma.monthlyShift.create({data:{tenantId,targetMonth:new Date('2035-01-01T00:00:00.000Z'),status:MonthlyShiftStatus.CONFIRMED,createdByUserId:admin.id,confirmedByUserId:admin.id,confirmedAt:new Date()}});const date=new Date('2035-01-10T00:00:00.000Z');await prisma.shiftAssignment.createMany({data:[{tenantId,monthlyShiftId:schedule.id,staffId:requesterStaff.id,workDate:date,shiftType:ShiftType.EARLY,startTime:'07:00',endTime:'16:00'},{tenantId,monthlyShiftId:schedule.id,staffId:targetStaff.id,workDate:date,shiftType:ShiftType.LATE,startTime:'10:30',endTime:'20:00'}]});const adminToken=await login(admin.email,password);const requesterToken=await login(requester.email,password);const targetToken=await login(target.email,password);
assert.equal((await call('/notifications')).status,401);assert.equal((await call('/audit-logs',{},requesterToken)).status,403);assert.equal((await call('/shift-swaps/targets',{},requesterToken)).status,200);
const created=await call('/shift-swaps',{method:'POST',body:JSON.stringify({targetMemberId:target.id,requestDate:'2035-01-10',requestComment:'交代希望'})},requesterToken);assert.equal(created.status,201);const swapId=created.body.id;assert.equal((await call('/shift-swaps',{},requesterToken)).body.length,1);assert.equal((await call(`/shift-swaps/${swapId}`,{method:'PATCH',body:JSON.stringify({status:'APPROVED'})},requesterToken)).status,403);
const targetNotifications=await call('/notifications',{},targetToken);assert.equal(targetNotifications.status,200);assert.ok(targetNotifications.body.some((row)=>row.type==='SHIFT_SWAP_REQUEST'));const ownNotification=targetNotifications.body[0];assert.equal((await call(`/notifications/${ownNotification.id}/read`,{method:'PATCH'},requesterToken)).status,404);assert.equal((await call(`/notifications/${ownNotification.id}/read`,{method:'PATCH'},targetToken)).status,200);assert.equal((await call('/notifications/read-all',{method:'PATCH'},targetToken)).status,200);
const approved=await call(`/shift-swaps/${swapId}`,{method:'PATCH',body:JSON.stringify({status:'APPROVED',adminComment:'承認'})},adminToken);assert.equal(approved.status,200);assert.equal(approved.body.status,'APPROVED');const assignments=await prisma.shiftAssignment.findMany({where:{monthlyShiftId:schedule.id,workDate:date},orderBy:{staffId:'asc'}});const requesterAssignment=assignments.find(row=>row.staffId===requesterStaff.id);const targetAssignment=assignments.find(row=>row.staffId===targetStaff.id);assert.equal(requesterAssignment.shiftType,ShiftType.LATE);assert.equal(targetAssignment.shiftType,ShiftType.EARLY);
const second=await call('/shift-swaps',{method:'POST',body:JSON.stringify({targetMemberId:target.id,requestDate:'2035-01-10'})},requesterToken);assert.equal(second.status,201);assert.equal((await call(`/shift-swaps/${second.body.id}`,{method:'DELETE'},requesterToken)).status,200);const audit=await call('/audit-logs',{},adminToken);assert.equal(audit.status,200);assert.ok(audit.body.some(row=>row.action==='SHIFT_SWAP_CREATED'));assert.ok(audit.body.some(row=>row.action==='SHIFT_SWAP_APPROVED'));
const other=await prisma.tenant.create({data:{name:`別園 ${run}`}});const foreign=await prisma.shiftSwapRequest.create({data:{tenantId:other.id,requesterId:admin.id,targetMemberId:requester.id,requestDate:date}});assert.equal((await call(`/shift-swaps/${foreign.id}`,{method:'DELETE'},requesterToken)).status,404);await prisma.tenant.delete({where:{id:other.id}});console.log('Sprint 7 API integration tests: PASS (18 scenarios)');}
main().finally(async()=>{if(tenantId)await prisma.tenant.deleteMany({where:{id:tenantId}}).catch(()=>undefined);await prisma.$disconnect();}).catch(error=>{console.error(error);process.exitCode=1;});
