const assert=require('node:assert/strict');
const{createHash,randomUUID}=require('node:crypto');
const{PrismaClient,SubscriptionPlan,SubscriptionStatus}=require('@prisma/client');
const prisma=new PrismaClient();const base=process.env.API_BASE_URL||'http://localhost:8080/api';
let tenantId,originalSubscription,otherTenantId;
async function call(path,init={},token){const r=await fetch(base+path,{...init,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})}});return{status:r.status,body:await r.json().catch(()=>null)}}
function stable(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(stable).join(',')}]`;return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(',')}}`}function checksum(v){return createHash('sha256').update(stable(v)).digest('hex')}
const input=(overrides={})=>({ruleType:'UNAVAILABLE_DAY_OF_WEEK',workPatternId:null,dayOfWeek:0,startDate:'2026-08-01',endDate:'2026-08-31',startTime:null,endTime:null,numericValue:null,booleanValue:null,priority:100,isHardConstraint:true,reason:'E2E条件',isActive:true,...overrides});
async function main(){
 const login=await call('/auth/login',{method:'POST',body:JSON.stringify({email:process.env.SEED_OWNER_EMAIL||'owner@demo.enshift.local',password:process.env.SEED_OWNER_PASSWORD||'ChangeMe123!'})});assert.equal(login.status,200);const token=login.body.accessToken;const me=await call('/me',{},token);tenantId=me.body.tenant.id;const staff=await prisma.staff.findFirstOrThrow({where:{tenantId,isActive:true}});originalSubscription=await prisma.tenantSubscription.findUniqueOrThrow({where:{tenantId}});
 await prisma.tenantSubscription.update({where:{tenantId},data:{plan:SubscriptionPlan.STANDARD,status:SubscriptionStatus.ACTIVE,trialEndsAt:null}});assert.equal((await call(`/staff/${staff.id}/work-rules`,{},token)).status,200);assert.equal((await call(`/staff/${staff.id}/work-rules`,{method:'POST',body:JSON.stringify(input())},token)).status,403,'Feature OFF書込拒否');await prisma.tenantSubscription.update({where:{tenantId},data:{plan:SubscriptionPlan.PROFESSIONAL}});
 let r=await call(`/staff/${staff.id}/work-rules`,{method:'POST',body:JSON.stringify(input())},token);assert.equal(r.status,201);const id=r.body.id;assert.equal((await call(`/staff/${staff.id}/work-rules`,{method:'POST',body:JSON.stringify(input())},token)).status,409,'完全重複');assert.equal((await call(`/staff/${staff.id}/work-rules`,{method:'POST',body:JSON.stringify(input({ruleType:'AVAILABLE_DAY_OF_WEEK'}))},token)).status,409,'完全一致期間');assert.equal((await call(`/staff/${staff.id}/work-rules`,{method:'POST',body:JSON.stringify(input({ruleType:'AVAILABLE_DAY_OF_WEEK',startDate:'2026-08-15',endDate:'2026-08-20'}))},token)).status,409,'部分期間重複');assert.equal((await call(`/staff/${staff.id}/work-rules`,{method:'POST',body:JSON.stringify(input({ruleType:'AVAILABLE_DAY_OF_WEEK',dayOfWeek:1,startDate:'2026-08-15',endDate:'2026-08-20'}))},token)).status,201,'曜日違い');assert.equal((await call(`/staff/${staff.id}/work-rules`,{method:'POST',body:JSON.stringify(input({ruleType:'AVAILABLE_DAY_OF_WEEK',startDate:'2026-09-01',endDate:'2026-09-05'}))},token)).status,201,'非重複期間');assert.equal((await call(`/staff/${staff.id}/work-rules`,{method:'POST',body:JSON.stringify(input({ruleType:'AVAILABLE_DAY_OF_WEEK',startDate:null,endDate:null}))},token)).status,409,'期間未指定は常時適用');
 assert.equal((await call(`/staff/${staff.id}/work-rules`,{method:'POST',body:JSON.stringify(input({ruleType:'MAX_WORK_DAYS_PER_WEEK',dayOfWeek:null,numericValue:8}))},token)).status,400);assert.equal((await call(`/staff/${staff.id}/work-rules`,{method:'POST',body:JSON.stringify(input({ruleType:'MAX_WORK_DAYS_PER_MONTH',dayOfWeek:null,numericValue:32}))},token)).status,400);assert.equal((await call(`/staff/${staff.id}/work-rules`,{method:'POST',body:JSON.stringify(input({ruleType:'MAX_WORK_MINUTES_PER_MONTH',dayOfWeek:null,numericValue:44641}))},token)).status,400);assert.equal((await call(`/staff/${staff.id}/work-rules`,{method:'POST',body:JSON.stringify(input({booleanValue:true}))},token)).status,400);assert.equal((await call(`/staff/${staff.id}/work-rules`,{method:'POST',body:JSON.stringify(input({reason:'bad\u0001reason'}))},token)).status,400);
 assert.equal((await call(`/staff/${staff.id}/work-rules/${id}`,{method:'PUT',body:JSON.stringify(input())},token)).status,200,'変更なし更新');assert.equal((await call(`/staff/${staff.id}/work-rules/${id}`,{method:'PUT',body:JSON.stringify(input({ruleType:'AVAILABLE_DAY_OF_WEEK',dayOfWeek:1,startDate:'2026-08-15',endDate:'2026-08-20'}))},token)).status,409,'更新時期間競合');assert.equal((await call(`/staff/${staff.id}/work-rules/${id}`,{method:'DELETE'},token)).status,200);r=await call(`/staff/${staff.id}/work-rules`,{method:'POST',body:JSON.stringify(input())},token);assert.equal(r.status,201);assert.equal(r.body.id,id,'無効ルールを再利用');assert.ok(await prisma.auditLog.findFirst({where:{tenantId,targetId:id,action:'STAFF_WORK_RULE_REACTIVATED'}}));
 const normal=(await call('/work-patterns',{},token)).body.find(p=>p.code==='NORMAL');const custom=await prisma.workPattern.create({data:{tenantId,code:`E2E_${randomUUID().slice(0,6).toUpperCase()}`,name:'E2E勤務',shortName:'E',startTime:'09:00',endTime:'18:00',isWorking:true,isActive:true}});r=await call(`/staff/${staff.id}/work-rules`,{method:'POST',body:JSON.stringify(input({ruleType:'PREFERRED_WORK_PATTERN',dayOfWeek:null,startDate:null,endDate:null,workPatternId:custom.id,isHardConstraint:false}))},token);assert.equal(r.status,201);const customRule=r.body;await prisma.workPattern.update({where:{id:custom.id},data:{isActive:false}});r=await call(`/staff/${staff.id}/work-rules`,{},token);assert.equal(r.body.find(x=>x.id===customRule.id).workPattern.isActive,false);assert.equal((await call(`/staff/${staff.id}/work-rules/${customRule.id}`,{method:'PUT',body:JSON.stringify(input({ruleType:'PREFERRED_WORK_PATTERN',dayOfWeek:null,startDate:null,endDate:null,workPatternId:custom.id,isHardConstraint:false,reason:'維持'}))},token)).status,200,'同一無効Pattern維持');assert.equal((await call(`/staff/${staff.id}/work-rules`,{method:'POST',body:JSON.stringify(input({ruleType:'FIXED_WORK_PATTERN',dayOfWeek:2,workPatternId:custom.id}))},token)).status,400,'無効Pattern新規拒否');assert.equal((await call(`/staff/${staff.id}/work-rules/${customRule.id}`,{method:'DELETE'},token)).status,200);await prisma.workPattern.update({where:{id:custom.id},data:{isActive:true}});assert.equal((await call(`/staff/${staff.id}/work-rules`,{method:'POST',body:JSON.stringify(input({ruleType:'FIXED_WORK_PATTERN',dayOfWeek:2,workPatternId:normal.id}))},token)).status,201);
 const inactive=await prisma.staff.create({data:{tenantId,employeeNumber:`INACTIVE-${randomUUID().slice(0,6)}`,displayName:'無効職員',isActive:false}});assert.equal((await call(`/staff/${inactive.id}/work-rules`,{},token)).status,200);assert.equal((await call(`/staff/${inactive.id}/work-rules`,{method:'POST',body:JSON.stringify(input())},token)).status,400);await prisma.staff.delete({where:{id:inactive.id}});
 const other=await prisma.tenant.create({data:{name:`別園-${randomUUID().slice(0,6)}`}});otherTenantId=other.id;const otherStaff=await prisma.staff.create({data:{tenantId:other.id,employeeNumber:'OTHER',displayName:'別園'}});await prisma.staffWorkRule.create({data:{tenantId:other.id,staffId:otherStaff.id,ruleType:'UNAVAILABLE_DAY_OF_WEEK',dayOfWeek:0,isActive:false}});assert.equal((await call(`/staff/${otherStaff.id}/work-rules`,{},token)).status,404);assert.equal((await call(`/staff/${staff.id}/work-rules`,{method:'POST',body:JSON.stringify(input({workPatternId:randomUUID(),ruleType:'FIXED_WORK_PATTERN'}))},token)).status,400);
 const backup=await call('/backups/export',{method:'POST'},token);assert.equal(backup.status,201);assert.ok(backup.body.data.staffWorkRules.some(x=>x.isActive===false));const legacy=structuredClone(backup.body);delete legacy.data.staffWorkRules;delete legacy.counts.staffWorkRules;legacy.integrity.checksum=checksum(legacy.data);assert.equal((await call('/backups/validate',{method:'POST',body:JSON.stringify({backup:legacy})},token)).status,201);const invalid=structuredClone(backup.body);invalid.data.staffWorkRules[0].booleanValue=true;invalid.integrity.checksum=checksum(invalid.data);assert.equal((await call('/backups/validate',{method:'POST',body:JSON.stringify({backup:invalid})},token)).status,422);console.log('StaffWorkRule integration tests: PASS');
}
main().finally(async()=>{if(tenantId)await prisma.staffWorkRule.deleteMany({where:{tenantId,reason:{in:['E2E条件','維持']}}}).catch(()=>{});if(tenantId)await prisma.workPattern.deleteMany({where:{tenantId,code:{startsWith:'E2E_'}}}).catch(()=>{});if(otherTenantId)await prisma.tenant.delete({where:{id:otherTenantId}}).catch(()=>{});if(tenantId&&originalSubscription)await prisma.tenantSubscription.update({where:{tenantId},data:{plan:originalSubscription.plan,status:originalSubscription.status,trialEndsAt:originalSubscription.trialEndsAt}}).catch(()=>{});await prisma.$disconnect()}).catch(e=>{console.error(e);process.exitCode=1});
