const assert = require('node:assert/strict'); const { createHash, randomUUID } = require('node:crypto');
const { PrismaClient, SubscriptionPlan, SubscriptionStatus } = require('@prisma/client');
const prisma = new PrismaClient();
const base = process.env.API_BASE_URL || 'http://localhost:8080/api';
const email = process.env.SEED_OWNER_EMAIL || 'owner@demo.enshift.local'; const password = process.env.SEED_OWNER_PASSWORD || 'ChangeMe123!';
let tenantId; let originalSubscription; let scheduleId;
async function call(path, init = {}, token) { const response = await fetch(base + path, { ...init, headers: { 'content-type': 'application/json', ...(token ? { authorization: `Bearer ${token}` } : {}), ...init.headers } }); return { status: response.status, body: await response.json().catch(() => null) }; }
function stable(value) { if (value === null || typeof value !== 'object') return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(stable).join(',')}]`; return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stable(value[key])}`).join(',')}}`; }
function checksum(value) { return createHash('sha256').update(stable(value), 'utf8').digest('hex'); }
async function main() {
  const login = await call('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); assert.equal(login.status, 200); const token = login.body.accessToken;
  const me = await call('/me', {}, token); tenantId = me.body.tenant.id;
  originalSubscription = await prisma.tenantSubscription.findUniqueOrThrow({ where: { tenantId } }); await prisma.tenantFeature.deleteMany({ where: { tenantId, featureCode: 'ADVANCED_WORK_PATTERNS' } });
  await prisma.tenantSubscription.update({ where: { tenantId }, data: { plan: SubscriptionPlan.STANDARD, status: SubscriptionStatus.ACTIVE, trialEndsAt: null } });
  let result = await call('/work-patterns', {}, token); assert.equal(result.status, 200); assert.deepEqual(result.body.map((row) => row.code), ['EARLY', 'NORMAL', 'LATE', 'OFF']); assert.ok(result.body.every((row) => row.isSystem)); assert.equal(result.body.filter((row) => row.isDefault).length, 1); assert.equal(result.body.find((row) => row.code === 'NORMAL').isDefault, true);
  const beforeSecondGet = new Map(result.body.map((row) => [row.code, row.updatedAt])); result = await call('/work-patterns', {}, token); assert.ok(result.body.every((row) => row.updatedAt === beforeSecondGet.get(row.code)), '繰り返しGETはUPDATEしない');
  const missingLate = result.body.find((row) => row.code === 'LATE'); await prisma.workPattern.delete({ where: { id: missingLate.id } }); result = await call('/work-patterns', {}, token); assert.equal(result.body.length, 4); assert.ok(result.body.some((row) => row.code === 'LATE'), '一部欠損を補完'); result = await call('/work-patterns', {}, token); assert.equal(result.body.length, 4, '補完は冪等');
  let early = result.body.find((row) => row.code === 'EARLY'); const safeEarly = { code: early.code, name: early.name, shortName: early.shortName, displayOrder: early.displayOrder, startTime: early.startTime, endTime: early.endTime, breakMinutes: early.breakMinutes, color: early.color, isWorking: early.isWorking, isDefault: early.isDefault, isActive: early.isActive };
  result = await call(`/work-patterns/${early.id}`, { method: 'PUT', body: JSON.stringify({ ...safeEarly, name: '早番' }) }, token); assert.equal(result.status, 200, 'Feature OFFでもsystem安全編集可');
  result = await call(`/work-patterns/${early.id}`, { method: 'PUT', body: JSON.stringify({ ...safeEarly, isWorking: false, startTime: null, endTime: null, breakMinutes: 0 }) }, token); assert.equal(result.status, 400);
  result = await call(`/work-patterns/${early.id}`, { method: 'PUT', body: JSON.stringify({ ...safeEarly, isActive: false }) }, token); assert.equal(result.status, 400);
  const off = (await call('/work-patterns', {}, token)).body.find((row) => row.code === 'OFF'); const offInput = { code: off.code, name: off.name, shortName: off.shortName, displayOrder: off.displayOrder, startTime: off.startTime, endTime: off.endTime, breakMinutes: off.breakMinutes, color: off.color, isWorking: off.isWorking, isDefault: off.isDefault, isActive: off.isActive };
  result = await call(`/work-patterns/${off.id}`, { method: 'PUT', body: JSON.stringify({ ...offInput, isWorking: true, startTime: '09:00', endTime: '18:00', breakMinutes: 60 }) }, token); assert.equal(result.status, 400);
  await call(`/work-patterns/${early.id}`, { method: 'PUT', body: JSON.stringify(safeEarly) }, token);
  const input = { code: 'MID', name: '中番', shortName: '中', displayOrder: 25, startTime: '09:00', endTime: '18:00', breakMinutes: 60, color: '#0f766e', isWorking: true, isDefault: false, isActive: true };
  result = await call('/work-patterns', { method: 'POST', body: JSON.stringify(input) }, token); assert.equal(result.status, 403, 'Feature OFFでは追加不可');
  await prisma.tenantSubscription.update({ where: { tenantId }, data: { plan: SubscriptionPlan.PROFESSIONAL } });
  result = await call('/work-patterns', { method: 'POST', body: JSON.stringify({ ...input, isDefault: true }) }, token); assert.equal(result.status, 201); const id = result.body.id;
  let defaults = await prisma.workPattern.findMany({ where: { tenantId, isDefault: true, isActive: true } }); assert.equal(defaults.length, 1); assert.equal(defaults[0].id, id, '既定切替はtransactionで一意');
  result = await call(`/work-patterns/${id}`, { method: 'PUT', body: JSON.stringify({ ...input, isDefault: false }) }, token); assert.equal(result.status, 400, '既定0件となる更新を拒否');
  result = await call(`/work-patterns/${id}`, { method: 'PUT', body: JSON.stringify({ ...input, name: '中間勤務', isDefault: true }) }, token); assert.equal(result.status, 200); assert.equal(result.body.name, '中間勤務');
  result = await call('/work-patterns', {}, token); assert.ok(result.body.some((row) => row.code === 'MID'));
  early = result.body.find((row) => row.code === 'EARLY'); const normal = result.body.find((row) => row.code === 'NORMAL'); const normalInput = { code: normal.code, name: normal.name, shortName: normal.shortName, displayOrder: normal.displayOrder, startTime: normal.startTime, endTime: normal.endTime, breakMinutes: normal.breakMinutes, color: normal.color, isWorking: normal.isWorking, isDefault: true, isActive: normal.isActive }; await call(`/work-patterns/${normal.id}`, { method: 'PUT', body: JSON.stringify(normalInput) }, token);
  defaults = await prisma.workPattern.findMany({ where: { tenantId, isDefault: true, isActive: true } }); assert.deepEqual(defaults.map((row) => row.code), ['NORMAL']);
  const originalEarly = { code: early.code, name: early.name, shortName: early.shortName, displayOrder: early.displayOrder, startTime: early.startTime, endTime: early.endTime, breakMinutes: early.breakMinutes, color: early.color, isWorking: early.isWorking, isDefault: early.isDefault, isActive: early.isActive };
  result = await call(`/work-patterns/${early.id}`, { method: 'PUT', body: JSON.stringify({ ...originalEarly, startTime: '06:45', endTime: '15:45' }) }, token); assert.equal(result.status, 200);
  const month = `205${Math.floor(Math.random() * 9)}-${String(Math.floor(Math.random() * 11) + 1).padStart(2, '0')}`; result = await call('/shifts', { method: 'POST', body: JSON.stringify({ month }) }, token); assert.equal(result.status, 201); scheduleId = result.body.id;
  result = await call(`/shifts/${scheduleId}/generate`, { method: 'POST' }, token); assert.equal(result.status, 201);
  const generatedEarly = await prisma.shiftAssignment.findFirst({ where: { monthlyShiftId: scheduleId, shiftType: 'EARLY' } }); assert.ok(generatedEarly); assert.equal(generatedEarly.startTime, '06:45'); assert.equal(generatedEarly.workPatternId, early.id, 'Generator結果はsystem WorkPatternを参照する');
  await call(`/work-patterns/${early.id}`, { method: 'PUT', body: JSON.stringify(originalEarly) }, token);
  result = await call(`/work-patterns/${early.id}`, { method: 'DELETE' }, token); assert.equal(result.status, 400, 'system patternは削除不可');
  result = await call(`/work-patterns/${id}`, { method: 'DELETE' }, token); assert.equal(result.status, 200); assert.equal(result.body.isActive, false);
  const audit = await prisma.auditLog.findFirst({ where: { tenantId, targetType: 'WorkPattern', targetId: id }, orderBy: { createdAt: 'desc' } }); assert.ok(audit);
  const backupResult = await call('/backups/export', { method: 'POST' }, token); assert.equal(backupResult.status, 201); assert.equal(backupResult.body.version, 3); assert.equal(backupResult.body.counts.workPatterns, backupResult.body.data.workPatterns.length); assert.ok(backupResult.body.data.workPatterns.some((row) => row.code === 'NORMAL')); assert.ok(backupResult.body.data.shiftAssignments.some((row) => Object.prototype.hasOwnProperty.call(row, 'workPatternId')));
  const legacyV2 = structuredClone(backupResult.body); legacyV2.version = 2; for (const key of ['workPatterns','staffWorkContracts','paidLeaveGrants','paidLeaveUsages','paidLeaveAllocations']) { delete legacyV2.data[key]; delete legacyV2.counts[key]; } for (const row of legacyV2.data.shiftAssignments) delete row.workPatternId; legacyV2.integrity.checksum = checksum(legacyV2.data); result = await call('/backups/validate', { method: 'POST', body: JSON.stringify({ backup: legacyV2 }) }, token); assert.equal(result.status, 201, '旧version 2も互換');
  const invalidReference = structuredClone(backupResult.body); invalidReference.data.shiftAssignments[0].workPatternId = randomUUID(); invalidReference.integrity.checksum = checksum(invalidReference.data); result = await call('/backups/validate', { method: 'POST', body: JSON.stringify({ backup: invalidReference }) }, token); assert.equal(result.status, 422, '存在しないWorkPattern参照を拒否');
  const crossTenant = structuredClone(backupResult.body); crossTenant.data.workPatterns[0].tenantId = randomUUID(); crossTenant.integrity.checksum = checksum(crossTenant.data); result = await call('/backups/validate', { method: 'POST', body: JSON.stringify({ backup: crossTenant }) }, token); assert.equal(result.status, 422, '別Tenant WorkPatternを拒否');
  console.log('WorkPattern integration tests: PASS (system compatibility, feature ON/OFF, CRUD and audit)');
}
main().finally(async () => { if (scheduleId) await prisma.monthlyShift.deleteMany({ where: { id: scheduleId } }).catch(() => undefined); if (tenantId) { await prisma.workPattern.deleteMany({ where: { tenantId, code: 'MID' } }).catch(() => undefined); await prisma.tenantFeature.deleteMany({ where: { tenantId, featureCode: 'ADVANCED_WORK_PATTERNS' } }).catch(() => undefined); } if (tenantId && originalSubscription) await prisma.tenantSubscription.update({ where: { tenantId }, data: { plan: originalSubscription.plan, status: originalSubscription.status, trialEndsAt: originalSubscription.trialEndsAt } }).catch(() => undefined); await prisma.$disconnect(); }).catch((error) => { console.error(error); process.exitCode = 1; });
