import { useEffect, useState } from 'react';
import { api, type RuleException, type Staff, type TenantEvent, type WorkPattern } from '../../api/client';

type Props = { token: string; month: string; onSaved: () => unknown };

export function TenantCalendarManagement({ token }: { token: string }) {
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7));
  const [events, setEvents] = useState<TenantEvent[]>([]);
  const [exceptions, setExceptions] = useState<RuleException[]>([]);
  const [staff, setStaff] = useState<Staff[]>([]);
  const [patterns, setPatterns] = useState<WorkPattern[]>([]);
  const [message, setMessage] = useState('');
  const load = () => Promise.all([api.tenantEvents(token, month), api.ruleExceptions(token, month), api.staff(token), api.workPatterns(token)]).then(([eventRows, exceptionRows, staffRows, patternRows]) => {
    setEvents(eventRows); setExceptions(exceptionRows); setStaff(staffRows.filter((row) => row.isActive)); setPatterns(patternRows.filter((row) => row.isActive && row.isWorking)); setMessage('');
  }).catch((error) => setMessage(error instanceof Error ? error.message : '読み込めませんでした。'));
  useEffect(() => { void load(); }, [month]);
  return <section className="mt-6 space-y-5">
    <div className="card p-5"><label className="text-sm font-bold">対象月<input className="input ml-3" type="month" value={month} onChange={(event) => setMonth(event.target.value)} /></label><p className="mt-2 text-sm text-[var(--ink-muted)]">行事、基礎勤務、「この日だけ」の管理者承認を月ごとに管理します。永久ルールは変更しません。</p>{message && <p className="mt-2 text-sm text-red-700">{message}</p>}</div>
    <EventForm token={token} month={month} onSaved={load} />
    <div className="card p-5"><h2 className="text-lg font-black">登録済み行事</h2>{events.length ? <ul className="mt-3 space-y-2">{events.map((row) => <li className="flex items-center justify-between rounded-xl bg-[var(--canvas)] p-3" key={row.id}><span><strong>{row.eventDate.slice(0, 10)} {row.name}</strong><small className="block text-[var(--ink-muted)]">固定時間職員は契約時間を維持・根拠：{row.sourceReference || '画面登録'}</small></span><button className="btn-quiet" onClick={() => api.deleteTenantEvent(token, row.id).then(load)}>削除</button></li>)}</ul> : <p className="mt-3 text-sm">この月の行事はありません。</p>}</div>
    <DecisionForm token={token} month={month} staff={staff} patterns={patterns} onSaved={load} />
    <WeeklyExceptionForm token={token} month={month} onSaved={load} />
    <div className="card p-5"><h2 className="text-lg font-black">日別の管理者判断</h2>{exceptions.length ? <ul className="mt-3 space-y-2">{exceptions.map((row) => <li className="flex items-center justify-between rounded-xl bg-amber-50 p-3" key={row.id}><span><strong>{row.exceptionDate.slice(0, 10)} {exceptionLabel(row)}</strong><small className="block text-amber-900">{row.reason}・根拠：{row.sourceReference || '管理画面'}</small></span><button className="btn-quiet" onClick={() => api.deleteRuleException(token, row.id).then(load)}>取消</button></li>)}</ul> : <p className="mt-3 text-sm">この月の承認済み判断はありません。</p>}</div>
  </section>;
}

function EventForm({ token, month, onSaved }: Props) { const [date, setDate] = useState(`${month}-01`); const [name, setName] = useState(''); return <form className="card p-5" onSubmit={(event) => { event.preventDefault(); void api.createTenantEvent(token, { eventDate: date, name, eventType: 'ONSITE', fixedTimeStaffAllowed: true, sourceType: 'ADMIN_CONFIRMED', sourceReference: '管理画面で確認' }).then(() => { setName(''); onSaved(); }); }}><h2 className="text-lg font-black">月間行事を追加</h2><p className="mt-1 text-sm text-[var(--ink-muted)]">固定時間職員は行事があっても契約時間を維持します。</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><input className="input" type="date" value={date} onChange={(event) => setDate(event.target.value)} required /><input className="input" placeholder="行事名" value={name} onChange={(event) => setName(event.target.value)} required /></div><button className="btn-primary mt-3">行事を登録</button></form>; }

function DecisionForm({ token, month, staff, patterns, onSaved }: Props & { staff: Staff[]; patterns: WorkPattern[] }) {
  const [date, setDate] = useState(`${month}-01`); const [staffCode, setStaffCode] = useState(''); const [patternCode, setPatternCode] = useState(''); const [mode, setMode] = useState<'STAFF_WORK_PATTERN' | 'HARD_RULE_OVERRIDE'>('STAFF_WORK_PATTERN'); const [reason, setReason] = useState('');
  return <form className="card p-5" onSubmit={(event) => { event.preventDefault(); void api.createRuleException(token, { exceptionDate: date, exceptionType: mode, configuration: { staffCode, workPatternCode: patternCode, originalCondition: mode === 'HARD_RULE_OVERRIDE' ? '対象職員に適用されるHARD業務条件' : '半休等の基礎勤務が未確定', approvedException: mode === 'HARD_RULE_OVERRIDE' ? `${date}だけ${patternCode}を許可` : `${date}の基礎勤務を${patternCode}に指定`, ...(mode === 'HARD_RULE_OVERRIDE' ? { ruleType: 'DATE_LIMITED_ADMIN_OVERRIDE' } : {}) }, reason, sourceType: 'ADMIN_CONFIRMED', sourceReference: '日別判断画面で管理者承認' }).then(() => { setReason(''); onSaved(); }); }}><h2 className="text-lg font-black">未確定・条件矛盾への日別判断</h2><p className="mt-1 text-sm text-[var(--ink-muted)]">基礎勤務を指定するか、HARD条件との矛盾をその日だけ承認します。永久ルールには変換されません。</p><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><input className="input" type="date" value={date} onChange={(event) => setDate(event.target.value)} required /><select className="input" value={staffCode} onChange={(event) => setStaffCode(event.target.value)} required><option value="">職員を選択</option>{staff.map((row) => <option key={row.id} value={row.employeeNumber}>{row.employeeNumber} {row.displayName}</option>)}</select><select className="input" value={patternCode} onChange={(event) => setPatternCode(event.target.value)} required><option value="">勤務を選択</option>{patterns.map((row) => <option key={row.id} value={row.code}>{row.shortName || row.name}</option>)}</select><select className="input" value={mode} onChange={(event) => setMode(event.target.value as typeof mode)}><option value="STAFF_WORK_PATTERN">基礎勤務を指定</option><option value="HARD_RULE_OVERRIDE">その日だけ例外承認</option></select><input className="input" placeholder="判断理由（必須）" value={reason} onChange={(event) => setReason(event.target.value)} required /></div><button className="btn-primary mt-3">日別判断を記録</button></form>;
}

function WeeklyExceptionForm({ token, month, onSaved }: Props) { const [date, setDate] = useState(`${month}-01`); const [weeklyMaximum, setWeeklyMaximum] = useState(3); const [count, setCount] = useState(1); return <form className="card p-5" onSubmit={(event) => { event.preventDefault(); void api.createRuleException(token, { exceptionDate: date, exceptionType: 'WEEKLY_ROTATION_LIMIT', configuration: { maxWeeklyRotationCount: weeklyMaximum, maxAssignments: count, originalCondition: '通常週上限', approvedException: `対象職員を週${weeklyMaximum}回まで許可` }, reason: '必要人数不足への日付限定対応', sourceType: 'ADMIN_CONFIRMED', sourceReference: '管理画面で管理者承認' }).then(onSaved); }}><h2 className="text-lg font-black">人数不足への日別判断</h2><p className="mt-1 text-sm text-[var(--ink-muted)]">generatorは自動で上限を破りません。影響を確認した管理者だけが、この日・この人数に限定して承認できます。</p><div className="mt-3 flex flex-wrap gap-3"><input className="input" type="date" value={date} onChange={(event) => setDate(event.target.value)} required /><label className="text-sm font-bold">週の許容回数<input className="input ml-2 w-20" type="number" min="3" max="7" value={weeklyMaximum} onChange={(event) => setWeeklyMaximum(Number(event.target.value))} /></label><label className="text-sm font-bold">許可対象人数<input className="input ml-2 w-20" type="number" min="1" max="20" value={count} onChange={(event) => setCount(Number(event.target.value))} /></label></div><button className="btn-primary mt-3">この日だけ許可</button></form>; }

function exceptionLabel(row: RuleException) { const type = row.exceptionType.split(':')[0]; if (type === 'STAFF_WORK_PATTERN') return `${String(row.configuration.staffCode)}：基礎勤務 ${String(row.configuration.workPatternCode)} を指定`; if (type === 'HARD_RULE_OVERRIDE') return `${String(row.configuration.staffCode)}：${String(row.configuration.workPatternCode)} を日付限定で例外承認`; return `週${Number(row.configuration.maxWeeklyRotationCount)}回までを最大${Number(row.configuration.maxAssignments)}名許可`; }
